apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-nm
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-nm
spec:
  selector:
    matchLabels:
      app: {{ include "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: yarn-nm
  minAvailable: {{ .Values.hadoop.yarn.nodeManager.pdbMinAvailable }}
