/* Generated By:JavaCC: Do not edit this line. AccumuloSyntaxParserConstants.java */
package datawave.core.query.language.parser.lucene;

public interface AcumuloSyntaxParserConstants {

    int EOF = 0;
    int _NUM_CHAR = 1;
    int _ESCAPED_CHAR = 2;
    int _TERM_START_CHAR = 3;
    int _TERM_CHAR = 4;
    int _FUNCTION_ARG_CHAR = 5;
    int _FUNCTION_ARG_BEGINEND_CHAR = 6;
    int _FUNCTION_ARG_ALL_CHAR1 = 7;
    int _FUNCTION_ARG_ALL_CHAR2 = 8;
    int _FUNCTION_ARG = 9;
    int _WHITESPACE = 10;
    int _QUOTED_CHAR = 11;
    int AND = 13;
    int OR = 14;
    int NOT = 15;
    int FUNCTION = 16;
    int LPAREN = 17;
    int RPAREN = 18;
    int OP_COLON = 19;
    int CARAT = 20;
    int QUOTED = 21;
    int TERM = 22;
    int FUZZY_SLOP = 23;
    int REGEXPTERM = 24;
    int RANGEIN_START = 25;
    int RANGEEX_START = 26;
    int NUMBER = 27;
    int RANGE_TO = 28;
    int RANGEIN_END = 29;
    int RANGEEX_END = 30;
    int RANGE_QUOTED = 31;
    int RANGE_GOOP = 32;

    int Boost = 0;
    int Range = 1;
    int DEFAULT = 2;

    String[] tokenImage = {"<EOF>", "<_NUM_CHAR>", "<_ESCAPED_CHAR>", "<_TERM_START_CHAR>", "<_TERM_CHAR>", "<_FUNCTION_ARG_CHAR>",
            "<_FUNCTION_ARG_BEGINEND_CHAR>", "<_FUNCTION_ARG_ALL_CHAR1>", "<_FUNCTION_ARG_ALL_CHAR2>", "<_FUNCTION_ARG>", "<_WHITESPACE>", "<_QUOTED_CHAR>",
            "<token of kind 12>", "\"AND\"", "\"OR\"", "\"NOT\"", "<FUNCTION>", "\"(\"", "\")\"", "\":\"", "\"^\"", "<QUOTED>", "<TERM>", "<FUZZY_SLOP>",
            "<REGEXPTERM>", "\"[\"", "\"{\"", "<NUMBER>", "\"TO\"", "\"]\"", "\"}\"", "<RANGE_QUOTED>", "<RANGE_GOOP>",};

}
