<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>gov.nsa.datawave.webservices</groupId>
        <artifactId>datawave-ws-security-parent</artifactId>
        <version>9.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>datawave-ws-security</artifactId>
    <packaging>ejb</packaging>
    <name>${project.artifactId}</name>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-guava</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave</groupId>
            <artifactId>datawave-common-test</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.commons</groupId>
            <artifactId>datawave-commons-security</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>authorization-api</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.webservices</groupId>
            <artifactId>datawave-ws-common-util</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>gov.nsa.datawave.core</groupId>
                    <artifactId>datawave-core-common-util</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.webservices</groupId>
            <artifactId>datawave-ws-security-elytron</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk16</artifactId>
        </dependency>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.container</groupId>
            <artifactId>arquillian-weld-embedded</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jaxb-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.woodstox</groupId>
            <artifactId>woodstox-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.webservices</groupId>
            <artifactId>datawave-ws-common</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-client</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-security</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-undertow</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave</groupId>
            <artifactId>datawave-in-memory-accumulo</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>accumulo-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>dictionary-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>query-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.webservices</groupId>
            <artifactId>datawave-ws-common</artifactId>
            <version>${project.version}</version>
            <classifier>tests</classifier>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.easymock</groupId>
            <artifactId>easymock</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit</groupId>
            <artifactId>arquillian-junit-container</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.weld</groupId>
            <artifactId>weld-core-impl</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${version.mockito}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>${version.mockito}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <targetPath>test-classes</targetPath>
                <filtering>true</filtering>
                <directory>src/test/resources</directory>
                <excludes>
                    <exclude>*.pkcs12</exclude>
                    <exclude>*.p12</exclude>
                    <exclude>*.jks</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <outputDirectory>lib</outputDirectory>
                            <!-- just grab the non-provided runtime dependencies -->
                            <includeArtifactIds>jackson-datatype-guava,guava,bcprov-jdk16</includeArtifactIds>
                            <excludeTransitive>false</excludeTransitive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <configuration>
                    <ejbVersion>3.2</ejbVersion>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                        <manifestEntries>
                            <Dependencies>io.undertow.core,io.undertow.servlet</Dependencies>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <excludes>
                        <!-- Do not include any classes from the examples package in the final jar. We do not want any
                        beans in there to actually be deployed. -->
                        <exclude>**/datawave/security/examples/**/*</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
