spring:
  datasource:
    cachedResults:
      url: 'jdbc:mysql://${datawave.mysql.host}:3306/${datawave.mysql.dbname}?zeroDateTimeBehavior=convertToNull'
      username: '${datawave.mysql.username}'
      password: '${datawave.mysql.password}'
      driver-class-name: 'com.mysql.cj.jdbc.Driver'
      hikari:
        # default: 30000
        connection-timeout: 5000
        # default: 600000
        idle-timeout: 900000
        # default: maximum-pool-size
        minimum-idle: ${datawave.mysql.pool.min-size}
        # default: 10
        maximum-pool-size: ${datawave.mysql.pool.max-size}

datawave:
  mysql:
    host: 'mysql'
    dbname: 'cachedresults'
    pool:
      min-size: '5'
      max-size: '20'
    username: 'datawave'
    password: 'secret'
  query:
    cachedResults:
      enabled: ${CACHED_RESULTS:false}
      remoteQuery:
        queryServiceUri: "https://query:8443/query/v1/query"
        # unlimited
        maxBytesToBuffer: -1
      numFields: 900
      statementTemplates:
        createTableTemplate: |
          CREATE TABLE IF NOT EXISTS template (
          _user_ VARCHAR(200) NOT NULL,
          _queryId_ VARCHAR(200) NOT NULL,
          _logicName_ VARCHAR(200) NOT NULL,
          _datatype_ VARCHAR(35) NOT NULL,
          _eventId_ VARCHAR(50) NOT NULL,
          _row_ LONGTEXT NOT NULL,
          _colf_ LONGTEXT NOT NULL,
          _markings_ VARCHAR(400) NOT NULL,
          _column_markings_ LONGTEXT NOT NULL,
          _column_timestamps_ LONGTEXT NOT NULL,
          %FIELD_DEFINITIONS%
          ) ENGINE = MyISAM
        createTable: "CREATE TABLE %TABLE% LIKE template"
        dropTable: "DROP TABLE %TABLE%"
        dropView: "DROP VIEW %TABLE%"
        insert: |
          INSERT INTO %TABLE% (
          _user_, 
          _queryId_, 
          _logicName_, 
          _datatype_, 
          _eventId_, 
          _row_, 
          _colf_, 
          _markings_, 
          _column_markings_, 
          _column_timestamps_,
          %PREPARED_FIELDS%
          ) VALUES (
          ?,
          ?,
          ?,
          ?,
          ?,
          ?,
          ?,
          ?,
          ?,
          ?,
          %PREPARED_VALUES%
          )
        createView: "CREATE VIEW %VIEW%(%VIEW_COLS%) AS SELECT %TABLE_COLS% FROM %TABLE%"
