# This is where you set properties which are specific to pool1
executor:
  poolName: 'pool1'

datawave:
  swagger:
    title: "Query Executor Service (Pool 1)"
    description: "REST API provided by the Query Executor Service"
  connection:
    factory:
      pools:
        'pool1':
          zookeepers: '${accumulo.zookeepers}'
          instance: '${accumulo.instanceName}'
          username: '${accumulo.username}'
          password: '${accumulo.password}'
          lowPriorityPoolSize: 40
          normalPriorityPoolSize: 40
          highPriorityPoolSize: 40
          adminPriorityPoolSize: 40
