# This is where you set properties which are specific to pool2
executor:
  poolName: 'pool2'

datawave:
  swagger:
    title: "Query Executor Service (Pool 2)"
    description: "REST API provided by the Query Executor Service"
