# This is where you set properties which are specific to pool1
executor:
  poolName: 'pool1'

datawave:
  swagger:
    title: "Query Executor Service (Pool 1)"
    description: "REST API provided by the Query Executor Service"
