logging:
  level:
    root: INFO
    datawave.microservice: DEBUG
  
datawave:
  swagger:
    title: "Map Service"
    description: "REST API provided by the Map Service"
  map:
    metadataTableName: 'datawave.metadata'
    accumulo:
      zookeepers: "${accumulo.zookeepers}"
      instance-name: '${accumulo.instanceName}'
      username: '${accumulo.username}'
      password: '${accumulo.password}'
    basemaps:
    - title: 'Open Street Map'
      urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
      maxZoom: 18
      attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      defaultEnabled: true
    - title: 'Esri World Imagery'
      urlTemplate: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
      maxZoom: 18
      attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'

  metadata:
    all-metadata-auths:
        - PRIVATE,PUBLIC
    type-substitutions:
      "[datawave.data.type.DateType]": "datawave.data.type.RawDateType"