<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>gov.nsa.datawave</groupId>
        <artifactId>datawave-parent</artifactId>
        <version>9.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <groupId>gov.nsa.datawave</groupId>
    <artifactId>datawave-in-memory-accumulo</artifactId>
    <version>9.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>Datawave InMemory Accumulo</name>
    <url>https://code.nsa.gov/datawave-in-memory-accumulo</url>
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:https://github.com/NationalSecurityAgency/datawave.git</connection>
        <developerConnection>scm:git:git@github.com:NationalSecurityAgency/datawave.git</developerConnection>
        <tag>core/in-memory-accumulo-8.0.0</tag>
        <url>https://github.com/NationalSecurityAgency/datawave</url>
    </scm>
    <dependencyManagement>
        <dependencies>
            <?SORTPOM IGNORE?>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-bom</artifactId>
                <version>${version.log4j}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${version.junit5}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <?SORTPOM RESUME?>
            <dependency>
                <groupId>commons-collections</groupId>
                <artifactId>commons-collections</artifactId>
                <version>3.2.2</version>
            </dependency>
            <dependency>
                <groupId>org.apache.accumulo</groupId>
                <artifactId>accumulo-server-base</artifactId>
                <version>${version.accumulo}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.zookeeper</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-client</artifactId>
                <version>${version.hadoop}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-common</artifactId>
                <version>${version.hadoop}</version>
                <exclusions>
                    <exclusion>
                        <groupId>ch.qos.reload4j</groupId>
                        <artifactId>reload4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${version.mockito}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.accumulo</groupId>
            <artifactId>accumulo-server-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <tagNameFormat>@{project.version}</tagNameFormat>
                    <releaseProfiles>dist</releaseProfiles>
                    <arguments>-Ddist</arguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>autoformat</id>
            <activation>
                <property>
                    <!-- You should deactivate this profile in CI to keep git happy -->
                    <name>!skipFormat</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.diffplug.spotless</groupId>
                        <artifactId>spotless-maven-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>com.github.ekryd.sortpom</groupId>
                        <artifactId>sortpom-maven-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>net.revelc.code.formatter</groupId>
                        <artifactId>formatter-maven-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-enforcer-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <!-- The dist profile (activated with -Ddist) triggers building of source and javadoc artifacts. -->
        <profile>
            <id>dist</id>
            <activation>
                <property>
                    <name>dist</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-javadoc-plugin</artifactId>
                        <executions>
                            <!-- build javadoc jars per module for publishing to the repo -->
                            <execution>
                                <id>module-apidocs</id>
                                <goals>
                                    <goal>jar</goal>
                                </goals>
                                <phase>package</phase>
                                <configuration>
                                    <encoding>UTF-8</encoding>
                                    <outputDirectory>${project.build.directory}/apidocs</outputDirectory>
                                    <additionalJOption>-J-Xmx768m</additionalJOption>
                                    <tags>
                                        <tag>
                                            <name>HTTP</name>
                                            <placement>m</placement>
                                            <head>HTTP Return Codes</head>
                                        </tag>
                                        <tag>
                                            <name>RequestHeader</name>
                                            <placement>m</placement>
                                            <head>HTTP Request Headers</head>
                                        </tag>
                                        <tag>
                                            <name>ResponseHeader</name>
                                            <placement>m</placement>
                                            <head>HTTP Response Headers</head>
                                        </tag>
                                        <tag>
                                            <name>returnWrapped</name>
                                            <placement>m</placement>
                                            <head>Output</head>
                                        </tag>
                                    </tags>
                                    <show>private</show>
                                    <quiet>true</quiet>
                                    <javaApiLinks>
                                        <property>
                                            <name>api_1.8</name>
                                            <value>http://docs.oracle.com/javase/8/docs/api</value>
                                        </property>
                                    </javaApiLinks>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-source-plugin</artifactId>
                        <executions>
                            <!-- Build source jars and attach them to the project for publishing -->
                            <execution>
                                <id>java-sources</id>
                                <goals>
                                    <goal>jar-no-fork</goal>
                                    <goal>test-jar-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
