// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exception_messages.proto

package datawave.webservice.query.exception;

public final class ExceptionMessages {
    private ExceptionMessages() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public interface QueryExceptionTypeOrBuilder extends com.google.protobuf.MessageLiteOrBuilder {

        // optional string message = 1;
        /**
         * <code>optional string message = 1;</code>
         *
         * @return if it has message
         */
        boolean hasMessage();

        /**
         * <code>optional string message = 1;</code>
         *
         * @return the message
         */
        java.lang.String getMessage();

        /**
         * <code>optional string message = 1;</code>
         *
         * @return the message byte string
         */
        com.google.protobuf.ByteString getMessageBytes();

        // optional string cause = 2;
        /**
         * <code>optional string cause = 2;</code>
         *
         * @return if it has cause
         */
        boolean hasCause();

        /**
         * <code>optional string cause = 2;</code>
         *
         * @return the cause
         */
        java.lang.String getCause();

        /**
         * <code>optional string cause = 2;</code>
         *
         * @return the cause byte string
         */
        com.google.protobuf.ByteString getCauseBytes();
    }

    /**
     * Protobuf type {@code datawave.webservice.query.exception.QueryExceptionType}
     */
    public static final class QueryExceptionType extends com.google.protobuf.GeneratedMessageLite implements QueryExceptionTypeOrBuilder {
        // Use QueryExceptionType.newBuilder() to construct.
        private QueryExceptionType(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);

        }

        private QueryExceptionType(boolean noInit) {}

        private static final QueryExceptionType defaultInstance;

        public static QueryExceptionType getDefaultInstance() {
            return defaultInstance;
        }

        public QueryExceptionType getDefaultInstanceForType() {
            return defaultInstance;
        }

        private QueryExceptionType(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            message_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            cause_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static com.google.protobuf.Parser<QueryExceptionType> PARSER = new com.google.protobuf.AbstractParser<QueryExceptionType>() {
            public QueryExceptionType parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new QueryExceptionType(input, extensionRegistry);
            }
        };

        @java.lang.Override
        public com.google.protobuf.Parser<QueryExceptionType> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // optional string message = 1;
        public static final int MESSAGE_FIELD_NUMBER = 1;
        private java.lang.Object message_;

        /**
         * <code>optional string message = 1;</code>
         *
         * @return if it has a message
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string message = 1;</code>
         *
         * @return the message
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string message = 1;</code>
         *
         * @return the message byte string
         */
        public com.google.protobuf.ByteString getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string cause = 2;
        public static final int CAUSE_FIELD_NUMBER = 2;
        private java.lang.Object cause_;

        /**
         * <code>optional string cause = 2;</code>
         *
         * @return if it has a cause
         */
        public boolean hasCause() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional string cause = 2;</code>
         *
         * @return the cause
         */
        public java.lang.String getCause() {
            java.lang.Object ref = cause_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    cause_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string cause = 2;</code>
         *
         * @return the cause byte string
         */
        public com.google.protobuf.ByteString getCauseBytes() {
            java.lang.Object ref = cause_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                cause_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            message_ = "";
            cause_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMessageBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getCauseBytes());
            }
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getMessageBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getCauseBytes());
            }
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(byte[] data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(byte[] data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseDelimitedFrom(java.io.InputStream input)
                        throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseDelimitedFrom(java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(com.google.protobuf.CodedInputStream input)
                        throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parseFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code datawave.webservice.query.exception.QueryExceptionType}
         */
        public static final class Builder extends
                        com.google.protobuf.GeneratedMessageLite.Builder<datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType,Builder>
                        implements datawave.webservice.query.exception.ExceptionMessages.QueryExceptionTypeOrBuilder {
            // Construct using datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {}

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                cause_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType getDefaultInstanceForType() {
                return datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType.getDefaultInstance();
            }

            public datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType build() {
                datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType buildPartial() {
                datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType result = new datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType(
                                this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.message_ = message_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.cause_ = cause_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType other) {
                if (other == datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType.getDefaultInstance())
                    return this;
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000001;
                    message_ = other.message_;

                }
                if (other.hasCause()) {
                    bitField0_ |= 0x00000002;
                    cause_ = other.cause_;

                }
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (datawave.webservice.query.exception.ExceptionMessages.QueryExceptionType) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // optional string message = 1;
            private java.lang.Object message_ = "";

            /**
             * <code>optional string message = 1;</code>
             *
             * @return if it has a message
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string message = 1;</code>
             *
             * @return the message
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string message = 1;</code>
             *
             * @return the message byte string
             */
            public com.google.protobuf.ByteString getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string message = 1;</code>
             *
             * @param value
             *            the message
             *
             * @return builder to set the message
             */
            public Builder setMessage(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                message_ = value;

                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             *
             * @return builder to clear the message
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000001);
                message_ = getDefaultInstance().getMessage();

                return this;
            }

            /**
             * <code>optional string message = 1;</code>
             *
             * @param value
             *            the value byte string
             *
             * @return builder to set the message to provided byte string
             */
            public Builder setMessageBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                message_ = value;

                return this;
            }

            // optional string cause = 2;
            private java.lang.Object cause_ = "";

            /**
             * <code>optional string cause = 2;</code>
             *
             * @return if it has a cause
             */
            public boolean hasCause() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional string cause = 2;</code>
             *
             * @return the cause
             */
            public java.lang.String getCause() {
                java.lang.Object ref = cause_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    cause_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string cause = 2;</code>
             *
             * @return the cause byte string
             */
            public com.google.protobuf.ByteString getCauseBytes() {
                java.lang.Object ref = cause_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    cause_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string cause = 2;</code>
             *
             * @param value
             *            the cause
             *
             * @return builder to set the cause to the provided value
             */
            public Builder setCause(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                cause_ = value;

                return this;
            }

            /**
             * <code>optional string cause = 2;</code>
             *
             * @return builder to clear the cause
             */
            public Builder clearCause() {
                bitField0_ = (bitField0_ & ~0x00000002);
                cause_ = getDefaultInstance().getCause();

                return this;
            }

            /**
             * <code>optional string cause = 2;</code>
             *
             * @param value
             *            new cause value as byte string
             *
             * @return builder to set cause to byte string
             */
            public Builder setCauseBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                cause_ = value;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:datawave.webservice.query.exception.QueryExceptionType)
        }

        static {
            defaultInstance = new QueryExceptionType(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:datawave.webservice.query.exception.QueryExceptionType)
    }

    static {}

    // @@protoc_insertion_point(outer_class_scope)
}
