package datawave.query.predicate;

import java.util.Map;

import javax.annotation.Nullable;

import org.apache.accumulo.core.data.Key;
import org.apache.accumulo.core.data.Range;
import org.apache.hadoop.io.Text;

/**
 * Decorating filter that limits the total number of entries aggregated into a single document, protecting the tserver against queries that pull problematically
 * large documents.
 * <p>
 * Once the limit is reached this filter rejects every subsequent entry, converts the first rejected key into a single synthetic
 * {@value #INCOMPLETE_DOCUMENT_FIELD} marker field via {@link #transform(Key)} so the truncated document is identifiable downstream, and returns a seek range
 * from {@link #getSeekRange(Key, Key, boolean)} that rolls over the remainder of the document, avoiding the IO of reading entries that would be discarded
 * anyway.
 * <p>
 * All other decisions are delegated to the wrapped filter, if one is present. The entry count and marker state are per-document, reset by
 * {@link #startNewDocument(Key)}, and deliberately not copied by {@link #clone()}.
 */
public class EventDataQueryEntryLimitFilter implements EventDataQueryFilter {

    /** Field name of the synthetic marker added to a document that was truncated by the entry limit */
    public static final String INCOMPLETE_DOCUMENT_FIELD = "INCOMPLETE_DOCUMENT";

    private static final String MARKER_PREFIX = INCOMPLETE_DOCUMENT_FIELD + '\u0000';

    // the maximum number of entries to aggregate for a single document (-1 disables the limit)
    private int maxEntries = -1;

    // the wrapped filter, may be null
    private EventDataQueryFilter delegate;

    // per-document state: the number of entries accepted so far, and whether the marker was emitted
    private int count;
    private boolean markerEmitted;

    public EventDataQueryEntryLimitFilter() {}

    /**
     * @param delegate
     *            the filter to decorate, may be null
     */
    public EventDataQueryEntryLimitFilter(EventDataQueryFilter delegate) {
        this.delegate = delegate;
    }

    /**
     * Copy constructor used by the {@link #clone()} method. Per-document state is deliberately not copied.
     *
     * @param other
     *            an instance of the {@link EventDataQueryEntryLimitFilter}
     */
    public EventDataQueryEntryLimitFilter(EventDataQueryEntryLimitFilter other) {
        this.maxEntries = other.maxEntries;
        this.delegate = other.delegate == null ? null : other.delegate.clone();
        this.count = 0;
        this.markerEmitted = false;
    }

    /**
     * Builder-style method used to set the maximum number of entries
     *
     * @param maxEntries
     *            the maximum number of entries to aggregate per document, or -1 to disable
     * @return the filter
     */
    public EventDataQueryEntryLimitFilter withMaxEntries(int maxEntries) {
        this.maxEntries = maxEntries;
        return this;
    }

    public int getMaxEntries() {
        return maxEntries;
    }

    @Override
    public void startNewDocument(Key document) {
        count = 0;
        markerEmitted = false;
        if (delegate != null) {
            delegate.startNewDocument(document);
        }
    }

    @Override
    public boolean keep(Key k) {
        if (limitReached()) {
            // the marker generated by this filter must always survive
            return isMarker(k);
        }
        return delegate == null || delegate.keep(k);
    }

    @Override
    public boolean apply(@Nullable Map.Entry<Key,String> entry) {
        return apply(entry, true);
    }

    @Override
    public boolean peek(@Nullable Map.Entry<Key,String> entry) {
        return apply(entry, false);
    }

    /**
     * @param entry
     *            the entry
     * @param update
     *            flag that indicates if the {@link #count} may be incremented
     * @return true if the entry should be aggregated
     */
    private boolean apply(Map.Entry<Key,String> entry, boolean update) {
        if (entry == null) {
            return false;
        }
        if (limitReached()) {
            // the marker generated by this filter must always survive
            return isMarker(entry.getKey());
        }
        boolean result = delegate == null || (update ? delegate.apply(entry) : delegate.peek(entry));
        if (result && update) {
            count++;
        }
        return result;
    }

    private boolean limitReached() {
        return maxEntries > -1 && count >= maxEntries;
    }

    private boolean isMarker(Key key) {
        return key.getColumnQualifier().toString().startsWith(MARKER_PREFIX);
    }

    /**
     * Once the limit is reached, convert the first rejected key into the incomplete-document marker so the truncation is visible in the returned document;
     * before that, defer to the wrapped filter.
     *
     * @param toLimit
     *            the key that was rejected
     * @return the marker key exactly once per document after the limit is reached, otherwise the wrapped filter's transformation
     */
    @Override
    public Key transform(Key toLimit) {
        if (limitReached()) {
            if (!markerEmitted) {
                markerEmitted = true;
                // carry the rejected key's visibility and timestamp so the marker survives downstream visibility and time filtering
                return new Key(toLimit.getRow(), toLimit.getColumnFamily(), new Text(MARKER_PREFIX + "true"), toLimit.getColumnVisibility(),
                                toLimit.getTimestamp());
            }
            return null;
        }
        return delegate == null ? null : delegate.transform(toLimit);
    }

    /**
     * Once the limit is reached, skip the remainder of the document entirely: the entries would be rejected anyway, so reading them is wasted IO.
     *
     * @param current
     *            the current key at the top of the source iterator
     * @param endKey
     *            the current range endKey
     * @param endKeyInclusive
     *            the endKeyInclusive flag from the current range
     * @return a rollover range past the current document once the limit is reached, otherwise the wrapped filter's seek range
     */
    @Override
    public Range getSeekRange(Key current, Key endKey, boolean endKeyInclusive) {
        if (limitReached()) {
            if (current == null) {
                return null;
            }
            Text columnFamily = new Text(current.getColumnFamilyData().toString() + '\u0000');
            Key start = new Key(current.getRow(), columnFamily);
            if (endKey != null && start.compareTo(endKey) >= 0) {
                // the range does not extend past this document (the common single-document range): an empty range
                // cannot be represented, so decline to seek and let the remaining entries drain as cheap rejections
                return null;
            }
            return new Range(start, false, endKey, endKeyInclusive);
        }
        return delegate == null ? null : delegate.getSeekRange(current, endKey, endKeyInclusive);
    }

    @Override
    public int getMaxNextCount() {
        // not consulted on the event aggregation path, and delegates may throw when asked (see EventDataQueryFieldFilter), so do not forward
        return -1;
    }

    @Override
    public EventDataQueryFilter clone() {
        return new EventDataQueryEntryLimitFilter(this);
    }
}
