package datawave.query.planner;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.commons.lang3.tuple.Pair;
import org.apache.log4j.Logger;

import datawave.core.common.logging.ThreadConfigurableLogger;
import datawave.core.query.configuration.QueryData;
import datawave.query.CloseableIterable;
import datawave.query.config.ShardQueryConfiguration;
import datawave.query.exceptions.DatawaveFatalQueryException;
import datawave.query.exceptions.DatawaveQueryException;

/**
 * Implementation of {@link CloseableIterable} intended to be used by {@link DatePartitionedQueryPlanner}. This iterable
 */
public class DatePartitionedQueryIterable implements CloseableIterable<QueryData> {

    private static final Logger log = ThreadConfigurableLogger.getLogger(DatePartitionedQueryIterable.class);
    private final List<SubPlanCallable> subPlanGenerators;
    private final ShardQueryConfiguration shardQueryConfig;
    private final String initialPlan;
    private Iter iterator;
    private final List<PlanListener> listeners = new ArrayList<>();

    public DatePartitionedQueryIterable(List<SubPlanCallable> subPlansGenerators, ShardQueryConfiguration shardQueryConfig, PlanListener listener)
                    throws DatawaveQueryException, DatawaveFatalQueryException {
        this.subPlanGenerators = subPlansGenerators;
        this.shardQueryConfig = shardQueryConfig;
        this.initialPlan = shardQueryConfig.getQueryString();
        this.listeners.add(listener);
        this.iterator = new Iter();
    }

    public void addListener(PlanListener listener) {
        this.listeners.add(listener);
    }

    /**
     * Closes and clears each iterable in this {@link DatePartitionedQueryIterable}.
     *
     * @throws IOException
     *             if an error occurred when closing an iterable
     */
    @Override
    public void close() throws IOException {
        if (this.iterator != null) {
            this.iterator.close();
        }
    }

    /**
     * Returns an iterator that will iterate over the {@link QueryData} returned by each iterable in this {@link DatePartitionedQueryIterable}.
     *
     * @return the iterator
     */
    @Override
    public Iterator<QueryData> iterator() {
        return this.iterator;
    }

    /**
     * Get the planned script
     *
     * @return the planned script
     */
    public String getPlannedScript() {
        return this.iterator.getPlannedScript();
    }

    /**
     * Iterator implementation that provides the ability to iterate over each {@link QueryData} of the iterables generated by the {@link SubPlanCallable}.
     */
    private class Iter implements Iterator<QueryData> {

        private final SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

        // the plans
        private final Set<String> plans = new LinkedHashSet<>();

        // the exceptions
        private final List<DatawaveQueryException> exceptions = new ArrayList<>();

        // Iterator that traverses over the plans
        private final Iterator<SubPlanCallable> callableIterator = subPlanGenerators.iterator();

        // The closable iterable
        private CloseableIterable<QueryData> currentSubIterable = null;

        // The current sub iterator.
        private Iterator<QueryData> currentSubIterator = null;

        // Construct the iterator which will in turn find an available query data stream
        public Iter() throws DatawaveQueryException, DatawaveFatalQueryException {
            // Let's make sure we have at least one valid query data stream
            seekToNextAvailableQueryData();

            // if every plan failed, then pass an exception up
            evaluateFailures();
        }

        public void close() throws IOException {
            if (currentSubIterable != null) {
                this.currentSubIterable.close();
                this.currentSubIterable = null;
            }
        }

        @Override
        public boolean hasNext() {
            seekToNextAvailableQueryData();
            return currentSubIterator != null && currentSubIterator.hasNext();
        }

        @Override
        public QueryData next() {
            return currentSubIterator.next();
        }

        /**
         * Seek to the next sub-iterator that has a {@link QueryData} remaining in it.
         */
        private void seekToNextAvailableQueryData() {
            // If the current sub iterator is null, attempt to get the next available iterator, or return early if there are no more iterators.
            while ((currentSubIterator == null || !currentSubIterator.hasNext()) && callableIterator.hasNext()) {
                populateNextIterable();
            }
        }

        private void populateNextIterable() {
            if (callableIterator.hasNext()) {
                SubPlanCallable callable = callableIterator.next();
                Map.Entry<Pair<Date,Date>,Set<String>> dateRange = callable.getDateRange();
                String subBeginDate = dateFormat.format(dateRange.getKey().getLeft());
                String subEndDate = dateFormat.format(dateRange.getKey().getRight());

                try {
                    currentSubIterable = callable.call();
                    // may be null if only generating a plan
                    if (currentSubIterable != null) {
                        currentSubIterator = currentSubIterable.iterator();
                    }

                    if (log.isDebugEnabled()) {
                        log.debug("Query string for config of sub-plan against date range (" + subBeginDate + "-" + subEndDate + ") with unindexed fields "
                                        + dateRange.getValue() + ": " + callable.getSubPlanConfig().getQueryString());
                    }
                } catch (Exception e) {
                    String msg = "Exception occurred when processing sub-plan against date range (" + subBeginDate + "-" + subEndDate + ")";
                    log.warn(msg, e);
                    exceptions.add(new DatawaveQueryException(msg, e.getCause()));
                } finally {
                    ShardQueryConfiguration subPlanConfig = callable.getSubPlanConfig();

                    // append the new timers for logging at the end
                    shardQueryConfig.appendTimers(subPlanConfig.getTimers());

                    // Add to the set of plans
                    plans.add(subPlanConfig.getQueryString());

                    // notify the listeners that the plan has changed
                    String plan = getPlannedScript();
                    for (PlanListener listener : listeners) {
                        listener.planUpdated(plan);
                    }
                }
            }
        }

        /**
         * Get the planned script to represent a concatenation of the planned scripts from all sub-plans. If we have not gathered all of the subplans, then
         * simply return the original plan
         */
        public String getPlannedScript() {
            String plannedScript;
            // if no plans yet, then our plan is the initial plan
            if (plans.isEmpty()) {
                plannedScript = initialPlan;
            }
            // if only one plan, then use that
            else if (plans.size() == 1) {
                plannedScript = plans.iterator().next();
            }
            // else concatenate the plans
            else {
                StringBuilder sb = new StringBuilder();
                int i = 0;
                for (String plan : plans) {
                    if (sb.length() > 0) {
                        sb.append(" || ");
                    }
                    sb.append("((plan = ").append(++i).append(") && (").append(plan).append("))");
                }
                plannedScript = sb.toString();
            }
            return plannedScript;
        }

        /**
         * Determine if we are failing the query entirely. This can happen if every subplan failed to execute.
         *
         * @throws DatawaveQueryException
         * @throws DatawaveFatalQueryException
         */
        private void evaluateFailures() throws DatawaveQueryException, DatawaveFatalQueryException {
            if (exceptions.size() == subPlanGenerators.size()) {
                if (exceptions.size() == 1) {
                    Throwable e = unwrapException(exceptions.get(0));
                    if (e instanceof RuntimeException) {
                        throw (RuntimeException) e;
                    } else {
                        throw (DatawaveQueryException) e;
                    }
                } else {
                    DatawaveFatalQueryException e = new DatawaveFatalQueryException("Query failed creation for " + shardQueryConfig.getQuery().getId());
                    for (Throwable reason : exceptions) {
                        e.addSuppressed(reason);
                    }
                    throw e;
                }
            }
        }

        /**
         * In the case were we have only 1 exception, we want to throw the underlying exception to be backward compatible which will be the lowest level
         * DatawaveQueryException or first DatawaveFatalQueryException
         *
         * @param e
         *            The exception being unwrapped
         * @return DatawaveQueryException or DatawaveFatalQueryException
         */
        private Throwable unwrapException(DatawaveQueryException e) {
            Throwable toThrow = e;
            Throwable test = e;
            while (test.getCause() != null && test.getCause() != test) {
                test = test.getCause();
                if (test instanceof DatawaveFatalQueryException) {
                    return test;
                }
                if (test instanceof DatawaveQueryException) {
                    toThrow = test;
                }
            }
            return toThrow;
        }

    }

}
