####################################
# Core Helm Template Configuration #
####################################

apiVersion: v1
kind: Service

######################################
# Basic Metadata for this Deployment #
######################################

metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  name: "{{ .Chart.Name }}-{{ .Values.dictionaryService.meta.name }}"
  labels:
    application: "{{ .Chart.Name }}-{{ .Values.dictionaryService.meta.name }}"

##################################
# Complete Service Specification #
##################################

spec:

  ###############################
  # Pod Selection Configuration #
  ###############################

  selector:
    application: "{{ .Chart.Name }}-{{ .Values.dictionaryDeployment.meta.name }}"

  ##############################
  # Service Port Configuration #
  ##############################

  ports:

    - name: http
      port: {{ .Values.dictionaryService.ports.http }}
      targetPort: 8080

    - name: https
      port: {{ .Values.dictionaryService.ports.https }}
      targetPort: 8443