package datawave.ingest.metadata;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import org.apache.hadoop.io.Text;

import com.google.common.base.Objects;

/**
 * Given a column family (COLF), this class tracks the related metadata's earliest entry per datatype.
 * <p>
 * It maintains a mapping between a unique key (constructed from the field name and datatype output name) and a {@link Components} instance, which holds the
 * metadata field name, its datatype, and the earliest event date encountered.
 * </p>
 */
public class MetadataWithEarliestDate {

    public static final String IGNORED_NORMALIZER_CLASS = null;

    // The column family (COLF) this instance is tracking
    private final Text columnFamily;

    /**
     * Stores the earliest date for a field and datatype combination.
     * <p>
     * The key is generated by concatenating the field name and the datatype output name. The value is a {@link Components} instance holding the metadata
     * details.
     * </p>
     */
    private Map<String,Components> earliestDates = new HashMap<>();

    /**
     * Creates an instance for tracking earliest metadata entries for a specific column family.
     *
     * @param columnFamily
     *            the column family (COLF) to track
     */
    public MetadataWithEarliestDate(Text columnFamily) {
        this.columnFamily = columnFamily;
    }

    /**
     * Creates a unique key by concatenating the field name and the datatype output name. This key is used to store and retrieve the corresponding
     * {@link Components} in the map.
     *
     * @param fieldName
     *            the field name of the metadata entry
     * @param dataTypeOutputName
     *            the datatype output name of the metadata entry
     * @return a unique string key combining the field name and datatype name
     */
    private static String createKey(String fieldName, String dataTypeOutputName) {
        // Concatenation guarantees a unique identifier given a unique combination of field and datatype
        return fieldName + dataTypeOutputName;
    }

    /**
     * Creates a new entry or updates an existing entry in the {@code earliestDates} map.
     * <p>
     * If no entry exists for the given fieldName and dataTypeOutputName, a new {@link Components} instance is created with the provided eventDate. Otherwise,
     * if the provided eventDate is earlier than the currently stored date, the existing entry is updated with the new date.
     * </p>
     *
     * @param fieldName
     *            the field name of the associated metadata entry
     * @param dataTypeOutputName
     *            the datatype output name of the associated metadata entry
     * @param eventDate
     *            the event date to be considered for updating the earliest date
     */
    public void createOrUpdate(String fieldName, String dataTypeOutputName, long eventDate) {
        // Create a unique identifier based on field name and datatype name
        String identifier = createKey(fieldName, dataTypeOutputName);
        Components value = earliestDates.get(identifier);
        if (value == null) {
            // No existing entry: add a new Components instance to the map
            earliestDates.put(identifier, new Components(fieldName, dataTypeOutputName, eventDate));
        } else if (eventDate < value.getEarliestDate()) {
            // Existing entry found but the new date is earlier: update the stored earliest date
            value.setEarliestDate(eventDate);
        }
    }

    /**
     * Retrieves all the earliest metadata entries stored for the tracked column family.
     *
     * @return a collection of {@link Components} representing the earliest entries for each datatype
     */
    public Collection<Components> entries() {
        return earliestDates.values();
    }

    /**
     * Clears all stored earliest metadata entries.
     */
    public void clear() {
        earliestDates.clear();
    }

    /**
     * Returns the column family (COLF) that this instance is tracking.
     *
     * @return the tracked column family as a {@link Text} object
     */
    public Text getColumnFamily() {
        return columnFamily;
    }

    /**
     * A container class that holds components related to the earliest date information for a specific field and datatype.
     */
    static class Components {
        // The name of the field associated with this metadata entry
        private final String fieldName;
        // The output name of the datatype associated with this metadata entry
        private final String dataTypeOutputName;
        // The earliest event date for the metadata entry
        private long earliestDate;

        /**
         * Constructs a new Components instance.
         *
         * @param fieldName
         *            the field name of the metadata entry
         * @param dataTypeOutputName
         *            the datatype output name of the metadata entry
         * @param eventDate
         *            the event date considered as the earliest date
         */
        public Components(String fieldName, String dataTypeOutputName, long eventDate) {
            this.fieldName = fieldName;
            this.dataTypeOutputName = dataTypeOutputName;
            this.earliestDate = eventDate;
        }

        /**
         * Gets the field name associated with this metadata component.
         *
         * @return the metadata field name
         */
        public String getFieldName() {
            return fieldName;
        }

        /**
         * Gets the datatype output name associated with this metadata component.
         *
         * @return the datatype output name
         */
        public String getDataType() {
            return dataTypeOutputName;
        }

        /**
         * Gets the earliest event date for this metadata entry.
         *
         * @return the earliest date as a long value
         */
        public long getEarliestDate() {
            return earliestDate;
        }

        /**
         * Updates the earliest event date for this metadata entry.
         *
         * @param dateToUse
         *            the new earliest date to set
         */
        public void setEarliestDate(long dateToUse) {
            this.earliestDate = dateToUse;
        }

        /**
         * Computes the hash code for this Components instance.
         * <p>
         * The hash code is based on the concatenation of fieldName and dataTypeOutputName as well as the earliest date.
         * </p>
         *
         * @return the hash code as an integer
         */
        @Override
        public int hashCode() {
            int hashcode = (fieldName + dataTypeOutputName).hashCode();
            hashcode += (int) (earliestDate ^ (earliestDate >>> 32));
            return hashcode;
        }

        /**
         * Determines whether this Components instance is equal to another object.
         * <p>
         * Two Components instances are considered equal if they have the same field name, datatype output name, and earliest date.
         * </p>
         *
         * @param o
         *            the object to compare with this instance
         * @return {@code true} if the objects are equal; {@code false} otherwise
         */
        @Override
        public boolean equals(Object o) {
            if (!(o instanceof Components)) {
                return false;
            }
            Components other = (Components) o;
            return Objects.equal(dataTypeOutputName, other.dataTypeOutputName) && Objects.equal(fieldName, other.fieldName)
                            && this.earliestDate == other.earliestDate;
        }
    }
}
