package datawave.query.transformer;

import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import java.util.Set;
import java.util.stream.Collectors;

import org.apache.accumulo.core.data.Key;
import org.apache.accumulo.core.data.Value;
import org.apache.accumulo.core.security.Authorizations;

import datawave.core.query.logic.BaseQueryLogicTransformer;
import datawave.marking.MarkingFunctions;
import datawave.microservice.query.Query;
import datawave.query.tables.keyword.KeywordQueryState;
import datawave.query.tables.keyword.transform.TagCloudInputTransformer;
import datawave.util.keyword.TagCloud;
import datawave.util.keyword.TagCloudEntry;
import datawave.util.keyword.TagCloudPartition;
import datawave.webservice.query.result.event.ResponseObjectFactory;
import datawave.webservice.result.BaseQueryResponse;
import datawave.webservice.result.keyword.TagCloudBase;
import datawave.webservice.result.keyword.TagCloudEntryBase;
import datawave.webservice.result.keyword.TagCloudResponseBase;

/** Transforms the Key/Values returned by the KeywordExtractionIterator into KeywordResults and then Tag Clouds Responses */
@SuppressWarnings("rawtypes")
public class TagCloudTransformer extends BaseQueryLogicTransformer<Entry<Key,Value>,TagCloudPartition> {
    public static final ResponseVersion DEFAULT_VERSION = ResponseVersion.V1;

    private final ResponseVersion responseVersion;
    protected final Authorizations auths;
    protected final ResponseObjectFactory responseObjectFactory;
    protected final KeywordQueryState state;
    private final Set<TagCloudInputTransformer<?>> transformers;

    public enum ResponseVersion {
        V1, V2
    }

    // TODO-crwill9 pass in state data, not the state object so this is more reusable
    public TagCloudTransformer(String responseVersion, Query query, KeywordQueryState state, MarkingFunctions markingFunctions,
                    ResponseObjectFactory responseObjectFactory, Set<TagCloudInputTransformer<?>> transformers) {
        super(markingFunctions);
        this.responseVersion = getResponseVersion(responseVersion);
        this.auths = new Authorizations(query.getQueryAuthorizations().split(","));
        this.responseObjectFactory = responseObjectFactory;
        this.state = state;
        this.transformers = transformers;
    }

    private ResponseVersion getResponseVersion(String responseVersion) {
        if (responseVersion == null) {
            return DEFAULT_VERSION;
        }

        if (responseVersion.equals("1") || responseVersion.equals("v1") || responseVersion.equals("V1")) {
            return ResponseVersion.V1;
        } else if (responseVersion.equals("2") || responseVersion.equals("v2") || responseVersion.equals("V2")) {
            return ResponseVersion.V2;
        }

        return DEFAULT_VERSION;
    }

    /**
     * Transform results from the KeywordExtractingIterator into Events that will then be used for generating the response in createResponse()
     *
     * @param entry
     *            a
     * @return KeywordResults object containing the transformed entry.
     */
    @Override
    public TagCloudPartition transform(Entry<Key,Value> entry) {
        // each contains the serialized keywords for individual documents.
        if (entry.getKey() == null && entry.getValue() == null) {
            return null;
        }

        if (null == entry.getKey() || null == entry.getValue()) {
            throw new IllegalArgumentException("Null key or value. Key:" + entry.getKey() + ", Value: " + entry.getValue());
        }

        for (TagCloudInputTransformer<?> transformer : transformers) {
            if (transformer.canDecode(entry)) {
                return transformer.decode(entry);
            }
        }

        throw new IllegalArgumentException("Unable to parse keyword extraction results " + entry.getKey());
    }

    /**
     * Transform a list of results generated by the transform method into a query response. The nature of the response is based on the query configuration
     *
     * @param resultList
     *            the results to add to the response that were created by the transform method
     * @return a tag cloud response
     */
    @Override
    public BaseQueryResponse createResponse(List<Object> resultList) {
        final List<TagCloudPartition> inputList = resultList.stream().map(o -> (TagCloudPartition) o).collect(Collectors.toList());
        List<TagCloud> tagClouds = new ArrayList<>();
        tagClouds.addAll(buildTagCloud(state.isGenerateCloud(), inputList));

        return generateTagCloudResponse(tagClouds);
    }

    /**
     * Transform a list of partitions into a query response containing tag clouds either merged into a single tag cloud, or into one tag cloud per partition
     *
     * @param merged
     *            if the tag clouds should be merged
     * @param resultList
     *            the partitions to add to the tag cloud(s)
     * @return a non-null list of tag clouds
     */
    private List<TagCloud> buildTagCloud(boolean merged, List<TagCloudPartition> resultList) {
        List<TagCloud> results = new ArrayList<>();
        TagCloud.Builder builder = getTagCloudBuilder().withComparator(TagCloudEntry.ORDER_BY_FREQUENCY);
        for (TagCloudPartition result : resultList) {
            builder.addInput(result);
            if (!merged) {
                results.addAll(builder.build());
                builder = getTagCloudBuilder().withComparator(TagCloudEntry.ORDER_BY_FREQUENCY);
            }
        }

        if (merged) {
            results.addAll(builder.build());
        }

        return results;
    }

    /**
     * Get a configured tag cloud builder
     *
     * @return a configured tag cloud builder.
     */
    protected TagCloud.Builder getTagCloudBuilder() {
        final TagCloud.Builder builder = new TagCloud.Builder().withTagCloudUtilities(state.getTagCloudUtils());
        if (state.getMaxCloudTags() > 0) {
            builder.withMaxTags(state.getMaxCloudTags());
        }
        return builder;
    }

    /**
     * Transform a list of one or more wordCloudResults into the necessary tag-cloud response type
     *
     * @param tagCloudResultsList
     *            the results to convert, each representing the results for a single document.
     * @return a tag cloud response that includes one or more tag clouds.
     */
    @SuppressWarnings("unchecked")
    protected TagCloudResponseBase generateTagCloudResponse(List<TagCloud> tagCloudResultsList) {
        TagCloudResponseBase response = responseObjectFactory.getTagCloudQueryResponse();
        List<TagCloudBase> tagClouds = new ArrayList<>();
        for (TagCloud tagCloudResult : tagCloudResultsList) {
            TagCloudBase tagCloud = responseObjectFactory.getTagCloud();
            configureTagCloud(tagCloud, tagCloudResult);
            tagClouds.add(tagCloud);
        }
        response.setTagClouds(tagClouds);
        return response;
    }

    public ResponseVersion getResponseVersion() {
        return responseVersion;
    }

    private void configureV1TagCloud(TagCloudBase base, TagCloud tagCloud) {
        if (tagCloud.getMetadata() != null) {
            String language = tagCloud.getMetadata().get("language");
            if (language != null) {
                base.setLanguage(language);
            } else {
                String type = tagCloud.getMetadata().get("type");
                if (type != null) {
                    base.setLanguage(type);
                }
            }
        }
        if (!tagCloud.getVisibility().isEmpty()) {
            base.setMarkings(tagCloud.getVisibility());
        }
        base.setTags(generateTagCloudEntries(tagCloud));
    }

    private void configureV2TagCloud(TagCloudBase base, TagCloud tagCloud) {
        if (tagCloud.getMetadata() != null && !tagCloud.getMetadata().isEmpty()) {
            base.setMetadata(tagCloud.getMetadata());
        }
        if (!tagCloud.getVisibility().isEmpty()) {
            base.setMarkings(tagCloud.getVisibility());
        }
        base.setTags(generateTagCloudEntries(tagCloud));
    }

    private void configureTagCloud(TagCloudBase base, TagCloud tagCloud) {
        if (responseVersion == ResponseVersion.V1) {
            configureV1TagCloud(base, tagCloud);
        } else if (responseVersion == ResponseVersion.V2) {
            configureV2TagCloud(base, tagCloud);
        } else {
            throw new UnsupportedOperationException("cannot configure response for " + responseVersion);
        }
    }

    /**
     * Transform a single wordCloudResult into the necessary tag-cloud response type
     *
     * @param wordCloudResults
     *            the results to convert, each representing the results for a single document.
     * @return a list of tag cloud entries to be added to a tag cloud.
     */
    @SuppressWarnings("unchecked")
    protected List<TagCloudEntryBase> generateTagCloudEntries(TagCloud wordCloudResults) {
        List<TagCloudEntryBase> tagCloudEntries = new ArrayList<>();
        for (TagCloudEntry entry : wordCloudResults.getResults()) {
            TagCloudEntryBase tagCloudEntry = responseObjectFactory.getTagCloudEntry();
            tagCloudEntry.setScore(entry.getScore());
            tagCloudEntry.setFrequency(entry.getFrequency());
            tagCloudEntry.setTerm(entry.getKeyword());
            tagCloudEntry.setSources(entry.getSources());
            tagCloudEntries.add(tagCloudEntry);
        }
        return tagCloudEntries;
    }
}
