// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EdgeMetadata.proto

package datawave.metadata.protobuf;

public final class EdgeMetadata {
    private EdgeMetadata() {}
    
    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}
    
    public interface MetadataValueOrBuilder extends
                    // @@protoc_insertion_point(interface_extends:datawave.metadata.protobuf.MetadataValue)
                    com.google.protobuf.MessageOrBuilder {
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        java.util.List<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata> getMetadataList();
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata getMetadata(int index);
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        int getMetadataCount();
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        java.util.List<? extends datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder> getMetadataOrBuilderList();
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder getMetadataOrBuilder(int index);
    }
    
    /**
     * Protobuf type {@code datawave.metadata.protobuf.MetadataValue}
     *
     * <pre>
     * moved this out because no need for Metadata values to appear in the standard edge table.
     * this would be fixed if packed=true worked on strings, but meh
     * </pre>
     */
    public static final class MetadataValue extends com.google.protobuf.GeneratedMessage implements
                    // @@protoc_insertion_point(message_implements:datawave.metadata.protobuf.MetadataValue)
                    MetadataValueOrBuilder {
        // Use MetadataValue.newBuilder() to construct.
        private MetadataValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        
        private MetadataValue(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        
        private static final MetadataValue defaultInstance;
        
        public static MetadataValue getDefaultInstance() {
            return defaultInstance;
        }
        
        public MetadataValue getDefaultInstanceForType() {
            return defaultInstance;
        }
        
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }
        
        private MetadataValue(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                metadata_ = new java.util.ArrayList<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            metadata_.add(input.readMessage(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    metadata_ = java.util.Collections.unmodifiableList(metadata_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.class,
                                            datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Builder.class);
        }
        
        public static com.google.protobuf.Parser<MetadataValue> PARSER = new com.google.protobuf.AbstractParser<MetadataValue>() {
            public MetadataValue parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new MetadataValue(input, extensionRegistry);
            }
        };
        
        @java.lang.Override
        public com.google.protobuf.Parser<MetadataValue> getParserForType() {
            return PARSER;
        }
        
        public interface MetadataOrBuilder extends
                        // @@protoc_insertion_point(interface_extends:datawave.metadata.protobuf.MetadataValue.Metadata)
                        com.google.protobuf.MessageOrBuilder {
            
            /**
             * <code>required string source = 1;</code>
             */
            boolean hasSource();
            
            /**
             * <code>required string source = 1;</code>
             */
            java.lang.String getSource();
            
            /**
             * <code>required string source = 1;</code>
             */
            com.google.protobuf.ByteString getSourceBytes();
            
            /**
             * <code>required string sink = 2;</code>
             */
            boolean hasSink();
            
            /**
             * <code>required string sink = 2;</code>
             */
            java.lang.String getSink();
            
            /**
             * <code>required string sink = 2;</code>
             */
            com.google.protobuf.ByteString getSinkBytes();
            
            /**
             * <code>optional string enrichment = 3;</code>
             */
            boolean hasEnrichment();
            
            /**
             * <code>optional string enrichment = 3;</code>
             */
            java.lang.String getEnrichment();
            
            /**
             * <code>optional string enrichment = 3;</code>
             */
            com.google.protobuf.ByteString getEnrichmentBytes();
            
            /**
             * <code>optional string enrichmentIndex = 4;</code>
             */
            boolean hasEnrichmentIndex();
            
            /**
             * <code>optional string enrichmentIndex = 4;</code>
             */
            java.lang.String getEnrichmentIndex();
            
            /**
             * <code>optional string enrichmentIndex = 4;</code>
             */
            com.google.protobuf.ByteString getEnrichmentIndexBytes();
            
            /**
             * <code>optional string date = 5;</code>
             */
            boolean hasDate();
            
            /**
             * <code>optional string date = 5;</code>
             */
            java.lang.String getDate();
            
            /**
             * <code>optional string date = 5;</code>
             */
            com.google.protobuf.ByteString getDateBytes();
            
            /**
             * <code>optional string jexlPrecondition = 6;</code>
             */
            boolean hasJexlPrecondition();
            
            /**
             * <code>optional string jexlPrecondition = 6;</code>
             */
            java.lang.String getJexlPrecondition();
            
            /**
             * <code>optional string jexlPrecondition = 6;</code>
             */
            com.google.protobuf.ByteString getJexlPreconditionBytes();
        }
        
        /**
         * Protobuf type {@code datawave.metadata.protobuf.MetadataValue.Metadata}
         */
        public static final class Metadata extends com.google.protobuf.GeneratedMessage implements
                        // @@protoc_insertion_point(message_implements:datawave.metadata.protobuf.MetadataValue.Metadata)
                        MetadataOrBuilder {
            // Use Metadata.newBuilder() to construct.
            private Metadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
                super(builder);
                this.unknownFields = builder.getUnknownFields();
            }
            
            private Metadata(boolean noInit) {
                this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
            }
            
            private static final Metadata defaultInstance;
            
            public static Metadata getDefaultInstance() {
                return defaultInstance;
            }
            
            public Metadata getDefaultInstanceForType() {
                return defaultInstance;
            }
            
            private final com.google.protobuf.UnknownFieldSet unknownFields;
            
            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
                return this.unknownFields;
            }
            
            private Metadata(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                initFields();
                int mutable_bitField0_ = 0;
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            default: {
                                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                            case 10: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000001;
                                source_ = bs;
                                break;
                            }
                            case 18: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000002;
                                sink_ = bs;
                                break;
                            }
                            case 26: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000004;
                                enrichment_ = bs;
                                break;
                            }
                            case 34: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000008;
                                enrichmentIndex_ = bs;
                                break;
                            }
                            case 42: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000010;
                                date_ = bs;
                                break;
                            }
                            case 50: {
                                com.google.protobuf.ByteString bs = input.readBytes();
                                bitField0_ |= 0x00000020;
                                jexlPrecondition_ = bs;
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }
            
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_fieldAccessorTable
                                .ensureFieldAccessorsInitialized(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.class,
                                                datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder.class);
            }
            
            public static com.google.protobuf.Parser<Metadata> PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
                public Metadata parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Metadata(input, extensionRegistry);
                }
            };
            
            @java.lang.Override
            public com.google.protobuf.Parser<Metadata> getParserForType() {
                return PARSER;
            }
            
            private int bitField0_;
            public static final int SOURCE_FIELD_NUMBER = 1;
            private java.lang.Object source_;
            
            /**
             * <code>required string source = 1;</code>
             */
            public boolean hasSource() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            
            /**
             * <code>required string source = 1;</code>
             */
            public java.lang.String getSource() {
                java.lang.Object ref = source_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        source_ = s;
                    }
                    return s;
                }
            }
            
            /**
             * <code>required string source = 1;</code>
             */
            public com.google.protobuf.ByteString getSourceBytes() {
                java.lang.Object ref = source_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    source_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            
            public static final int SINK_FIELD_NUMBER = 2;
            private java.lang.Object sink_;
            
            /**
             * <code>required string sink = 2;</code>
             */
            public boolean hasSink() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            
            /**
             * <code>required string sink = 2;</code>
             */
            public java.lang.String getSink() {
                java.lang.Object ref = sink_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        sink_ = s;
                    }
                    return s;
                }
            }
            
            /**
             * <code>required string sink = 2;</code>
             */
            public com.google.protobuf.ByteString getSinkBytes() {
                java.lang.Object ref = sink_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    sink_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            
            public static final int ENRICHMENT_FIELD_NUMBER = 3;
            private java.lang.Object enrichment_;
            
            /**
             * <code>optional string enrichment = 3;</code>
             */
            public boolean hasEnrichment() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            
            /**
             * <code>optional string enrichment = 3;</code>
             */
            public java.lang.String getEnrichment() {
                java.lang.Object ref = enrichment_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        enrichment_ = s;
                    }
                    return s;
                }
            }
            
            /**
             * <code>optional string enrichment = 3;</code>
             */
            public com.google.protobuf.ByteString getEnrichmentBytes() {
                java.lang.Object ref = enrichment_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    enrichment_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            
            public static final int ENRICHMENTINDEX_FIELD_NUMBER = 4;
            private java.lang.Object enrichmentIndex_;
            
            /**
             * <code>optional string enrichmentIndex = 4;</code>
             */
            public boolean hasEnrichmentIndex() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            
            /**
             * <code>optional string enrichmentIndex = 4;</code>
             */
            public java.lang.String getEnrichmentIndex() {
                java.lang.Object ref = enrichmentIndex_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        enrichmentIndex_ = s;
                    }
                    return s;
                }
            }
            
            /**
             * <code>optional string enrichmentIndex = 4;</code>
             */
            public com.google.protobuf.ByteString getEnrichmentIndexBytes() {
                java.lang.Object ref = enrichmentIndex_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    enrichmentIndex_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            
            public static final int DATE_FIELD_NUMBER = 5;
            private java.lang.Object date_;
            
            /**
             * <code>optional string date = 5;</code>
             */
            public boolean hasDate() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }
            
            /**
             * <code>optional string date = 5;</code>
             */
            public java.lang.String getDate() {
                java.lang.Object ref = date_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        date_ = s;
                    }
                    return s;
                }
            }
            
            /**
             * <code>optional string date = 5;</code>
             */
            public com.google.protobuf.ByteString getDateBytes() {
                java.lang.Object ref = date_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    date_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            
            public static final int JEXLPRECONDITION_FIELD_NUMBER = 6;
            private java.lang.Object jexlPrecondition_;
            
            /**
             * <code>optional string jexlPrecondition = 6;</code>
             */
            public boolean hasJexlPrecondition() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }
            
            /**
             * <code>optional string jexlPrecondition = 6;</code>
             */
            public java.lang.String getJexlPrecondition() {
                java.lang.Object ref = jexlPrecondition_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        jexlPrecondition_ = s;
                    }
                    return s;
                }
            }
            
            /**
             * <code>optional string jexlPrecondition = 6;</code>
             */
            public com.google.protobuf.ByteString getJexlPreconditionBytes() {
                java.lang.Object ref = jexlPrecondition_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                    jexlPrecondition_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            
            private void initFields() {
                source_ = "";
                sink_ = "";
                enrichment_ = "";
                enrichmentIndex_ = "";
                date_ = "";
                jexlPrecondition_ = "";
            }
            
            private byte memoizedIsInitialized = -1;
            
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1)
                    return true;
                if (isInitialized == 0)
                    return false;
                
                if (!hasSource()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                if (!hasSink()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
                memoizedIsInitialized = 1;
                return true;
            }
            
            public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeBytes(1, getSourceBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeBytes(2, getSinkBytes());
                }
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    output.writeBytes(3, getEnrichmentBytes());
                }
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    output.writeBytes(4, getEnrichmentIndexBytes());
                }
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    output.writeBytes(5, getDateBytes());
                }
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                    output.writeBytes(6, getJexlPreconditionBytes());
                }
                getUnknownFields().writeTo(output);
            }
            
            private int memoizedSerializedSize = -1;
            
            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1)
                    return size;
                
                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getSourceBytes());
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getSinkBytes());
                }
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getEnrichmentBytes());
                }
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(4, getEnrichmentIndexBytes());
                }
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(5, getDateBytes());
                }
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                    size += com.google.protobuf.CodedOutputStream.computeBytesSize(6, getJexlPreconditionBytes());
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }
            
            private static final long serialVersionUID = 0L;
            
            @java.lang.Override
            protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
                return super.writeReplace();
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(com.google.protobuf.ByteString data)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(com.google.protobuf.ByteString data,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(byte[] data)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(byte[] data,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(java.io.InputStream input) throws java.io.IOException {
                return PARSER.parseFrom(input);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(java.io.InputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseDelimitedFrom(java.io.InputStream input)
                            throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseDelimitedFrom(java.io.InputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return PARSER.parseDelimitedFrom(input, extensionRegistry);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(com.google.protobuf.CodedInputStream input)
                            throws java.io.IOException {
                return PARSER.parseFrom(input);
            }
            
            public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parseFrom(com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return PARSER.parseFrom(input, extensionRegistry);
            }
            
            public static Builder newBuilder() {
                return Builder.create();
            }
            
            public Builder newBuilderForType() {
                return newBuilder();
            }
            
            public static Builder newBuilder(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata prototype) {
                return newBuilder().mergeFrom(prototype);
            }
            
            public Builder toBuilder() {
                return newBuilder(this);
            }
            
            @java.lang.Override
            protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }
            
            /**
             * Protobuf type {@code datawave.metadata.protobuf.MetadataValue.Metadata}
             */
            public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                            // @@protoc_insertion_point(builder_implements:datawave.metadata.protobuf.MetadataValue.Metadata)
                            datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                    return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_descriptor;
                }
                
                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                    return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_fieldAccessorTable
                                    .ensureFieldAccessorsInitialized(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.class,
                                                    datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder.class);
                }
                
                // Construct using datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }
                
                private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }
                
                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
                }
                
                private static Builder create() {
                    return new Builder();
                }
                
                public Builder clear() {
                    super.clear();
                    source_ = "";
                    bitField0_ = (bitField0_ & ~0x00000001);
                    sink_ = "";
                    bitField0_ = (bitField0_ & ~0x00000002);
                    enrichment_ = "";
                    bitField0_ = (bitField0_ & ~0x00000004);
                    enrichmentIndex_ = "";
                    bitField0_ = (bitField0_ & ~0x00000008);
                    date_ = "";
                    bitField0_ = (bitField0_ & ~0x00000010);
                    jexlPrecondition_ = "";
                    bitField0_ = (bitField0_ & ~0x00000020);
                    return this;
                }
                
                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }
                
                public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                    return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_descriptor;
                }
                
                public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata getDefaultInstanceForType() {
                    return datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.getDefaultInstance();
                }
                
                public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata build() {
                    datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }
                
                public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata buildPartial() {
                    datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata result = new datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata(
                                    this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.source_ = source_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.sink_ = sink_;
                    if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                        to_bitField0_ |= 0x00000004;
                    }
                    result.enrichment_ = enrichment_;
                    if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                        to_bitField0_ |= 0x00000008;
                    }
                    result.enrichmentIndex_ = enrichmentIndex_;
                    if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                        to_bitField0_ |= 0x00000010;
                    }
                    result.date_ = date_;
                    if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                        to_bitField0_ |= 0x00000020;
                    }
                    result.jexlPrecondition_ = jexlPrecondition_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }
                
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata) {
                        return mergeFrom((datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }
                
                public Builder mergeFrom(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata other) {
                    if (other == datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.getDefaultInstance())
                        return this;
                    if (other.hasSource()) {
                        bitField0_ |= 0x00000001;
                        source_ = other.source_;
                        onChanged();
                    }
                    if (other.hasSink()) {
                        bitField0_ |= 0x00000002;
                        sink_ = other.sink_;
                        onChanged();
                    }
                    if (other.hasEnrichment()) {
                        bitField0_ |= 0x00000004;
                        enrichment_ = other.enrichment_;
                        onChanged();
                    }
                    if (other.hasEnrichmentIndex()) {
                        bitField0_ |= 0x00000008;
                        enrichmentIndex_ = other.enrichmentIndex_;
                        onChanged();
                    }
                    if (other.hasDate()) {
                        bitField0_ |= 0x00000010;
                        date_ = other.date_;
                        onChanged();
                    }
                    if (other.hasJexlPrecondition()) {
                        bitField0_ |= 0x00000020;
                        jexlPrecondition_ = other.jexlPrecondition_;
                        onChanged();
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }
                
                public final boolean isInitialized() {
                    if (!hasSource()) {
                        
                        return false;
                    }
                    if (!hasSink()) {
                        
                        return false;
                    }
                    return true;
                }
                
                public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                throws java.io.IOException {
                    datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata) e.getUnfinishedMessage();
                        throw e;
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }
                
                private int bitField0_;
                
                private java.lang.Object source_ = "";
                
                /**
                 * <code>required string source = 1;</code>
                 */
                public boolean hasSource() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }
                
                /**
                 * <code>required string source = 1;</code>
                 */
                public java.lang.String getSource() {
                    java.lang.Object ref = source_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            source_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                
                /**
                 * <code>required string source = 1;</code>
                 */
                public com.google.protobuf.ByteString getSourceBytes() {
                    java.lang.Object ref = source_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                        source_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                
                /**
                 * <code>required string source = 1;</code>
                 */
                public Builder setSource(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    source_ = value;
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>required string source = 1;</code>
                 */
                public Builder clearSource() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    source_ = getDefaultInstance().getSource();
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>required string source = 1;</code>
                 */
                public Builder setSourceBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000001;
                    source_ = value;
                    onChanged();
                    return this;
                }
                
                private java.lang.Object sink_ = "";
                
                /**
                 * <code>required string sink = 2;</code>
                 */
                public boolean hasSink() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }
                
                /**
                 * <code>required string sink = 2;</code>
                 */
                public java.lang.String getSink() {
                    java.lang.Object ref = sink_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            sink_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                
                /**
                 * <code>required string sink = 2;</code>
                 */
                public com.google.protobuf.ByteString getSinkBytes() {
                    java.lang.Object ref = sink_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                        sink_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                
                /**
                 * <code>required string sink = 2;</code>
                 */
                public Builder setSink(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    sink_ = value;
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>required string sink = 2;</code>
                 */
                public Builder clearSink() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    sink_ = getDefaultInstance().getSink();
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>required string sink = 2;</code>
                 */
                public Builder setSinkBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    sink_ = value;
                    onChanged();
                    return this;
                }
                
                private java.lang.Object enrichment_ = "";
                
                /**
                 * <code>optional string enrichment = 3;</code>
                 */
                public boolean hasEnrichment() {
                    return ((bitField0_ & 0x00000004) == 0x00000004);
                }
                
                /**
                 * <code>optional string enrichment = 3;</code>
                 */
                public java.lang.String getEnrichment() {
                    java.lang.Object ref = enrichment_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            enrichment_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                
                /**
                 * <code>optional string enrichment = 3;</code>
                 */
                public com.google.protobuf.ByteString getEnrichmentBytes() {
                    java.lang.Object ref = enrichment_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                        enrichment_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                
                /**
                 * <code>optional string enrichment = 3;</code>
                 */
                public Builder setEnrichment(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000004;
                    enrichment_ = value;
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string enrichment = 3;</code>
                 */
                public Builder clearEnrichment() {
                    bitField0_ = (bitField0_ & ~0x00000004);
                    enrichment_ = getDefaultInstance().getEnrichment();
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string enrichment = 3;</code>
                 */
                public Builder setEnrichmentBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000004;
                    enrichment_ = value;
                    onChanged();
                    return this;
                }
                
                private java.lang.Object enrichmentIndex_ = "";
                
                /**
                 * <code>optional string enrichmentIndex = 4;</code>
                 */
                public boolean hasEnrichmentIndex() {
                    return ((bitField0_ & 0x00000008) == 0x00000008);
                }
                
                /**
                 * <code>optional string enrichmentIndex = 4;</code>
                 */
                public java.lang.String getEnrichmentIndex() {
                    java.lang.Object ref = enrichmentIndex_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            enrichmentIndex_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                
                /**
                 * <code>optional string enrichmentIndex = 4;</code>
                 */
                public com.google.protobuf.ByteString getEnrichmentIndexBytes() {
                    java.lang.Object ref = enrichmentIndex_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                        enrichmentIndex_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                
                /**
                 * <code>optional string enrichmentIndex = 4;</code>
                 */
                public Builder setEnrichmentIndex(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000008;
                    enrichmentIndex_ = value;
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string enrichmentIndex = 4;</code>
                 */
                public Builder clearEnrichmentIndex() {
                    bitField0_ = (bitField0_ & ~0x00000008);
                    enrichmentIndex_ = getDefaultInstance().getEnrichmentIndex();
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string enrichmentIndex = 4;</code>
                 */
                public Builder setEnrichmentIndexBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000008;
                    enrichmentIndex_ = value;
                    onChanged();
                    return this;
                }
                
                private java.lang.Object date_ = "";
                
                /**
                 * <code>optional string date = 5;</code>
                 */
                public boolean hasDate() {
                    return ((bitField0_ & 0x00000010) == 0x00000010);
                }
                
                /**
                 * <code>optional string date = 5;</code>
                 */
                public java.lang.String getDate() {
                    java.lang.Object ref = date_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            date_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                
                /**
                 * <code>optional string date = 5;</code>
                 */
                public com.google.protobuf.ByteString getDateBytes() {
                    java.lang.Object ref = date_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                        date_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                
                /**
                 * <code>optional string date = 5;</code>
                 */
                public Builder setDate(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000010;
                    date_ = value;
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string date = 5;</code>
                 */
                public Builder clearDate() {
                    bitField0_ = (bitField0_ & ~0x00000010);
                    date_ = getDefaultInstance().getDate();
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string date = 5;</code>
                 */
                public Builder setDateBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000010;
                    date_ = value;
                    onChanged();
                    return this;
                }
                
                private java.lang.Object jexlPrecondition_ = "";
                
                /**
                 * <code>optional string jexlPrecondition = 6;</code>
                 */
                public boolean hasJexlPrecondition() {
                    return ((bitField0_ & 0x00000020) == 0x00000020);
                }
                
                /**
                 * <code>optional string jexlPrecondition = 6;</code>
                 */
                public java.lang.String getJexlPrecondition() {
                    java.lang.Object ref = jexlPrecondition_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        if (bs.isValidUtf8()) {
                            jexlPrecondition_ = s;
                        }
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }
                
                /**
                 * <code>optional string jexlPrecondition = 6;</code>
                 */
                public com.google.protobuf.ByteString getJexlPreconditionBytes() {
                    java.lang.Object ref = jexlPrecondition_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                        jexlPrecondition_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }
                
                /**
                 * <code>optional string jexlPrecondition = 6;</code>
                 */
                public Builder setJexlPrecondition(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000020;
                    jexlPrecondition_ = value;
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string jexlPrecondition = 6;</code>
                 */
                public Builder clearJexlPrecondition() {
                    bitField0_ = (bitField0_ & ~0x00000020);
                    jexlPrecondition_ = getDefaultInstance().getJexlPrecondition();
                    onChanged();
                    return this;
                }
                
                /**
                 * <code>optional string jexlPrecondition = 6;</code>
                 */
                public Builder setJexlPreconditionBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000020;
                    jexlPrecondition_ = value;
                    onChanged();
                    return this;
                }
                
                // @@protoc_insertion_point(builder_scope:datawave.metadata.protobuf.MetadataValue.Metadata)
            }
            
            static {
                defaultInstance = new Metadata(true);
                defaultInstance.initFields();
            }
            
            // @@protoc_insertion_point(class_scope:datawave.metadata.protobuf.MetadataValue.Metadata)
        }
        
        public static final int METADATA_FIELD_NUMBER = 1;
        private java.util.List<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata> metadata_;
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        public java.util.List<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata> getMetadataList() {
            return metadata_;
        }
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        public java.util.List<? extends datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder> getMetadataOrBuilderList() {
            return metadata_;
        }
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        public int getMetadataCount() {
            return metadata_.size();
        }
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata getMetadata(int index) {
            return metadata_.get(index);
        }
        
        /**
         * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
         */
        public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder getMetadataOrBuilder(int index) {
            return metadata_.get(index);
        }
        
        private void initFields() {
            metadata_ = java.util.Collections.emptyList();
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;
            
            for (int i = 0; i < getMetadataCount(); i++) {
                if (!getMetadata(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < metadata_.size(); i++) {
                output.writeMessage(1, metadata_.get(i));
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            for (int i = 0; i < metadata_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, metadata_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseDelimitedFrom(java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        
        public static datawave.metadata.protobuf.EdgeMetadata.MetadataValue parseFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        
        public static Builder newBuilder() {
            return Builder.create();
        }
        
        public Builder newBuilderForType() {
            return newBuilder();
        }
        
        public static Builder newBuilder(datawave.metadata.protobuf.EdgeMetadata.MetadataValue prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder() {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        /**
         * Protobuf type {@code datawave.metadata.protobuf.MetadataValue}
         *
         * <pre>
         * moved this out because no need for Metadata values to appear in the standard edge table.
         * this would be fixed if packed=true worked on strings, but meh
         * </pre>
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                        // @@protoc_insertion_point(builder_implements:datawave.metadata.protobuf.MetadataValue)
                        datawave.metadata.protobuf.EdgeMetadata.MetadataValueOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_fieldAccessorTable
                                .ensureFieldAccessorsInitialized(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.class,
                                                datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Builder.class);
            }
            
            // Construct using datawave.metadata.protobuf.EdgeMetadata.MetadataValue.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }
            
            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getMetadataFieldBuilder();
                }
            }
            
            private static Builder create() {
                return new Builder();
            }
            
            public Builder clear() {
                super.clear();
                if (metadataBuilder_ == null) {
                    metadata_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    metadataBuilder_.clear();
                }
                return this;
            }
            
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return datawave.metadata.protobuf.EdgeMetadata.internal_static_datawave_metadata_protobuf_MetadataValue_descriptor;
            }
            
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue getDefaultInstanceForType() {
                return datawave.metadata.protobuf.EdgeMetadata.MetadataValue.getDefaultInstance();
            }
            
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue build() {
                datawave.metadata.protobuf.EdgeMetadata.MetadataValue result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue buildPartial() {
                datawave.metadata.protobuf.EdgeMetadata.MetadataValue result = new datawave.metadata.protobuf.EdgeMetadata.MetadataValue(this);
                int from_bitField0_ = bitField0_;
                if (metadataBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        metadata_ = java.util.Collections.unmodifiableList(metadata_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.metadata_ = metadata_;
                } else {
                    result.metadata_ = metadataBuilder_.build();
                }
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof datawave.metadata.protobuf.EdgeMetadata.MetadataValue) {
                    return mergeFrom((datawave.metadata.protobuf.EdgeMetadata.MetadataValue) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(datawave.metadata.protobuf.EdgeMetadata.MetadataValue other) {
                if (other == datawave.metadata.protobuf.EdgeMetadata.MetadataValue.getDefaultInstance())
                    return this;
                if (metadataBuilder_ == null) {
                    if (!other.metadata_.isEmpty()) {
                        if (metadata_.isEmpty()) {
                            metadata_ = other.metadata_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureMetadataIsMutable();
                            metadata_.addAll(other.metadata_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.metadata_.isEmpty()) {
                        if (metadataBuilder_.isEmpty()) {
                            metadataBuilder_.dispose();
                            metadataBuilder_ = null;
                            metadata_ = other.metadata_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            metadataBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getMetadataFieldBuilder() : null;
                        } else {
                            metadataBuilder_.addAllMessages(other.metadata_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized() {
                for (int i = 0; i < getMetadataCount(); i++) {
                    if (!getMetadata(i).isInitialized()) {
                        
                        return false;
                    }
                }
                return true;
            }
            
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                datawave.metadata.protobuf.EdgeMetadata.MetadataValue parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (datawave.metadata.protobuf.EdgeMetadata.MetadataValue) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            
            private int bitField0_;
            
            private java.util.List<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata> metadata_ = java.util.Collections.emptyList();
            
            private void ensureMetadataIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    metadata_ = new java.util.ArrayList<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata>(metadata_);
                    bitField0_ |= 0x00000001;
                }
            }
            
            private com.google.protobuf.RepeatedFieldBuilder<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata,datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder,datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder> metadataBuilder_;
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public java.util.List<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata> getMetadataList() {
                if (metadataBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(metadata_);
                } else {
                    return metadataBuilder_.getMessageList();
                }
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public int getMetadataCount() {
                if (metadataBuilder_ == null) {
                    return metadata_.size();
                } else {
                    return metadataBuilder_.getCount();
                }
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata getMetadata(int index) {
                if (metadataBuilder_ == null) {
                    return metadata_.get(index);
                } else {
                    return metadataBuilder_.getMessage(index);
                }
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder setMetadata(int index, datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata value) {
                if (metadataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMetadataIsMutable();
                    metadata_.set(index, value);
                    onChanged();
                } else {
                    metadataBuilder_.setMessage(index, value);
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder setMetadata(int index, datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder builderForValue) {
                if (metadataBuilder_ == null) {
                    ensureMetadataIsMutable();
                    metadata_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    metadataBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder addMetadata(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata value) {
                if (metadataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMetadataIsMutable();
                    metadata_.add(value);
                    onChanged();
                } else {
                    metadataBuilder_.addMessage(value);
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder addMetadata(int index, datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata value) {
                if (metadataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMetadataIsMutable();
                    metadata_.add(index, value);
                    onChanged();
                } else {
                    metadataBuilder_.addMessage(index, value);
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder addMetadata(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder builderForValue) {
                if (metadataBuilder_ == null) {
                    ensureMetadataIsMutable();
                    metadata_.add(builderForValue.build());
                    onChanged();
                } else {
                    metadataBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder addMetadata(int index, datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder builderForValue) {
                if (metadataBuilder_ == null) {
                    ensureMetadataIsMutable();
                    metadata_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    metadataBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder addAllMetadata(java.lang.Iterable<? extends datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata> values) {
                if (metadataBuilder_ == null) {
                    ensureMetadataIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, metadata_);
                    onChanged();
                } else {
                    metadataBuilder_.addAllMessages(values);
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder clearMetadata() {
                if (metadataBuilder_ == null) {
                    metadata_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    metadataBuilder_.clear();
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public Builder removeMetadata(int index) {
                if (metadataBuilder_ == null) {
                    ensureMetadataIsMutable();
                    metadata_.remove(index);
                    onChanged();
                } else {
                    metadataBuilder_.remove(index);
                }
                return this;
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder getMetadataBuilder(int index) {
                return getMetadataFieldBuilder().getBuilder(index);
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder getMetadataOrBuilder(int index) {
                if (metadataBuilder_ == null) {
                    return metadata_.get(index);
                } else {
                    return metadataBuilder_.getMessageOrBuilder(index);
                }
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public java.util.List<? extends datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder> getMetadataOrBuilderList() {
                if (metadataBuilder_ != null) {
                    return metadataBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(metadata_);
                }
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder addMetadataBuilder() {
                return getMetadataFieldBuilder().addBuilder(datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.getDefaultInstance());
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder addMetadataBuilder(int index) {
                return getMetadataFieldBuilder().addBuilder(index, datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.getDefaultInstance());
            }
            
            /**
             * <code>repeated .datawave.metadata.protobuf.MetadataValue.Metadata metadata = 1;</code>
             */
            public java.util.List<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder> getMetadataBuilderList() {
                return getMetadataFieldBuilder().getBuilderList();
            }
            
            private com.google.protobuf.RepeatedFieldBuilder<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata,datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder,datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder> getMetadataFieldBuilder() {
                if (metadataBuilder_ == null) {
                    metadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata,datawave.metadata.protobuf.EdgeMetadata.MetadataValue.Metadata.Builder,datawave.metadata.protobuf.EdgeMetadata.MetadataValue.MetadataOrBuilder>(
                                    metadata_, ((bitField0_ & 0x00000001) == 0x00000001), getParentForChildren(), isClean());
                    metadata_ = null;
                }
                return metadataBuilder_;
            }
            
            // @@protoc_insertion_point(builder_scope:datawave.metadata.protobuf.MetadataValue)
        }
        
        static {
            defaultInstance = new MetadataValue(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:datawave.metadata.protobuf.MetadataValue)
    }
    
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_datawave_metadata_protobuf_MetadataValue_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_datawave_metadata_protobuf_MetadataValue_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_fieldAccessorTable;
    
    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
    
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\022EdgeMetadata.proto\022\032datawave.metadata." + "protobuf\"\324\001\n\rMetadataValue\022D\n\010metadata\030\001"
                                + " \003(\01322.datawave.metadata.protobuf.Metada" + "taValue.Metadata\032}\n\010Metadata\022\016\n\006source\030\001"
                                + " \002(\t\022\014\n\004sink\030\002 \002(\t\022\022\n\nenrichment\030\003 \001(\t\022\027"
                                + "\n\017enrichmentIndex\030\004 \001(\t\022\014\n\004date\030\005 \001(\t\022\030\n"
                                + "\020jexlPrecondition\030\006 \001(\tB\036\n\032datawave.meta" + "data.protobufH\001"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {},
                        assigner);
        internal_static_datawave_metadata_protobuf_MetadataValue_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_datawave_metadata_protobuf_MetadataValue_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_datawave_metadata_protobuf_MetadataValue_descriptor, new java.lang.String[] {"Metadata",});
        internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_descriptor = internal_static_datawave_metadata_protobuf_MetadataValue_descriptor
                        .getNestedTypes().get(0);
        internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_datawave_metadata_protobuf_MetadataValue_Metadata_descriptor,
                        new java.lang.String[] {"Source", "Sink", "Enrichment", "EnrichmentIndex", "Date", "JexlPrecondition",});
    }
    
    // @@protoc_insertion_point(outer_class_scope)
}
