// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TermWeight.proto

package datawave.ingest.protobuf;

public final class TermWeight {
    private TermWeight() {}
    
    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}
    
    public interface InfoOrBuilder extends com.google.protobuf.MessageOrBuilder {
        
        // repeated uint32 termOffset = 3;
        /**
         * <code>repeated uint32 termOffset = 3;</code>
         */
        java.util.List<java.lang.Integer> getTermOffsetList();
        
        /**
         * <code>repeated uint32 termOffset = 3;</code>
         */
        int getTermOffsetCount();
        
        /**
         * <code>repeated uint32 termOffset = 3;</code>
         */
        int getTermOffset(int index);
        
        // repeated uint32 prevSkips = 4;
        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         */
        java.util.List<java.lang.Integer> getPrevSkipsList();
        
        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         */
        int getPrevSkipsCount();
        
        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         */
        int getPrevSkips(int index);
        
        // repeated uint32 score = 5;
        /**
         * <code>repeated uint32 score = 5;</code>
         */
        java.util.List<java.lang.Integer> getScoreList();
        
        /**
         * <code>repeated uint32 score = 5;</code>
         */
        int getScoreCount();
        
        /**
         * <code>repeated uint32 score = 5;</code>
         */
        int getScore(int index);
        
        // optional bool zeroOffsetMatch = 6 [default = true];
        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         */
        boolean hasZeroOffsetMatch();
        
        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         */
        boolean getZeroOffsetMatch();
    }
    
    /**
     * Protobuf type {@code datawave.ingest.protobuf.Info}
     */
    public static final class Info extends com.google.protobuf.GeneratedMessage implements InfoOrBuilder {
        // Use Info.newBuilder() to construct.
        private Info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        
        private Info(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        
        private static final Info defaultInstance;
        
        public static Info getDefaultInstance() {
            return defaultInstance;
        }
        
        public Info getDefaultInstanceForType() {
            return defaultInstance;
        }
        
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }
        
        private Info(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 24: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                termOffset_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            termOffset_.add(input.readUInt32());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                                termOffset_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                termOffset_.add(input.readUInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 32: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                prevSkips_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            prevSkips_.add(input.readUInt32());
                            break;
                        }
                        case 34: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                                prevSkips_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                prevSkips_.add(input.readUInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 40: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                score_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            score_.add(input.readUInt32());
                            break;
                        }
                        case 42: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                                score_ = new java.util.ArrayList<java.lang.Integer>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                score_.add(input.readUInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000001;
                            zeroOffsetMatch_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    termOffset_ = java.util.Collections.unmodifiableList(termOffset_);
                }
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    prevSkips_ = java.util.Collections.unmodifiableList(prevSkips_);
                }
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    score_ = java.util.Collections.unmodifiableList(score_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.ingest.protobuf.TermWeight.internal_static_datawave_ingest_protobuf_Info_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.ingest.protobuf.TermWeight.internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable.ensureFieldAccessorsInitialized(
                            datawave.ingest.protobuf.TermWeight.Info.class, datawave.ingest.protobuf.TermWeight.Info.Builder.class);
        }
        
        public static com.google.protobuf.Parser<Info> PARSER = new com.google.protobuf.AbstractParser<Info>() {
            public Info parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new Info(input, extensionRegistry);
            }
        };
        
        @java.lang.Override
        public com.google.protobuf.Parser<Info> getParserForType() {
            return PARSER;
        }
        
        private int bitField0_;
        // repeated uint32 termOffset = 3;
        public static final int TERMOFFSET_FIELD_NUMBER = 3;
        private java.util.List<java.lang.Integer> termOffset_;
        
        /**
         * <code>repeated uint32 termOffset = 3;</code>
         */
        public java.util.List<java.lang.Integer> getTermOffsetList() {
            return termOffset_;
        }
        
        /**
         * <code>repeated uint32 termOffset = 3;</code>
         */
        public int getTermOffsetCount() {
            return termOffset_.size();
        }
        
        /**
         * <code>repeated uint32 termOffset = 3;</code>
         */
        public int getTermOffset(int index) {
            return termOffset_.get(index);
        }
        
        // repeated uint32 prevSkips = 4;
        public static final int PREVSKIPS_FIELD_NUMBER = 4;
        private java.util.List<java.lang.Integer> prevSkips_;
        
        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         */
        public java.util.List<java.lang.Integer> getPrevSkipsList() {
            return prevSkips_;
        }
        
        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         */
        public int getPrevSkipsCount() {
            return prevSkips_.size();
        }
        
        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         */
        public int getPrevSkips(int index) {
            return prevSkips_.get(index);
        }
        
        // repeated uint32 score = 5;
        public static final int SCORE_FIELD_NUMBER = 5;
        private java.util.List<java.lang.Integer> score_;
        
        /**
         * <code>repeated uint32 score = 5;</code>
         */
        public java.util.List<java.lang.Integer> getScoreList() {
            return score_;
        }
        
        /**
         * <code>repeated uint32 score = 5;</code>
         */
        public int getScoreCount() {
            return score_.size();
        }
        
        /**
         * <code>repeated uint32 score = 5;</code>
         */
        public int getScore(int index) {
            return score_.get(index);
        }
        
        // optional bool zeroOffsetMatch = 6 [default = true];
        public static final int ZEROOFFSETMATCH_FIELD_NUMBER = 6;
        private boolean zeroOffsetMatch_;
        
        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         */
        public boolean hasZeroOffsetMatch() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         */
        public boolean getZeroOffsetMatch() {
            return zeroOffsetMatch_;
        }
        
        private void initFields() {
            termOffset_ = java.util.Collections.emptyList();
            prevSkips_ = java.util.Collections.emptyList();
            score_ = java.util.Collections.emptyList();
            zeroOffsetMatch_ = true;
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;
            
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < termOffset_.size(); i++) {
                output.writeUInt32(3, termOffset_.get(i));
            }
            for (int i = 0; i < prevSkips_.size(); i++) {
                output.writeUInt32(4, prevSkips_.get(i));
            }
            for (int i = 0; i < score_.size(); i++) {
                output.writeUInt32(5, score_.get(i));
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBool(6, zeroOffsetMatch_);
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < termOffset_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(termOffset_.get(i));
                }
                size += dataSize;
                size += 1 * getTermOffsetList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < prevSkips_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(prevSkips_.get(i));
                }
                size += dataSize;
                size += 1 * getPrevSkipsList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < score_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(score_.get(i));
                }
                size += dataSize;
                size += 1 * getScoreList().size();
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(6, zeroOffsetMatch_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseDelimitedFrom(java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        
        public static datawave.ingest.protobuf.TermWeight.Info parseFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        
        public static Builder newBuilder() {
            return Builder.create();
        }
        
        public Builder newBuilderForType() {
            return newBuilder();
        }
        
        public static Builder newBuilder(datawave.ingest.protobuf.TermWeight.Info prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder() {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        /**
         * Protobuf type {@code datawave.ingest.protobuf.Info}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                        datawave.ingest.protobuf.TermWeight.InfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return datawave.ingest.protobuf.TermWeight.internal_static_datawave_ingest_protobuf_Info_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return datawave.ingest.protobuf.TermWeight.internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable.ensureFieldAccessorsInitialized(
                                datawave.ingest.protobuf.TermWeight.Info.class, datawave.ingest.protobuf.TermWeight.Info.Builder.class);
            }
            
            // Construct using datawave.ingest.protobuf.TermWeight.Info.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }
            
            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
            }
            
            private static Builder create() {
                return new Builder();
            }
            
            public Builder clear() {
                super.clear();
                termOffset_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                prevSkips_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                score_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                zeroOffsetMatch_ = true;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }
            
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return datawave.ingest.protobuf.TermWeight.internal_static_datawave_ingest_protobuf_Info_descriptor;
            }
            
            public datawave.ingest.protobuf.TermWeight.Info getDefaultInstanceForType() {
                return datawave.ingest.protobuf.TermWeight.Info.getDefaultInstance();
            }
            
            public datawave.ingest.protobuf.TermWeight.Info build() {
                datawave.ingest.protobuf.TermWeight.Info result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            public datawave.ingest.protobuf.TermWeight.Info buildPartial() {
                datawave.ingest.protobuf.TermWeight.Info result = new datawave.ingest.protobuf.TermWeight.Info(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    termOffset_ = java.util.Collections.unmodifiableList(termOffset_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.termOffset_ = termOffset_;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    prevSkips_ = java.util.Collections.unmodifiableList(prevSkips_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.prevSkips_ = prevSkips_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    score_ = java.util.Collections.unmodifiableList(score_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.score_ = score_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.zeroOffsetMatch_ = zeroOffsetMatch_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof datawave.ingest.protobuf.TermWeight.Info) {
                    return mergeFrom((datawave.ingest.protobuf.TermWeight.Info) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(datawave.ingest.protobuf.TermWeight.Info other) {
                if (other == datawave.ingest.protobuf.TermWeight.Info.getDefaultInstance())
                    return this;
                if (!other.termOffset_.isEmpty()) {
                    if (termOffset_.isEmpty()) {
                        termOffset_ = other.termOffset_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureTermOffsetIsMutable();
                        termOffset_.addAll(other.termOffset_);
                    }
                    onChanged();
                }
                if (!other.prevSkips_.isEmpty()) {
                    if (prevSkips_.isEmpty()) {
                        prevSkips_ = other.prevSkips_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensurePrevSkipsIsMutable();
                        prevSkips_.addAll(other.prevSkips_);
                    }
                    onChanged();
                }
                if (!other.score_.isEmpty()) {
                    if (score_.isEmpty()) {
                        score_ = other.score_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureScoreIsMutable();
                        score_.addAll(other.score_);
                    }
                    onChanged();
                }
                if (other.hasZeroOffsetMatch()) {
                    setZeroOffsetMatch(other.getZeroOffsetMatch());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized() {
                return true;
            }
            
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                datawave.ingest.protobuf.TermWeight.Info parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (datawave.ingest.protobuf.TermWeight.Info) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            
            private int bitField0_;
            
            // repeated uint32 termOffset = 3;
            private java.util.List<java.lang.Integer> termOffset_ = java.util.Collections.emptyList();
            
            private void ensureTermOffsetIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    termOffset_ = new java.util.ArrayList<java.lang.Integer>(termOffset_);
                    bitField0_ |= 0x00000001;
                }
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public java.util.List<java.lang.Integer> getTermOffsetList() {
                return java.util.Collections.unmodifiableList(termOffset_);
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public int getTermOffsetCount() {
                return termOffset_.size();
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public int getTermOffset(int index) {
                return termOffset_.get(index);
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public Builder setTermOffset(int index, int value) {
                ensureTermOffsetIsMutable();
                termOffset_.set(index, value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public Builder addTermOffset(int value) {
                ensureTermOffsetIsMutable();
                termOffset_.add(value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public Builder addAllTermOffset(java.lang.Iterable<? extends java.lang.Integer> values) {
                ensureTermOffsetIsMutable();
                super.addAll(values, termOffset_);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 termOffset = 3;</code>
             */
            public Builder clearTermOffset() {
                termOffset_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }
            
            // repeated uint32 prevSkips = 4;
            private java.util.List<java.lang.Integer> prevSkips_ = java.util.Collections.emptyList();
            
            private void ensurePrevSkipsIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    prevSkips_ = new java.util.ArrayList<java.lang.Integer>(prevSkips_);
                    bitField0_ |= 0x00000002;
                }
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public java.util.List<java.lang.Integer> getPrevSkipsList() {
                return java.util.Collections.unmodifiableList(prevSkips_);
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public int getPrevSkipsCount() {
                return prevSkips_.size();
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public int getPrevSkips(int index) {
                return prevSkips_.get(index);
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public Builder setPrevSkips(int index, int value) {
                ensurePrevSkipsIsMutable();
                prevSkips_.set(index, value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public Builder addPrevSkips(int value) {
                ensurePrevSkipsIsMutable();
                prevSkips_.add(value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public Builder addAllPrevSkips(java.lang.Iterable<? extends java.lang.Integer> values) {
                ensurePrevSkipsIsMutable();
                super.addAll(values, prevSkips_);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             */
            public Builder clearPrevSkips() {
                prevSkips_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }
            
            // repeated uint32 score = 5;
            private java.util.List<java.lang.Integer> score_ = java.util.Collections.emptyList();
            
            private void ensureScoreIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    score_ = new java.util.ArrayList<java.lang.Integer>(score_);
                    bitField0_ |= 0x00000004;
                }
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public java.util.List<java.lang.Integer> getScoreList() {
                return java.util.Collections.unmodifiableList(score_);
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public int getScoreCount() {
                return score_.size();
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public int getScore(int index) {
                return score_.get(index);
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public Builder setScore(int index, int value) {
                ensureScoreIsMutable();
                score_.set(index, value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public Builder addScore(int value) {
                ensureScoreIsMutable();
                score_.add(value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public Builder addAllScore(java.lang.Iterable<? extends java.lang.Integer> values) {
                ensureScoreIsMutable();
                super.addAll(values, score_);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated uint32 score = 5;</code>
             */
            public Builder clearScore() {
                score_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }
            
            // optional bool zeroOffsetMatch = 6 [default = true];
            private boolean zeroOffsetMatch_ = true;
            
            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             */
            public boolean hasZeroOffsetMatch() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            
            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             */
            public boolean getZeroOffsetMatch() {
                return zeroOffsetMatch_;
            }
            
            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             */
            public Builder setZeroOffsetMatch(boolean value) {
                bitField0_ |= 0x00000008;
                zeroOffsetMatch_ = value;
                onChanged();
                return this;
            }
            
            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             */
            public Builder clearZeroOffsetMatch() {
                bitField0_ = (bitField0_ & ~0x00000008);
                zeroOffsetMatch_ = true;
                onChanged();
                return this;
            }
            
            // @@protoc_insertion_point(builder_scope:datawave.ingest.protobuf.Info)
        }
        
        static {
            defaultInstance = new Info(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:datawave.ingest.protobuf.Info)
    }
    
    private static com.google.protobuf.Descriptors.Descriptor internal_static_datawave_ingest_protobuf_Info_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable;
    
    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
    
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {"\n\020TermWeight.proto\022\030datawave.ingest.prot"
                        + "obuf\"[\n\004Info\022\022\n\ntermOffset\030\003 \003(\r\022\021\n\tprev"
                        + "Skips\030\004 \003(\r\022\r\n\005score\030\005 \003(\r\022\035\n\017zeroOffset"
                        + "Match\030\006 \001(\010:\004trueB\034\n\030datawave.ingest.pro" + "tobufH\001"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_datawave_ingest_protobuf_Info_descriptor = getDescriptor().getMessageTypes().get(0);
                internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_datawave_ingest_protobuf_Info_descriptor, new java.lang.String[] {"TermOffset", "PrevSkips", "Score",
                                        "ZeroOffsetMatch",});
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {},
                        assigner);
    }
    
    // @@protoc_insertion_point(outer_class_scope)
}
