// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Uid.proto

package datawave.ingest.protobuf;

import com.google.protobuf.Descriptors;
import com.google.protobuf.LazyStringArrayList;
import com.google.protobuf.Message;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public final class Uid {
    private Uid() {}
    
    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}
    
    public interface ListOrBuilder extends com.google.protobuf.MessageOrBuilder {
        
        // required bool IGNORE = 1;
        /**
         * <code>required bool IGNORE = 1;</code>
         */
        boolean hasIGNORE();
        
        /**
         * <code>required bool IGNORE = 1;</code>
         */
        boolean getIGNORE();
        
        // required uint64 COUNT = 2;
        /**
         * <code>required uint64 COUNT = 2;</code>
         */
        boolean hasCOUNT();
        
        /**
         * <code>required uint64 COUNT = 2;</code>
         */
        long getCOUNT();
        
        // repeated string UID = 3;
        /**
         * <code>repeated string UID = 3;</code>
         */
        java.util.List<java.lang.String> getUIDList();
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        int getUIDCount();
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        java.lang.String getUID(int index);
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        com.google.protobuf.ByteString getUIDBytes(int index);
        
        // repeated string REMOVEDUID = 4;
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        java.util.List<java.lang.String> getREMOVEDUIDList();
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        int getREMOVEDUIDCount();
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        java.lang.String getREMOVEDUID(int index);
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        com.google.protobuf.ByteString getREMOVEDUIDBytes(int index);
    }
    
    /**
     * Protobuf type {@code datawave.ingest.protobuf.List}
     */
    public static final class List extends com.google.protobuf.GeneratedMessage implements ListOrBuilder {
        // Use List.newBuilder() to construct.
        private List(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        
        private List(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        
        private static final List defaultInstance;
        
        public static List getDefaultInstance() {
            return defaultInstance;
        }
        
        public List getDefaultInstanceForType() {
            return defaultInstance;
        }
        
        private final com.google.protobuf.UnknownFieldSet unknownFields;
        
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }
        
        private List(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            iGNORE_ = input.readBool();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            cOUNT_ = input.readUInt64();
                            break;
                        }
                        case 26: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                uID_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            uID_.add(input.readBytes());
                            break;
                        }
                        case 34: {
                            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                                rEMOVEDUID_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000008;
                            }
                            rEMOVEDUID_.add(input.readBytes());
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    uID_ = new com.google.protobuf.UnmodifiableLazyStringList(uID_);
                }
                if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                    rEMOVEDUID_ = new com.google.protobuf.UnmodifiableLazyStringList(rEMOVEDUID_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        
        public boolean sameAs(final Object other) {
            if (other == this) {
                return true;
            }
            if (!(other instanceof Uid.List)) {
                return false;
            }
            
            final Uid.List otherList = (Uid.List) other;
            if (getDescriptorForType() != otherList.getDescriptorForType()) {
                return false;
            }
            
            return iGNORE_ == otherList.iGNORE_ && cOUNT_ == otherList.cOUNT_ && sameList(uID_, otherList.uID_) && sameList(rEMOVEDUID_, otherList.rEMOVEDUID_);
            
        }
        
        public boolean sameAs2(final Object other) {
            if (other == this) {
                return true;
            }
            if (!(other instanceof Uid.List)) {
                return false;
            }
            
            final Uid.List otherList = (Uid.List) other;
            if (getDescriptorForType() != otherList.getDescriptorForType()) {
                return false;
            }
            
            Map<Descriptors.FieldDescriptor,Object> fields = getAllFields();
            Map<Descriptors.FieldDescriptor,Object> otherFields = otherList.getAllFields();
            if (fields.size() != otherFields.size()) {
                return false;
            }
            
            for (Descriptors.FieldDescriptor key : fields.keySet()) {
                Object value = fields.get(key);
                Object otherValue = otherFields.get(key);
                
                if (key.isRepeated()) {
                    if (!sameList2((java.util.List<?>) value, (java.util.List<?>) otherValue)) {
                        return false;
                    }
                } else {
                    if (!value.equals(otherValue)) {
                        return false;
                    }
                }
            }
            return true;
        }
        
        private boolean sameList(java.util.List<String> list1, java.util.List<String> list2) {
            java.util.List<String> _list1 = new ArrayList<>(list1);
            java.util.List<String> _list2 = new ArrayList<>(list2);
            Collections.sort(_list1);
            Collections.sort(_list2);
            return _list1.equals(_list2);
        }
        
        private boolean sameList2(java.util.List<?> list1, java.util.List<?> list2) {
            if (list1.size() != list2.size()) {
                return false;
            }
            
            Set<?> set1 = new HashSet<>(list1);
            Set<?> set2 = new HashSet<>(list2);
            return set1.equals(set2);
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.ingest.protobuf.Uid.internal_static_datawave_ingest_protobuf_List_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.ingest.protobuf.Uid.internal_static_datawave_ingest_protobuf_List_fieldAccessorTable.ensureFieldAccessorsInitialized(
                            datawave.ingest.protobuf.Uid.List.class, datawave.ingest.protobuf.Uid.List.Builder.class);
        }
        
        public static com.google.protobuf.Parser<List> PARSER = new com.google.protobuf.AbstractParser<List>() {
            public List parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new List(input, extensionRegistry);
            }
        };
        
        @java.lang.Override
        public com.google.protobuf.Parser<List> getParserForType() {
            return PARSER;
        }
        
        private int bitField0_;
        // required bool IGNORE = 1;
        public static final int IGNORE_FIELD_NUMBER = 1;
        private boolean iGNORE_;
        
        /**
         * <code>required bool IGNORE = 1;</code>
         */
        public boolean hasIGNORE() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        
        /**
         * <code>required bool IGNORE = 1;</code>
         */
        public boolean getIGNORE() {
            return iGNORE_;
        }
        
        // required uint64 COUNT = 2;
        public static final int COUNT_FIELD_NUMBER = 2;
        private long cOUNT_;
        
        /**
         * <code>required uint64 COUNT = 2;</code>
         */
        public boolean hasCOUNT() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        
        /**
         * <code>required uint64 COUNT = 2;</code>
         */
        public long getCOUNT() {
            return cOUNT_;
        }
        
        // repeated string UID = 3;
        public static final int UID_FIELD_NUMBER = 3;
        private com.google.protobuf.LazyStringList uID_;
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        public java.util.List<java.lang.String> getUIDList() {
            return uID_;
        }
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        public int getUIDCount() {
            return uID_.size();
        }
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        public java.lang.String getUID(int index) {
            return uID_.get(index);
        }
        
        /**
         * <code>repeated string UID = 3;</code>
         */
        public com.google.protobuf.ByteString getUIDBytes(int index) {
            return uID_.getByteString(index);
        }
        
        // repeated string REMOVEDUID = 4;
        public static final int REMOVEDUID_FIELD_NUMBER = 4;
        private com.google.protobuf.LazyStringList rEMOVEDUID_;
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        public java.util.List<java.lang.String> getREMOVEDUIDList() {
            return rEMOVEDUID_;
        }
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        public int getREMOVEDUIDCount() {
            return rEMOVEDUID_.size();
        }
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        public java.lang.String getREMOVEDUID(int index) {
            return rEMOVEDUID_.get(index);
        }
        
        /**
         * <code>repeated string REMOVEDUID = 4;</code>
         */
        public com.google.protobuf.ByteString getREMOVEDUIDBytes(int index) {
            return rEMOVEDUID_.getByteString(index);
        }
        
        private void initFields() {
            iGNORE_ = false;
            cOUNT_ = 0L;
            uID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            rEMOVEDUID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }
        
        private byte memoizedIsInitialized = -1;
        
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1)
                return isInitialized == 1;
            
            if (!hasIGNORE()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCOUNT()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBool(1, iGNORE_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeUInt64(2, cOUNT_);
            }
            for (int i = 0; i < uID_.size(); i++) {
                output.writeBytes(3, uID_.getByteString(i));
            }
            for (int i = 0; i < rEMOVEDUID_.size(); i++) {
                output.writeBytes(4, rEMOVEDUID_.getByteString(i));
            }
            getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1)
                return size;
            
            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(1, iGNORE_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, cOUNT_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < uID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(uID_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getUIDList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < rEMOVEDUID_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeBytesSizeNoTag(rEMOVEDUID_.getByteString(i));
                }
                size += dataSize;
                size += 1 * getREMOVEDUIDList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }
        
        private static final long serialVersionUID = 0L;
        
        @java.lang.Override
        protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
            return super.writeReplace();
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(com.google.protobuf.ByteString data)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(com.google.protobuf.ByteString data,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseDelimitedFrom(java.io.InputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        
        public static datawave.ingest.protobuf.Uid.List parseFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        
        public static Builder newBuilder() {
            return Builder.create();
        }
        
        public Builder newBuilderForType() {
            return newBuilder();
        }
        
        public static Builder newBuilder(datawave.ingest.protobuf.Uid.List prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        
        public Builder toBuilder() {
            return newBuilder(this);
        }
        
        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        
        /**
         * Protobuf type {@code datawave.ingest.protobuf.List}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements datawave.ingest.protobuf.Uid.ListOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return datawave.ingest.protobuf.Uid.internal_static_datawave_ingest_protobuf_List_descriptor;
            }
            
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return datawave.ingest.protobuf.Uid.internal_static_datawave_ingest_protobuf_List_fieldAccessorTable.ensureFieldAccessorsInitialized(
                                datawave.ingest.protobuf.Uid.List.class, datawave.ingest.protobuf.Uid.List.Builder.class);
            }
            
            // Construct using datawave.ingest.protobuf.Uid.List.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }
            
            private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {}
            }
            
            private static Builder create() {
                return new Builder();
            }
            
            public Builder clear() {
                super.clear();
                iGNORE_ = false;
                bitField0_ = (bitField0_ & ~0x00000001);
                cOUNT_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                uID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                rEMOVEDUID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }
            
            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }
            
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return datawave.ingest.protobuf.Uid.internal_static_datawave_ingest_protobuf_List_descriptor;
            }
            
            public datawave.ingest.protobuf.Uid.List getDefaultInstanceForType() {
                return datawave.ingest.protobuf.Uid.List.getDefaultInstance();
            }
            
            public datawave.ingest.protobuf.Uid.List build() {
                datawave.ingest.protobuf.Uid.List result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }
            
            public datawave.ingest.protobuf.Uid.List buildPartial() {
                datawave.ingest.protobuf.Uid.List result = new datawave.ingest.protobuf.Uid.List(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.iGNORE_ = iGNORE_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.cOUNT_ = cOUNT_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    uID_ = new com.google.protobuf.UnmodifiableLazyStringList(uID_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.uID_ = uID_;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    rEMOVEDUID_ = new com.google.protobuf.UnmodifiableLazyStringList(rEMOVEDUID_);
                    bitField0_ = (bitField0_ & ~0x00000008);
                }
                result.rEMOVEDUID_ = rEMOVEDUID_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }
            
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof datawave.ingest.protobuf.Uid.List) {
                    return mergeFrom((datawave.ingest.protobuf.Uid.List) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }
            
            public Builder mergeFrom(datawave.ingest.protobuf.Uid.List other) {
                if (other == datawave.ingest.protobuf.Uid.List.getDefaultInstance())
                    return this;
                if (other.hasIGNORE()) {
                    setIGNORE(other.getIGNORE());
                }
                if (other.hasCOUNT()) {
                    setCOUNT(other.getCOUNT());
                }
                if (!other.uID_.isEmpty()) {
                    if (uID_.isEmpty()) {
                        uID_ = other.uID_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureUIDIsMutable();
                        uID_.addAll(other.uID_);
                    }
                    onChanged();
                }
                if (!other.rEMOVEDUID_.isEmpty()) {
                    if (rEMOVEDUID_.isEmpty()) {
                        rEMOVEDUID_ = other.rEMOVEDUID_;
                        bitField0_ = (bitField0_ & ~0x00000008);
                    } else {
                        ensureREMOVEDUIDIsMutable();
                        rEMOVEDUID_.addAll(other.rEMOVEDUID_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }
            
            public final boolean isInitialized() {
                if (!hasIGNORE()) {
                    
                    return false;
                }
                if (!hasCOUNT()) {
                    
                    return false;
                }
                return true;
            }
            
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                datawave.ingest.protobuf.Uid.List parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (datawave.ingest.protobuf.Uid.List) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            
            private int bitField0_;
            
            // required bool IGNORE = 1;
            private boolean iGNORE_;
            
            /**
             * <code>required bool IGNORE = 1;</code>
             */
            public boolean hasIGNORE() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            
            /**
             * <code>required bool IGNORE = 1;</code>
             */
            public boolean getIGNORE() {
                return iGNORE_;
            }
            
            /**
             * <code>required bool IGNORE = 1;</code>
             */
            public Builder setIGNORE(boolean value) {
                bitField0_ |= 0x00000001;
                iGNORE_ = value;
                onChanged();
                return this;
            }
            
            /**
             * <code>required bool IGNORE = 1;</code>
             */
            public Builder clearIGNORE() {
                bitField0_ = (bitField0_ & ~0x00000001);
                iGNORE_ = false;
                onChanged();
                return this;
            }
            
            // required uint64 COUNT = 2;
            private long cOUNT_;
            
            /**
             * <code>required uint64 COUNT = 2;</code>
             */
            public boolean hasCOUNT() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            
            /**
             * <code>required uint64 COUNT = 2;</code>
             */
            public long getCOUNT() {
                return cOUNT_;
            }
            
            /**
             * <code>required uint64 COUNT = 2;</code>
             */
            public Builder setCOUNT(long value) {
                bitField0_ |= 0x00000002;
                cOUNT_ = value;
                onChanged();
                return this;
            }
            
            /**
             * <code>required uint64 COUNT = 2;</code>
             */
            public Builder clearCOUNT() {
                bitField0_ = (bitField0_ & ~0x00000002);
                cOUNT_ = 0L;
                onChanged();
                return this;
            }
            
            // repeated string UID = 3;
            private com.google.protobuf.LazyStringList uID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            
            private void ensureUIDIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    uID_ = new com.google.protobuf.LazyStringArrayList(uID_);
                    bitField0_ |= 0x00000004;
                }
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public java.util.List<java.lang.String> getUIDList() {
                return java.util.Collections.unmodifiableList(uID_);
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public int getUIDCount() {
                return uID_.size();
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public java.lang.String getUID(int index) {
                return uID_.get(index);
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public com.google.protobuf.ByteString getUIDBytes(int index) {
                return uID_.getByteString(index);
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public Builder setUID(int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUIDIsMutable();
                uID_.set(index, value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public Builder addUID(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUIDIsMutable();
                uID_.add(value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public Builder addAllUID(java.lang.Iterable<java.lang.String> values) {
                ensureUIDIsMutable();
                super.addAll(values, uID_);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public Builder clearUID() {
                uID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string UID = 3;</code>
             */
            public Builder addUIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureUIDIsMutable();
                uID_.add(value);
                onChanged();
                return this;
            }
            
            // repeated string REMOVEDUID = 4;
            private com.google.protobuf.LazyStringList rEMOVEDUID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            
            private void ensureREMOVEDUIDIsMutable() {
                if (!((bitField0_ & 0x00000008) == 0x00000008)) {
                    rEMOVEDUID_ = new com.google.protobuf.LazyStringArrayList(rEMOVEDUID_);
                    bitField0_ |= 0x00000008;
                }
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public java.util.List<java.lang.String> getREMOVEDUIDList() {
                return java.util.Collections.unmodifiableList(rEMOVEDUID_);
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public int getREMOVEDUIDCount() {
                return rEMOVEDUID_.size();
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public java.lang.String getREMOVEDUID(int index) {
                return rEMOVEDUID_.get(index);
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public com.google.protobuf.ByteString getREMOVEDUIDBytes(int index) {
                return rEMOVEDUID_.getByteString(index);
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public Builder setREMOVEDUID(int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureREMOVEDUIDIsMutable();
                rEMOVEDUID_.set(index, value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public Builder addREMOVEDUID(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureREMOVEDUIDIsMutable();
                rEMOVEDUID_.add(value);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public Builder addAllREMOVEDUID(java.lang.Iterable<java.lang.String> values) {
                ensureREMOVEDUIDIsMutable();
                super.addAll(values, rEMOVEDUID_);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public Builder clearREMOVEDUID() {
                rEMOVEDUID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }
            
            /**
             * <code>repeated string REMOVEDUID = 4;</code>
             */
            public Builder addREMOVEDUIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureREMOVEDUIDIsMutable();
                rEMOVEDUID_.add(value);
                onChanged();
                return this;
            }
            
            // @@protoc_insertion_point(builder_scope:datawave.ingest.protobuf.List)
        }
        
        static {
            defaultInstance = new List(true);
            defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:datawave.ingest.protobuf.List)
    }
    
    private static com.google.protobuf.Descriptors.Descriptor internal_static_datawave_ingest_protobuf_List_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_datawave_ingest_protobuf_List_fieldAccessorTable;
    
    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }
    
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {"\n\tUid.proto\022\030datawave.ingest.protobuf\"F\n"
                        + "\004List\022\016\n\006IGNORE\030\001 \002(\010\022\r\n\005COUNT\030\002 \002(\004\022\013\n\003"
                        + "UID\030\003 \003(\t\022\022\n\nREMOVEDUID\030\004 \003(\tB\034\n\030datawav" + "e.ingest.protobufH\001"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_datawave_ingest_protobuf_List_descriptor = getDescriptor().getMessageTypes().get(0);
                internal_static_datawave_ingest_protobuf_List_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_datawave_ingest_protobuf_List_descriptor, new java.lang.String[] {"IGNORE", "COUNT", "UID", "REMOVEDUID",});
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {},
                        assigner);
    }
    
    // @@protoc_insertion_point(outer_class_scope)
}
