syntax = "proto3";

package datawave.webservice.query.metric;

option java_package = "datawave.webservice.query.metric";

import "exception_messages.proto";

message PageMetric {
	uint64 pagesize = 1;
	uint64 return_time = 2;
}

message QueryMetric {
	string query_type = 1;
	string user = 2;
	int64 create_date = 3;
	string query_id = 4;
	uint64 setup_time = 5;
	PageMetric page_times = 6;
}

message QueryMetricListResponse {
	uint64 operation_time_ms = 1;
	repeated string messages = 2;
	repeated datawave.webservice.query.exception.QueryExceptionType exceptions = 3;
	repeated QueryMetric result = 4;
	int32 num_results = 5;
}