syntax = "proto3";

package datawave.webservice.query;

option java_package = "datawave.webservice.query";

message QueryImpl {
	string query_logic_name = 1;
	string id = 2;
	string query_name = 3;
	string user_DN = 4;
	string query = 5;
	string query_visibility = 6;
	int64 begin_date = 7;
	int64 end_date = 8;
	string query_authorizations = 9;
	int64 expiration_date = 10;
	uint32 pagesize = 11;
	Parameter parameters = 12;
	
	message Parameter {
		string parameter_name = 1;
		string parameter_value = 2;
	}	
}
