spring:
  cloud:
    stream:
      rabbit:
        bindings:
          logAuditSink:
            consumer:
              autoBindDlq: true
          accumuloAuditSink:
            consumer:
              autoBindDlq: true
          dumpAuditSink:
            consumer:
              autoBindDlq: true
              bindQueue: false
      bindings:
        auditSource:
          destination: 'audit'
          producer:
            errorChannelEnabled: true
        logAuditSink:
          destination: 'audit'
          group: 'log'
        accumuloAuditSink:
          destination: 'audit'
          group: 'accumulo'
        dumpAuditSink:
          destination: 'audit'
          group: 'dump'
          consumer:
            concurrency: 5

audit:
  auditors:
    log:
      enabled: true
    accumulo:
      enabled: false

logging:
  level:
    datawave.microservice.audit: DEBUG
