# This is the main configuration file for Apache Accumulo. Available configuration properties can be
# found at https://accumulo.apache.org/docs/2.x/configuration/server-properties

## Sets location in HDFS where Accumulo will store data
instance.volumes=hdfs://hdfs-nn:9000/accumulo

## Sets location of Zookeepers
instance.zookeeper.host=zookeeper:2181

## Change secret before initialization. All Accumulo servers must have same secret
instance.secret=DEFAULT

## Set to false if 'accumulo-util build-native' fails
tserver.memory.maps.native.enabled=true
tserver.memory.maps.max=384M
tserver.cache.data.size=64M
tserver.cache.index.size=96M
tserver.total.mutation.queue.max=128M
tserver.sort.buffer.size=128M
tserver.walog.max.size=256M

## (optional) include additional property files for a resource group
## based on the ACCUMULO_RESOURCE_GROUP env var set in accumulo-service
#include=group-${env:ACCUMULO_RESOURCE_GROUP}.properties
#includeOptional=group-${env:ACCUMULO_RESOURCE_GROUP}.properties
