################################
## Accumulo client configuration
################################

## NOTE - All properties that have a default are set with it. Properties that
## are uncommented must be set by the user.

## Instance properties
## --------------
## Name of Accumulo instance to connect to
instance.name=my-instance-01

## Zookeeper connection information for Accumulo instance
instance.zookeepers=zookeeper:2181

## Zookeeper session timeout
#instance.zookeepers.timeout=30s


## Authentication properties
## --------------
## Authentication method (i.e password, kerberos, PasswordToken, KerberosToken, etc)
auth.type=password

## Accumulo principal/username for chosen authentication method
auth.principal=root

## Authentication token (ex. mypassword, /path/to/keytab)
auth.token=secret


## Batch Writer properties
## --------------
## The durability of writes to tables includes ensuring that mutations written by clients are persisted in the write-ahead log and that files written during a compaction are persisted to disk successfully. This property only configures the durability used to write to the write-ahead log. Legal values are: none, which skips the write-ahead log; log, which sends the data to the write-ahead log, but does nothing to make it durable; flush, which pushes data out of the JVM (likely to page cache); and sync, which ensures that each mutation is written to the physical disk. To configure the durability of files written during minor and major compactions, set the Hadoop property "dfs.datanode.synconclose" to "true". This will ensure that the blocks of the files in HDFS are written to the physical disk as the compaction output files are written (Note that this may only apply to replicated files in HDFS).  Setting this property will change the durability for the BatchWriter session. A value of "default" will use the table's durability setting.
#batch.writer.durability=default

## Max amount of time (in seconds) to hold data in memory before flushing it
#batch.writer.latency.max=120s

## Max memory (in bytes) to batch before writing
#batch.writer.memory.max=50M

## Maximum number of threads to use for writing data to tablet servers.
#batch.writer.threads.max=3

## Max amount of time (in seconds) an unresponsive server will be re-tried. An exception is thrown when this timeout is exceeded. Set to zero for no timeout.
#batch.writer.timeout.max=0


## Batch Scanner properties
## --------------
## Number of concurrent query threads to spawn for querying
#batch.scanner.num.query.threads=3


## Scanner properties
## --------------
## Number of key/value pairs that will be fetched at time from tablet server
#scanner.batch.size=1000


## SSL properties
## --------------
## Enable SSL for client RPC
#ssl.enabled=false

## Password used to encrypt keystore
#ssl.keystore.password=

## Path to SSL keystore file
#ssl.keystore.path=

## Type of SSL keystore
#ssl.keystore.type=jks

## Password used to encrypt truststore
#ssl.truststore.password=

## Path to SSL truststore file
#ssl.truststore.path=

## Type of SSL truststore
#ssl.truststore.type=jks

## Use JSSE system properties to configure SSL
#ssl.use.jsse=false


## SASL properties
## --------------
## Enable SASL for client RPC
#sasl.enabled=false

## Kerberos principal/primary that Accumulo servers use to login
#sasl.kerberos.server.primary=accumulo

## SASL quality of protection. Valid values are 'auth', 'auth-int', and 'auth-conf'
#sasl.qop=auth


## Tracing properties
## --------------
