<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>gov.nsa.datawave.microservice</groupId>
        <artifactId>datawave-microservice-service-parent</artifactId>
        <!--TODO check this version against integration-->
        <version>5.0.11</version>
        <relativePath>../../../microservice-service-parent/pom.xml</relativePath>
    </parent>

    <artifactId>annotation-cache-service</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <description>DATAWAVE Annotation Cache Microservice</description>
    <!-- TODO All the other boilerplate stuff-->

    <properties>
        <start-class>datawave.microservice.annotationCache.AnnotationCacheService</start-class>
        <!--TODO check these versions against integration-->
        <version.datawave>7.38.1</version.datawave>
        <version.datawave.annotation-cache-api>1.0.0-SNAPSHOT</version.datawave.annotation-cache-api>
        <version.datawave.starter>4.0.7</version.datawave.starter>
        <version.hazelcast.service>4.0.5-SNAPSHOT</version.hazelcast.service>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>gov.nsa.datawave.core</groupId>
                <artifactId>datawave-core-annotation</artifactId>
                <version>${version.datawave}</version>
                <exclusions>
                    <exclusion>
                        <groupId>*</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>gov.nsa.datawave.microservice</groupId>
                <artifactId>hazelcast-service</artifactId>
                <version>${version.hazelcast.service}</version>
            </dependency>
            <dependency>
                <groupId>gov.nsa.datawave.microservice</groupId>
                <artifactId>spring-boot-starter-datawave</artifactId>
                <version>${version.datawave.starter}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.jboss.spec.javax.annotation</groupId>
                        <artifactId>jboss-annotations-api_1.3_spec</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>gov.nsa.datawave.core</groupId>
            <artifactId>datawave-core-annotation</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>annotation-cache-api</artifactId>
            <version>${version.datawave.annotation-cache-api}</version>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>hazelcast-service</artifactId>
        </dependency>
        <dependency>
            <groupId>gov.nsa.datawave.microservice</groupId>
            <artifactId>spring-boot-starter-datawave</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.github.git-commit-id</groupId>
                <artifactId>git-commit-id-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>docker</id>
            <activation>
                <property>
                    <name>microservice-docker</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.eclipse.jkube</groupId>
                        <artifactId>kubernetes-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
