// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TermWeight.proto

package datawave.ingest.protobuf;

public final class TermWeight {
    private TermWeight() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface InfoOrBuilder extends
                    // @@protoc_insertion_point(interface_extends:datawave.ingest.protobuf.Info)
                    com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated uint32 termOffset = 3;</code>
         *
         * @return A list containing the termOffset.
         */
        java.util.List<Integer> getTermOffsetList();

        /**
         * <code>repeated uint32 termOffset = 3;</code>
         *
         * @return The count of termOffset.
         */
        int getTermOffsetCount();

        /**
         * <code>repeated uint32 termOffset = 3;</code>
         *
         * @param index
         *            The index of the element to return.
         * @return The termOffset at the given index.
         */
        int getTermOffset(int index);

        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         *
         * @return A list containing the prevSkips.
         */
        java.util.List<Integer> getPrevSkipsList();

        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         *
         * @return The count of prevSkips.
         */
        int getPrevSkipsCount();

        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         *
         * @param index
         *            The index of the element to return.
         * @return The prevSkips at the given index.
         */
        int getPrevSkips(int index);

        /**
         * <code>repeated uint32 score = 5;</code>
         *
         * @return A list containing the score.
         */
        java.util.List<Integer> getScoreList();

        /**
         * <code>repeated uint32 score = 5;</code>
         *
         * @return The count of score.
         */
        int getScoreCount();

        /**
         * <code>repeated uint32 score = 5;</code>
         *
         * @param index
         *            The index of the element to return.
         * @return The score at the given index.
         */
        int getScore(int index);

        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         *
         * @return Whether the zeroOffsetMatch field is set.
         */
        boolean hasZeroOffsetMatch();

        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         *
         * @return The zeroOffsetMatch.
         */
        boolean getZeroOffsetMatch();
    }

    /**
     * Protobuf type {@code datawave.ingest.protobuf.Info}
     */
    public static final class Info extends com.google.protobuf.GeneratedMessageV3 implements
                    // @@protoc_insertion_point(message_implements:datawave.ingest.protobuf.Info)
                    InfoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Info.newBuilder() to construct.
        private Info(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Info() {
            termOffset_ = emptyIntList();
            prevSkips_ = emptyIntList();
            score_ = emptyIntList();
            zeroOffsetMatch_ = true;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(UnusedPrivateParameter unused) {
            return new Info();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Info(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 24: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                termOffset_ = newIntList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            termOffset_.addInt(input.readUInt32());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                                termOffset_ = newIntList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                termOffset_.addInt(input.readUInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 32: {
                            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                                prevSkips_ = newIntList();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            prevSkips_.addInt(input.readUInt32());
                            break;
                        }
                        case 34: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                                prevSkips_ = newIntList();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                prevSkips_.addInt(input.readUInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 40: {
                            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                                score_ = newIntList();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            score_.addInt(input.readUInt32());
                            break;
                        }
                        case 42: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
                                score_ = newIntList();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                score_.addInt(input.readUInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 48: {
                            bitField0_ |= 0x00000001;
                            zeroOffsetMatch_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    termOffset_.makeImmutable(); // C
                }
                if (((mutable_bitField0_ & 0x00000002) != 0)) {
                    prevSkips_.makeImmutable(); // C
                }
                if (((mutable_bitField0_ & 0x00000004) != 0)) {
                    score_.makeImmutable(); // C
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return TermWeight.internal_static_datawave_ingest_protobuf_Info_descriptor;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return TermWeight.internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable.ensureFieldAccessorsInitialized(Info.class, Builder.class);
        }

        private int bitField0_;
        public static final int TERMOFFSET_FIELD_NUMBER = 3;
        private com.google.protobuf.Internal.IntList termOffset_;

        /**
         * <code>repeated uint32 termOffset = 3;</code>
         *
         * @return A list containing the termOffset.
         */
        @Override
        public java.util.List<Integer> getTermOffsetList() {
            return termOffset_;
        }

        /**
         * <code>repeated uint32 termOffset = 3;</code>
         *
         * @return The count of termOffset.
         */
        public int getTermOffsetCount() {
            return termOffset_.size();
        }

        /**
         * <code>repeated uint32 termOffset = 3;</code>
         *
         * @param index
         *            The index of the element to return.
         * @return The termOffset at the given index.
         */
        public int getTermOffset(int index) {
            return termOffset_.getInt(index);
        }

        public static final int PREVSKIPS_FIELD_NUMBER = 4;
        private com.google.protobuf.Internal.IntList prevSkips_;

        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         *
         * @return A list containing the prevSkips.
         */
        @Override
        public java.util.List<Integer> getPrevSkipsList() {
            return prevSkips_;
        }

        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         *
         * @return The count of prevSkips.
         */
        public int getPrevSkipsCount() {
            return prevSkips_.size();
        }

        /**
         * <code>repeated uint32 prevSkips = 4;</code>
         *
         * @param index
         *            The index of the element to return.
         * @return The prevSkips at the given index.
         */
        public int getPrevSkips(int index) {
            return prevSkips_.getInt(index);
        }

        public static final int SCORE_FIELD_NUMBER = 5;
        private com.google.protobuf.Internal.IntList score_;

        /**
         * <code>repeated uint32 score = 5;</code>
         *
         * @return A list containing the score.
         */
        @Override
        public java.util.List<Integer> getScoreList() {
            return score_;
        }

        /**
         * <code>repeated uint32 score = 5;</code>
         *
         * @return The count of score.
         */
        public int getScoreCount() {
            return score_.size();
        }

        /**
         * <code>repeated uint32 score = 5;</code>
         *
         * @param index
         *            The index of the element to return.
         * @return The score at the given index.
         */
        public int getScore(int index) {
            return score_.getInt(index);
        }

        public static final int ZEROOFFSETMATCH_FIELD_NUMBER = 6;
        private boolean zeroOffsetMatch_;

        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         *
         * @return Whether the zeroOffsetMatch field is set.
         */
        @Override
        public boolean hasZeroOffsetMatch() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
         *
         * @return The zeroOffsetMatch.
         */
        @Override
        public boolean getZeroOffsetMatch() {
            return zeroOffsetMatch_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            for (int i = 0; i < termOffset_.size(); i++) {
                output.writeUInt32(3, termOffset_.getInt(i));
            }
            for (int i = 0; i < prevSkips_.size(); i++) {
                output.writeUInt32(4, prevSkips_.getInt(i));
            }
            for (int i = 0; i < score_.size(); i++) {
                output.writeUInt32(5, score_.getInt(i));
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeBool(6, zeroOffsetMatch_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < termOffset_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(termOffset_.getInt(i));
                }
                size += dataSize;
                size += 1 * getTermOffsetList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < prevSkips_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(prevSkips_.getInt(i));
                }
                size += dataSize;
                size += 1 * getPrevSkipsList().size();
            }
            {
                int dataSize = 0;
                for (int i = 0; i < score_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(score_.getInt(i));
                }
                size += dataSize;
                size += 1 * getScoreList().size();
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream.computeBoolSize(6, zeroOffsetMatch_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Info)) {
                return super.equals(obj);
            }
            Info other = (Info) obj;

            if (!getTermOffsetList().equals(other.getTermOffsetList()))
                return false;
            if (!getPrevSkipsList().equals(other.getPrevSkipsList()))
                return false;
            if (!getScoreList().equals(other.getScoreList()))
                return false;
            if (hasZeroOffsetMatch() != other.hasZeroOffsetMatch())
                return false;
            if (hasZeroOffsetMatch()) {
                if (getZeroOffsetMatch() != other.getZeroOffsetMatch())
                    return false;
            }
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getTermOffsetCount() > 0) {
                hash = (37 * hash) + TERMOFFSET_FIELD_NUMBER;
                hash = (53 * hash) + getTermOffsetList().hashCode();
            }
            if (getPrevSkipsCount() > 0) {
                hash = (37 * hash) + PREVSKIPS_FIELD_NUMBER;
                hash = (53 * hash) + getPrevSkipsList().hashCode();
            }
            if (getScoreCount() > 0) {
                hash = (37 * hash) + SCORE_FIELD_NUMBER;
                hash = (53 * hash) + getScoreList().hashCode();
            }
            if (hasZeroOffsetMatch()) {
                hash = (37 * hash) + ZEROOFFSETMATCH_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getZeroOffsetMatch());
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Info parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Info parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Info parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Info parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Info parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Info parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Info parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Info parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Info parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static Info parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Info parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Info parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Info prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code datawave.ingest.protobuf.Info}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                        // @@protoc_insertion_point(builder_implements:datawave.ingest.protobuf.Info)
                        InfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return TermWeight.internal_static_datawave_ingest_protobuf_Info_descriptor;
            }

            @Override
            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return TermWeight.internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable.ensureFieldAccessorsInitialized(Info.class, Builder.class);
            }

            // Construct using datawave.ingest.protobuf.TermWeight.Info.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
            }

            @Override
            public Builder clear() {
                super.clear();
                termOffset_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000001);
                prevSkips_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000002);
                score_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000004);
                zeroOffsetMatch_ = true;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return TermWeight.internal_static_datawave_ingest_protobuf_Info_descriptor;
            }

            @Override
            public Info getDefaultInstanceForType() {
                return Info.getDefaultInstance();
            }

            @Override
            public Info build() {
                Info result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Info buildPartial() {
                Info result = new Info(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((bitField0_ & 0x00000001) != 0)) {
                    termOffset_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.termOffset_ = termOffset_;
                if (((bitField0_ & 0x00000002) != 0)) {
                    prevSkips_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.prevSkips_ = prevSkips_;
                if (((bitField0_ & 0x00000004) != 0)) {
                    score_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.score_ = score_;
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.zeroOffsetMatch_ = zeroOffsetMatch_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Info) {
                    return mergeFrom((Info) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Info other) {
                if (other == Info.getDefaultInstance())
                    return this;
                if (!other.termOffset_.isEmpty()) {
                    if (termOffset_.isEmpty()) {
                        termOffset_ = other.termOffset_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureTermOffsetIsMutable();
                        termOffset_.addAll(other.termOffset_);
                    }
                    onChanged();
                }
                if (!other.prevSkips_.isEmpty()) {
                    if (prevSkips_.isEmpty()) {
                        prevSkips_ = other.prevSkips_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensurePrevSkipsIsMutable();
                        prevSkips_.addAll(other.prevSkips_);
                    }
                    onChanged();
                }
                if (!other.score_.isEmpty()) {
                    if (score_.isEmpty()) {
                        score_ = other.score_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureScoreIsMutable();
                        score_.addAll(other.score_);
                    }
                    onChanged();
                }
                if (other.hasZeroOffsetMatch()) {
                    setZeroOffsetMatch(other.getZeroOffsetMatch());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws java.io.IOException {
                Info parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Info) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.Internal.IntList termOffset_ = emptyIntList();

            private void ensureTermOffsetIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    termOffset_ = mutableCopy(termOffset_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @return A list containing the termOffset.
             */
            public java.util.List<Integer> getTermOffsetList() {
                return ((bitField0_ & 0x00000001) != 0) ? java.util.Collections.unmodifiableList(termOffset_) : termOffset_;
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @return The count of termOffset.
             */
            public int getTermOffsetCount() {
                return termOffset_.size();
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @param index
             *            The index of the element to return.
             * @return The termOffset at the given index.
             */
            public int getTermOffset(int index) {
                return termOffset_.getInt(index);
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @param index
             *            The index to set the value at.
             * @param value
             *            The termOffset to set.
             * @return This builder for chaining.
             */
            public Builder setTermOffset(int index, int value) {
                ensureTermOffsetIsMutable();
                termOffset_.setInt(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @param value
             *            The termOffset to add.
             * @return This builder for chaining.
             */
            public Builder addTermOffset(int value) {
                ensureTermOffsetIsMutable();
                termOffset_.addInt(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @param values
             *            The termOffset to add.
             * @return This builder for chaining.
             */
            public Builder addAllTermOffset(Iterable<? extends Integer> values) {
                ensureTermOffsetIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, termOffset_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 termOffset = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTermOffset() {
                termOffset_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.IntList prevSkips_ = emptyIntList();

            private void ensurePrevSkipsIsMutable() {
                if (!((bitField0_ & 0x00000002) != 0)) {
                    prevSkips_ = mutableCopy(prevSkips_);
                    bitField0_ |= 0x00000002;
                }
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @return A list containing the prevSkips.
             */
            public java.util.List<Integer> getPrevSkipsList() {
                return ((bitField0_ & 0x00000002) != 0) ? java.util.Collections.unmodifiableList(prevSkips_) : prevSkips_;
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @return The count of prevSkips.
             */
            public int getPrevSkipsCount() {
                return prevSkips_.size();
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @param index
             *            The index of the element to return.
             * @return The prevSkips at the given index.
             */
            public int getPrevSkips(int index) {
                return prevSkips_.getInt(index);
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @param index
             *            The index to set the value at.
             * @param value
             *            The prevSkips to set.
             * @return This builder for chaining.
             */
            public Builder setPrevSkips(int index, int value) {
                ensurePrevSkipsIsMutable();
                prevSkips_.setInt(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @param value
             *            The prevSkips to add.
             * @return This builder for chaining.
             */
            public Builder addPrevSkips(int value) {
                ensurePrevSkipsIsMutable();
                prevSkips_.addInt(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @param values
             *            The prevSkips to add.
             * @return This builder for chaining.
             */
            public Builder addAllPrevSkips(Iterable<? extends Integer> values) {
                ensurePrevSkipsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, prevSkips_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 prevSkips = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPrevSkips() {
                prevSkips_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            private com.google.protobuf.Internal.IntList score_ = emptyIntList();

            private void ensureScoreIsMutable() {
                if (!((bitField0_ & 0x00000004) != 0)) {
                    score_ = mutableCopy(score_);
                    bitField0_ |= 0x00000004;
                }
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @return A list containing the score.
             */
            public java.util.List<Integer> getScoreList() {
                return ((bitField0_ & 0x00000004) != 0) ? java.util.Collections.unmodifiableList(score_) : score_;
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @return The count of score.
             */
            public int getScoreCount() {
                return score_.size();
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @param index
             *            The index of the element to return.
             * @return The score at the given index.
             */
            public int getScore(int index) {
                return score_.getInt(index);
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @param index
             *            The index to set the value at.
             * @param value
             *            The score to set.
             * @return This builder for chaining.
             */
            public Builder setScore(int index, int value) {
                ensureScoreIsMutable();
                score_.setInt(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @param value
             *            The score to add.
             * @return This builder for chaining.
             */
            public Builder addScore(int value) {
                ensureScoreIsMutable();
                score_.addInt(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @param values
             *            The score to add.
             * @return This builder for chaining.
             */
            public Builder addAllScore(Iterable<? extends Integer> values) {
                ensureScoreIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, score_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated uint32 score = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearScore() {
                score_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            private boolean zeroOffsetMatch_ = true;

            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             *
             * @return Whether the zeroOffsetMatch field is set.
             */
            @Override
            public boolean hasZeroOffsetMatch() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             *
             * @return The zeroOffsetMatch.
             */
            @Override
            public boolean getZeroOffsetMatch() {
                return zeroOffsetMatch_;
            }

            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             *
             * @param value
             *            The zeroOffsetMatch to set.
             * @return This builder for chaining.
             */
            public Builder setZeroOffsetMatch(boolean value) {
                bitField0_ |= 0x00000008;
                zeroOffsetMatch_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bool zeroOffsetMatch = 6 [default = true];</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearZeroOffsetMatch() {
                bitField0_ = (bitField0_ & ~0x00000008);
                zeroOffsetMatch_ = true;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:datawave.ingest.protobuf.Info)
        }

        // @@protoc_insertion_point(class_scope:datawave.ingest.protobuf.Info)
        private static final Info DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new Info();
        }

        public static Info getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @Deprecated
        public static final com.google.protobuf.Parser<Info> PARSER = new com.google.protobuf.AbstractParser<Info>() {
            @Override
            public Info parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                return new Info(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Info> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Info> getParserForType() {
            return PARSER;
        }

        @Override
        public Info getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_datawave_ingest_protobuf_Info_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        String[] descriptorData = {
                "\n\020TermWeight.proto\022\030datawave.ingest.prot" + "obuf\"[\n\004Info\022\022\n\ntermOffset\030\003 \003(\r\022\021\n\tprev"
                                + "Skips\030\004 \003(\r\022\r\n\005score\030\005 \003(\r\022\035\n\017zeroOffset"
                                + "Match\030\006 \001(\010:\004trueB\034\n\030datawave.ingest.pro" + "tobufH\001"};
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_datawave_ingest_protobuf_Info_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_datawave_ingest_protobuf_Info_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                        internal_static_datawave_ingest_protobuf_Info_descriptor, new String[] {"TermOffset", "PrevSkips", "Score", "ZeroOffsetMatch",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
