syntax = "proto3";

package datawave.annotation.protobuf.v1;

option java_package = "datawave.annotation.protobuf.v1";
option java_multiple_files = true;

// segment boundary types
message All { } // annotations on the entire object
message Point { sint32 x = 1; sint32 y = 2; string label = 3; } // annotations on a point
message TimeSpanSeconds { sfixed32 startSeconds = 1; sfixed32 endSeconds = 2; } // annotations on a span of time
message TextSpanChars { int64 startCharacter = 1; int64 endCharacter = 2; } // annotations on a span of characters

// segment value, e.g. a label, confidence and source
message SegmentValue {
    string value = 1; // e.g., label
    double score = 2; // e.g., confidence
    map<string,string> extension = 3; // type-specific data
}

message SegmentBoundary {
    string boundaryType = 1; // currently 'all', 'points', 'times', 'characters', should match the name of the field where data is stored.
    reserved 2 to 19; // for future growth.
    optional All all = 20; // the entire object.
    optional TimeSpanSeconds timeSpan = 21; // a start and end time span.
    optional TextSpanChars characterSpan = 22; // a start and end character.
    repeated Point points = 23; // zero or more points or polygons.
    reserved 24 to 50; // add future segment types here.
}

message Segment {
    string segmentId = 1; // the segment id in this annotation.
    SegmentBoundary boundary = 2; // boundary for this segment.
    repeated SegmentValue values = 3;  // Multiple values associated with this segment.
    reserved 4 to 49; // for future growth.
    map<string, string> metadata = 50;  // arbitrary, optional segment metadata
}

message Annotation {
    string shard = 1; // the shard of the record this annotation addresses
    string dataType = 2; // the datatype of the record this annotation addresses
    string uid = 3; // the internal id of the record this annotation addresses
    string annotationType = 4; // the type of this annotation
    string annotationId = 5; // the hash that identifies this annotation
    string analyticHash = 6; // the analytic hash that identifies this annotation's source
    optional AnnotationSource source = 7; // the source details for this annotation.
    string documentId = 8; // the external identifier for this annotations source document.
    reserved 9 to 19; // for future growth.
    repeated Segment segments = 20; // segment data
    reserved 21 to 49; // for future growth.
    map<string, string> metadata = 50;
}

message AnnotationSource {
    string analyticHash = 1; // the analytic hash for this source
    string engine = 2; // a string identifying the engine that produce the annotation
    string model = 3; // a string identifying the model that produced the annotation
    string sourceLabel = 4; // a label for the engine/model/configuration combo
    reserved 5 to 49; // for future growth.
    map<string, string> configuration = 50; // key value pairs identifying the configuration for the source.
}

// Embeddable list/element wrappers that are JSON-friendly.
message SegmentList {
    repeated Segment segments = 1;
    string nextPageToken = 2;
}

message AnnotationList {
    repeated Annotation annotations = 1;
    string nextPageToken = 2;
}