// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SegmentV1.proto

package datawave.annotation.protobuf.v1;

public interface AnnotationListOrBuilder extends
                // @@protoc_insertion_point(interface_extends:segments.v1.AnnotationList)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .segments.v1.Annotation annotations = 1;</code>
     */
    java.util.List<datawave.annotation.protobuf.v1.Annotation> getAnnotationsList();

    /**
     * <code>repeated .segments.v1.Annotation annotations = 1;</code>
     */
    datawave.annotation.protobuf.v1.Annotation getAnnotations(int index);

    /**
     * <code>repeated .segments.v1.Annotation annotations = 1;</code>
     */
    int getAnnotationsCount();

    /**
     * <code>repeated .segments.v1.Annotation annotations = 1;</code>
     */
    java.util.List<? extends datawave.annotation.protobuf.v1.AnnotationOrBuilder> getAnnotationsOrBuilderList();

    /**
     * <code>repeated .segments.v1.Annotation annotations = 1;</code>
     */
    datawave.annotation.protobuf.v1.AnnotationOrBuilder getAnnotationsOrBuilder(int index);

    /**
     * <code>string nextPageToken = 2;</code>
     *
     * @return The nextPageToken.
     */
    java.lang.String getNextPageToken();

    /**
     * <code>string nextPageToken = 2;</code>
     *
     * @return The bytes for nextPageToken.
     */
    com.google.protobuf.ByteString getNextPageTokenBytes();
}
