// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

/**
 * Protobuf type {@code datawave.annotation.protobuf.v1.Annotation}
 */
public final class Annotation extends com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.v1.Annotation)
                AnnotationOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Annotation.newBuilder() to construct.
    private Annotation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Annotation() {
        shard_ = "";
        dataType_ = "";
        uid_ = "";
        annotationId_ = "";
        documentId_ = "";
        annotationType_ = "";
        analyticSourceHash_ = "";
        segments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new Annotation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Annotation_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
            case 50:
                return internalGetMetadata();
            default:
                throw new RuntimeException("Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Annotation_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.Annotation.class,
                                        datawave.annotation.protobuf.v1.Annotation.Builder.class);
    }

    private int bitField0_;
    public static final int SHARD_FIELD_NUMBER = 1;
    private volatile java.lang.Object shard_;

    /**
     * <pre>
     * the shard of the record this annotation addresses
     * </pre>
     *
     * <code>string shard = 1;</code>
     *
     * @return The shard.
     */
    @java.lang.Override
    public java.lang.String getShard() {
        java.lang.Object ref = shard_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            shard_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the shard of the record this annotation addresses
     * </pre>
     *
     * <code>string shard = 1;</code>
     *
     * @return The bytes for shard.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getShardBytes() {
        java.lang.Object ref = shard_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            shard_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int DATATYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object dataType_;

    /**
     * <pre>
     * the datatype of the record this annotation addresses
     * </pre>
     *
     * <code>string dataType = 2;</code>
     *
     * @return The dataType.
     */
    @java.lang.Override
    public java.lang.String getDataType() {
        java.lang.Object ref = dataType_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dataType_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the datatype of the record this annotation addresses
     * </pre>
     *
     * <code>string dataType = 2;</code>
     *
     * @return The bytes for dataType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataTypeBytes() {
        java.lang.Object ref = dataType_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            dataType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int UID_FIELD_NUMBER = 3;
    private volatile java.lang.Object uid_;

    /**
     * <pre>
     * the internal id of the record this annotation addresses
     * </pre>
     *
     * <code>string uid = 3;</code>
     *
     * @return The uid.
     */
    @java.lang.Override
    public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uid_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the internal id of the record this annotation addresses
     * </pre>
     *
     * <code>string uid = 3;</code>
     *
     * @return The bytes for uid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            uid_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ANNOTATIONID_FIELD_NUMBER = 4;
    private volatile java.lang.Object annotationId_;

    /**
     * <pre>
     * the hash that identifies this annotation
     * </pre>
     *
     * <code>string annotationId = 4;</code>
     *
     * @return The annotationId.
     */
    @java.lang.Override
    public java.lang.String getAnnotationId() {
        java.lang.Object ref = annotationId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            annotationId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the hash that identifies this annotation
     * </pre>
     *
     * <code>string annotationId = 4;</code>
     *
     * @return The bytes for annotationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAnnotationIdBytes() {
        java.lang.Object ref = annotationId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            annotationId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int DOCUMENTID_FIELD_NUMBER = 5;
    private volatile java.lang.Object documentId_;

    /**
     * <pre>
     * the external identifier for this annotations source document.
     * </pre>
     *
     * <code>string documentId = 5;</code>
     *
     * @return The documentId.
     */
    @java.lang.Override
    public java.lang.String getDocumentId() {
        java.lang.Object ref = documentId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            documentId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the external identifier for this annotations source document.
     * </pre>
     *
     * <code>string documentId = 5;</code>
     *
     * @return The bytes for documentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDocumentIdBytes() {
        java.lang.Object ref = documentId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            documentId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ANNOTATIONTYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object annotationType_;

    /**
     * <pre>
     * the type of this annotation
     * </pre>
     *
     * <code>string annotationType = 6;</code>
     *
     * @return The annotationType.
     */
    @java.lang.Override
    public java.lang.String getAnnotationType() {
        java.lang.Object ref = annotationType_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            annotationType_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the type of this annotation
     * </pre>
     *
     * <code>string annotationType = 6;</code>
     *
     * @return The bytes for annotationType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAnnotationTypeBytes() {
        java.lang.Object ref = annotationType_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            annotationType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ANALYTICSOURCEHASH_FIELD_NUMBER = 7;
    private volatile java.lang.Object analyticSourceHash_;

    /**
     * <pre>
     * the analytic hash that identifies this annotation's source
     * </pre>
     *
     * <code>string analyticSourceHash = 7;</code>
     *
     * @return The analyticSourceHash.
     */
    @java.lang.Override
    public java.lang.String getAnalyticSourceHash() {
        java.lang.Object ref = analyticSourceHash_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            analyticSourceHash_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the analytic hash that identifies this annotation's source
     * </pre>
     *
     * <code>string analyticSourceHash = 7;</code>
     *
     * @return The bytes for analyticSourceHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAnalyticSourceHashBytes() {
        java.lang.Object ref = analyticSourceHash_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            analyticSourceHash_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SOURCE_FIELD_NUMBER = 8;
    private datawave.annotation.protobuf.v1.AnnotationSource source_;

    /**
     * <pre>
     * the source details for this annotation.
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
     *
     * @return Whether the source field is set.
     */
    @java.lang.Override
    public boolean hasSource() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * the source details for this annotation.
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
     *
     * @return The source.
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.AnnotationSource getSource() {
        return source_ == null ? datawave.annotation.protobuf.v1.AnnotationSource.getDefaultInstance() : source_;
    }

    /**
     * <pre>
     * the source details for this annotation.
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.AnnotationSourceOrBuilder getSourceOrBuilder() {
        return source_ == null ? datawave.annotation.protobuf.v1.AnnotationSource.getDefaultInstance() : source_;
    }

    public static final int SEGMENTS_FIELD_NUMBER = 20;
    private java.util.List<datawave.annotation.protobuf.v1.Segment> segments_;

    /**
     * <pre>
     * segment data
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
     */
    @java.lang.Override
    public java.util.List<datawave.annotation.protobuf.v1.Segment> getSegmentsList() {
        return segments_;
    }

    /**
     * <pre>
     * segment data
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
     */
    @java.lang.Override
    public java.util.List<? extends datawave.annotation.protobuf.v1.SegmentOrBuilder> getSegmentsOrBuilderList() {
        return segments_;
    }

    /**
     * <pre>
     * segment data
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
     */
    @java.lang.Override
    public int getSegmentsCount() {
        return segments_.size();
    }

    /**
     * <pre>
     * segment data
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.Segment getSegments(int index) {
        return segments_.get(index);
    }

    /**
     * <pre>
     * segment data
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.SegmentOrBuilder getSegmentsOrBuilder(int index) {
        return segments_.get(index);
    }

    public static final int METADATA_FIELD_NUMBER = 50;

    private static final class MetadataDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<java.lang.String,java.lang.String> defaultEntry = com.google.protobuf.MapEntry.<java.lang.String,java.lang.String> newDefaultInstance(
                        datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Annotation_MetadataEntry_descriptor,
                        com.google.protobuf.WireFormat.FieldType.STRING, "", com.google.protobuf.WireFormat.FieldType.STRING, "");
    }

    private com.google.protobuf.MapField<java.lang.String,java.lang.String> metadata_;

    private com.google.protobuf.MapField<java.lang.String,java.lang.String> internalGetMetadata() {
        if (metadata_ == null) {
            return com.google.protobuf.MapField.emptyMapField(MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
    }

    public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */

    @java.lang.Override
    public boolean containsMetadata(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetMetadata().getMap().containsKey(key);
    }

    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
        return getMetadataMap();
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String,java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrDefault(java.lang.String key, java.lang.String defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrThrow(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!getShardBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, shard_);
        }
        if (!getDataTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataType_);
        }
        if (!getUidBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uid_);
        }
        if (!getAnnotationIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, annotationId_);
        }
        if (!getDocumentIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, documentId_);
        }
        if (!getAnnotationTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, annotationType_);
        }
        if (!getAnalyticSourceHashBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, analyticSourceHash_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(8, getSource());
        }
        for (int i = 0; i < segments_.size(); i++) {
            output.writeMessage(20, segments_.get(i));
        }
        com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output, internalGetMetadata(), MetadataDefaultEntryHolder.defaultEntry, 50);
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getShardBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, shard_);
        }
        if (!getDataTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataType_);
        }
        if (!getUidBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uid_);
        }
        if (!getAnnotationIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, annotationId_);
        }
        if (!getDocumentIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, documentId_);
        }
        if (!getAnnotationTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, annotationType_);
        }
        if (!getAnalyticSourceHashBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, analyticSourceHash_);
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(8, getSource());
        }
        for (int i = 0; i < segments_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(20, segments_.get(i));
        }
        for (java.util.Map.Entry<java.lang.String,java.lang.String> entry : internalGetMetadata().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String,java.lang.String> metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
                            .setKey(entry.getKey()).setValue(entry.getValue()).build();
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(50, metadata__);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof datawave.annotation.protobuf.v1.Annotation)) {
            return super.equals(obj);
        }
        datawave.annotation.protobuf.v1.Annotation other = (datawave.annotation.protobuf.v1.Annotation) obj;

        if (!getShard().equals(other.getShard()))
            return false;
        if (!getDataType().equals(other.getDataType()))
            return false;
        if (!getUid().equals(other.getUid()))
            return false;
        if (!getAnnotationId().equals(other.getAnnotationId()))
            return false;
        if (!getDocumentId().equals(other.getDocumentId()))
            return false;
        if (!getAnnotationType().equals(other.getAnnotationType()))
            return false;
        if (!getAnalyticSourceHash().equals(other.getAnalyticSourceHash()))
            return false;
        if (hasSource() != other.hasSource())
            return false;
        if (hasSource()) {
            if (!getSource().equals(other.getSource()))
                return false;
        }
        if (!getSegmentsList().equals(other.getSegmentsList()))
            return false;
        if (!internalGetMetadata().equals(other.internalGetMetadata()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SHARD_FIELD_NUMBER;
        hash = (53 * hash) + getShard().hashCode();
        hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
        hash = (53 * hash) + getDataType().hashCode();
        hash = (37 * hash) + UID_FIELD_NUMBER;
        hash = (53 * hash) + getUid().hashCode();
        hash = (37 * hash) + ANNOTATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getAnnotationId().hashCode();
        hash = (37 * hash) + DOCUMENTID_FIELD_NUMBER;
        hash = (53 * hash) + getDocumentId().hashCode();
        hash = (37 * hash) + ANNOTATIONTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getAnnotationType().hashCode();
        hash = (37 * hash) + ANALYTICSOURCEHASH_FIELD_NUMBER;
        hash = (53 * hash) + getAnalyticSourceHash().hashCode();
        if (hasSource()) {
            hash = (37 * hash) + SOURCE_FIELD_NUMBER;
            hash = (53 * hash) + getSource().hashCode();
        }
        if (getSegmentsCount() > 0) {
            hash = (37 * hash) + SEGMENTS_FIELD_NUMBER;
            hash = (53 * hash) + getSegmentsList().hashCode();
        }
        if (!internalGetMetadata().getMap().isEmpty()) {
            hash = (37 * hash) + METADATA_FIELD_NUMBER;
            hash = (53 * hash) + internalGetMetadata().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseDelimitedFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.Annotation parseFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(datawave.annotation.protobuf.v1.Annotation prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code datawave.annotation.protobuf.v1.Annotation}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.v1.Annotation)
                    datawave.annotation.protobuf.v1.AnnotationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Annotation_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 50:
                    return internalGetMetadata();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
            switch (number) {
                case 50:
                    return internalGetMutableMetadata();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Annotation_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.Annotation.class,
                                            datawave.annotation.protobuf.v1.Annotation.Builder.class);
        }

        // Construct using datawave.annotation.protobuf.v1.Annotation.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getSourceFieldBuilder();
                getSegmentsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            shard_ = "";

            dataType_ = "";

            uid_ = "";

            annotationId_ = "";

            documentId_ = "";

            annotationType_ = "";

            analyticSourceHash_ = "";

            if (sourceBuilder_ == null) {
                source_ = null;
            } else {
                sourceBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000001);
            if (segmentsBuilder_ == null) {
                segments_ = java.util.Collections.emptyList();
            } else {
                segments_ = null;
                segmentsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            internalGetMutableMetadata().clear();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Annotation_descriptor;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.Annotation getDefaultInstanceForType() {
            return datawave.annotation.protobuf.v1.Annotation.getDefaultInstance();
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.Annotation build() {
            datawave.annotation.protobuf.v1.Annotation result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.Annotation buildPartial() {
            datawave.annotation.protobuf.v1.Annotation result = new datawave.annotation.protobuf.v1.Annotation(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.shard_ = shard_;
            result.dataType_ = dataType_;
            result.uid_ = uid_;
            result.annotationId_ = annotationId_;
            result.documentId_ = documentId_;
            result.annotationType_ = annotationType_;
            result.analyticSourceHash_ = analyticSourceHash_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                if (sourceBuilder_ == null) {
                    result.source_ = source_;
                } else {
                    result.source_ = sourceBuilder_.build();
                }
                to_bitField0_ |= 0x00000001;
            }
            if (segmentsBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    segments_ = java.util.Collections.unmodifiableList(segments_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.segments_ = segments_;
            } else {
                result.segments_ = segmentsBuilder_.build();
            }
            result.metadata_ = internalGetMetadata();
            result.metadata_.makeImmutable();
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof datawave.annotation.protobuf.v1.Annotation) {
                return mergeFrom((datawave.annotation.protobuf.v1.Annotation) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(datawave.annotation.protobuf.v1.Annotation other) {
            if (other == datawave.annotation.protobuf.v1.Annotation.getDefaultInstance())
                return this;
            if (!other.getShard().isEmpty()) {
                shard_ = other.shard_;
                onChanged();
            }
            if (!other.getDataType().isEmpty()) {
                dataType_ = other.dataType_;
                onChanged();
            }
            if (!other.getUid().isEmpty()) {
                uid_ = other.uid_;
                onChanged();
            }
            if (!other.getAnnotationId().isEmpty()) {
                annotationId_ = other.annotationId_;
                onChanged();
            }
            if (!other.getDocumentId().isEmpty()) {
                documentId_ = other.documentId_;
                onChanged();
            }
            if (!other.getAnnotationType().isEmpty()) {
                annotationType_ = other.annotationType_;
                onChanged();
            }
            if (!other.getAnalyticSourceHash().isEmpty()) {
                analyticSourceHash_ = other.analyticSourceHash_;
                onChanged();
            }
            if (other.hasSource()) {
                mergeSource(other.getSource());
            }
            if (segmentsBuilder_ == null) {
                if (!other.segments_.isEmpty()) {
                    if (segments_.isEmpty()) {
                        segments_ = other.segments_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureSegmentsIsMutable();
                        segments_.addAll(other.segments_);
                    }
                    onChanged();
                }
            } else {
                if (!other.segments_.isEmpty()) {
                    if (segmentsBuilder_.isEmpty()) {
                        segmentsBuilder_.dispose();
                        segmentsBuilder_ = null;
                        segments_ = other.segments_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        segmentsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getSegmentsFieldBuilder() : null;
                    } else {
                        segmentsBuilder_.addAllMessages(other.segments_);
                    }
                }
            }
            internalGetMutableMetadata().mergeFrom(other.internalGetMetadata());
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            shard_ = input.readStringRequireUtf8();

                            break;
                        } // case 10
                        case 18: {
                            dataType_ = input.readStringRequireUtf8();

                            break;
                        } // case 18
                        case 26: {
                            uid_ = input.readStringRequireUtf8();

                            break;
                        } // case 26
                        case 34: {
                            annotationId_ = input.readStringRequireUtf8();

                            break;
                        } // case 34
                        case 42: {
                            documentId_ = input.readStringRequireUtf8();

                            break;
                        } // case 42
                        case 50: {
                            annotationType_ = input.readStringRequireUtf8();

                            break;
                        } // case 50
                        case 58: {
                            analyticSourceHash_ = input.readStringRequireUtf8();

                            break;
                        } // case 58
                        case 66: {
                            input.readMessage(getSourceFieldBuilder().getBuilder(), extensionRegistry);
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 66
                        case 162: {
                            datawave.annotation.protobuf.v1.Segment m = input.readMessage(datawave.annotation.protobuf.v1.Segment.parser(), extensionRegistry);
                            if (segmentsBuilder_ == null) {
                                ensureSegmentsIsMutable();
                                segments_.add(m);
                            } else {
                                segmentsBuilder_.addMessage(m);
                            }
                            break;
                        } // case 162
                        case 402: {
                            com.google.protobuf.MapEntry<java.lang.String,java.lang.String> metadata__ = input
                                            .readMessage(MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            internalGetMutableMetadata().getMutableMap().put(metadata__.getKey(), metadata__.getValue());
                            break;
                        } // case 402
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object shard_ = "";

        /**
         * <pre>
         * the shard of the record this annotation addresses
         * </pre>
         *
         * <code>string shard = 1;</code>
         *
         * @return The shard.
         */
        public java.lang.String getShard() {
            java.lang.Object ref = shard_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                shard_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the shard of the record this annotation addresses
         * </pre>
         *
         * <code>string shard = 1;</code>
         *
         * @return The bytes for shard.
         */
        public com.google.protobuf.ByteString getShardBytes() {
            java.lang.Object ref = shard_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                shard_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the shard of the record this annotation addresses
         * </pre>
         *
         * <code>string shard = 1;</code>
         *
         * @param value
         *            The shard to set.
         * @return This builder for chaining.
         */
        public Builder setShard(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            shard_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the shard of the record this annotation addresses
         * </pre>
         *
         * <code>string shard = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearShard() {

            shard_ = getDefaultInstance().getShard();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the shard of the record this annotation addresses
         * </pre>
         *
         * <code>string shard = 1;</code>
         *
         * @param value
         *            The bytes for shard to set.
         * @return This builder for chaining.
         */
        public Builder setShardBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            shard_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object dataType_ = "";

        /**
         * <pre>
         * the datatype of the record this annotation addresses
         * </pre>
         *
         * <code>string dataType = 2;</code>
         *
         * @return The dataType.
         */
        public java.lang.String getDataType() {
            java.lang.Object ref = dataType_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dataType_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the datatype of the record this annotation addresses
         * </pre>
         *
         * <code>string dataType = 2;</code>
         *
         * @return The bytes for dataType.
         */
        public com.google.protobuf.ByteString getDataTypeBytes() {
            java.lang.Object ref = dataType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                dataType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the datatype of the record this annotation addresses
         * </pre>
         *
         * <code>string dataType = 2;</code>
         *
         * @param value
         *            The dataType to set.
         * @return This builder for chaining.
         */
        public Builder setDataType(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            dataType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the datatype of the record this annotation addresses
         * </pre>
         *
         * <code>string dataType = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDataType() {

            dataType_ = getDefaultInstance().getDataType();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the datatype of the record this annotation addresses
         * </pre>
         *
         * <code>string dataType = 2;</code>
         *
         * @param value
         *            The bytes for dataType to set.
         * @return This builder for chaining.
         */
        public Builder setDataTypeBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            dataType_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object uid_ = "";

        /**
         * <pre>
         * the internal id of the record this annotation addresses
         * </pre>
         *
         * <code>string uid = 3;</code>
         *
         * @return The uid.
         */
        public java.lang.String getUid() {
            java.lang.Object ref = uid_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                uid_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the internal id of the record this annotation addresses
         * </pre>
         *
         * <code>string uid = 3;</code>
         *
         * @return The bytes for uid.
         */
        public com.google.protobuf.ByteString getUidBytes() {
            java.lang.Object ref = uid_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                uid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the internal id of the record this annotation addresses
         * </pre>
         *
         * <code>string uid = 3;</code>
         *
         * @param value
         *            The uid to set.
         * @return This builder for chaining.
         */
        public Builder setUid(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            uid_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the internal id of the record this annotation addresses
         * </pre>
         *
         * <code>string uid = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUid() {

            uid_ = getDefaultInstance().getUid();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the internal id of the record this annotation addresses
         * </pre>
         *
         * <code>string uid = 3;</code>
         *
         * @param value
         *            The bytes for uid to set.
         * @return This builder for chaining.
         */
        public Builder setUidBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            uid_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object annotationId_ = "";

        /**
         * <pre>
         * the hash that identifies this annotation
         * </pre>
         *
         * <code>string annotationId = 4;</code>
         *
         * @return The annotationId.
         */
        public java.lang.String getAnnotationId() {
            java.lang.Object ref = annotationId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                annotationId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the hash that identifies this annotation
         * </pre>
         *
         * <code>string annotationId = 4;</code>
         *
         * @return The bytes for annotationId.
         */
        public com.google.protobuf.ByteString getAnnotationIdBytes() {
            java.lang.Object ref = annotationId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                annotationId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the hash that identifies this annotation
         * </pre>
         *
         * <code>string annotationId = 4;</code>
         *
         * @param value
         *            The annotationId to set.
         * @return This builder for chaining.
         */
        public Builder setAnnotationId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            annotationId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the hash that identifies this annotation
         * </pre>
         *
         * <code>string annotationId = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAnnotationId() {

            annotationId_ = getDefaultInstance().getAnnotationId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the hash that identifies this annotation
         * </pre>
         *
         * <code>string annotationId = 4;</code>
         *
         * @param value
         *            The bytes for annotationId to set.
         * @return This builder for chaining.
         */
        public Builder setAnnotationIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            annotationId_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object documentId_ = "";

        /**
         * <pre>
         * the external identifier for this annotations source document.
         * </pre>
         *
         * <code>string documentId = 5;</code>
         *
         * @return The documentId.
         */
        public java.lang.String getDocumentId() {
            java.lang.Object ref = documentId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                documentId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the external identifier for this annotations source document.
         * </pre>
         *
         * <code>string documentId = 5;</code>
         *
         * @return The bytes for documentId.
         */
        public com.google.protobuf.ByteString getDocumentIdBytes() {
            java.lang.Object ref = documentId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                documentId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the external identifier for this annotations source document.
         * </pre>
         *
         * <code>string documentId = 5;</code>
         *
         * @param value
         *            The documentId to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentId(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            documentId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the external identifier for this annotations source document.
         * </pre>
         *
         * <code>string documentId = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDocumentId() {

            documentId_ = getDefaultInstance().getDocumentId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the external identifier for this annotations source document.
         * </pre>
         *
         * <code>string documentId = 5;</code>
         *
         * @param value
         *            The bytes for documentId to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentIdBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            documentId_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object annotationType_ = "";

        /**
         * <pre>
         * the type of this annotation
         * </pre>
         *
         * <code>string annotationType = 6;</code>
         *
         * @return The annotationType.
         */
        public java.lang.String getAnnotationType() {
            java.lang.Object ref = annotationType_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                annotationType_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the type of this annotation
         * </pre>
         *
         * <code>string annotationType = 6;</code>
         *
         * @return The bytes for annotationType.
         */
        public com.google.protobuf.ByteString getAnnotationTypeBytes() {
            java.lang.Object ref = annotationType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                annotationType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the type of this annotation
         * </pre>
         *
         * <code>string annotationType = 6;</code>
         *
         * @param value
         *            The annotationType to set.
         * @return This builder for chaining.
         */
        public Builder setAnnotationType(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            annotationType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the type of this annotation
         * </pre>
         *
         * <code>string annotationType = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAnnotationType() {

            annotationType_ = getDefaultInstance().getAnnotationType();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the type of this annotation
         * </pre>
         *
         * <code>string annotationType = 6;</code>
         *
         * @param value
         *            The bytes for annotationType to set.
         * @return This builder for chaining.
         */
        public Builder setAnnotationTypeBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            annotationType_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object analyticSourceHash_ = "";

        /**
         * <pre>
         * the analytic hash that identifies this annotation's source
         * </pre>
         *
         * <code>string analyticSourceHash = 7;</code>
         *
         * @return The analyticSourceHash.
         */
        public java.lang.String getAnalyticSourceHash() {
            java.lang.Object ref = analyticSourceHash_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                analyticSourceHash_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the analytic hash that identifies this annotation's source
         * </pre>
         *
         * <code>string analyticSourceHash = 7;</code>
         *
         * @return The bytes for analyticSourceHash.
         */
        public com.google.protobuf.ByteString getAnalyticSourceHashBytes() {
            java.lang.Object ref = analyticSourceHash_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                analyticSourceHash_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the analytic hash that identifies this annotation's source
         * </pre>
         *
         * <code>string analyticSourceHash = 7;</code>
         *
         * @param value
         *            The analyticSourceHash to set.
         * @return This builder for chaining.
         */
        public Builder setAnalyticSourceHash(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            analyticSourceHash_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the analytic hash that identifies this annotation's source
         * </pre>
         *
         * <code>string analyticSourceHash = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAnalyticSourceHash() {

            analyticSourceHash_ = getDefaultInstance().getAnalyticSourceHash();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the analytic hash that identifies this annotation's source
         * </pre>
         *
         * <code>string analyticSourceHash = 7;</code>
         *
         * @param value
         *            The bytes for analyticSourceHash to set.
         * @return This builder for chaining.
         */
        public Builder setAnalyticSourceHashBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            analyticSourceHash_ = value;
            onChanged();
            return this;
        }

        private datawave.annotation.protobuf.v1.AnnotationSource source_;
        private com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.AnnotationSource,datawave.annotation.protobuf.v1.AnnotationSource.Builder,datawave.annotation.protobuf.v1.AnnotationSourceOrBuilder> sourceBuilder_;

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         *
         * @return Whether the source field is set.
         */
        public boolean hasSource() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         *
         * @return The source.
         */
        public datawave.annotation.protobuf.v1.AnnotationSource getSource() {
            if (sourceBuilder_ == null) {
                return source_ == null ? datawave.annotation.protobuf.v1.AnnotationSource.getDefaultInstance() : source_;
            } else {
                return sourceBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        public Builder setSource(datawave.annotation.protobuf.v1.AnnotationSource value) {
            if (sourceBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                source_ = value;
                onChanged();
            } else {
                sourceBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        public Builder setSource(datawave.annotation.protobuf.v1.AnnotationSource.Builder builderForValue) {
            if (sourceBuilder_ == null) {
                source_ = builderForValue.build();
                onChanged();
            } else {
                sourceBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        public Builder mergeSource(datawave.annotation.protobuf.v1.AnnotationSource value) {
            if (sourceBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0) && source_ != null && source_ != datawave.annotation.protobuf.v1.AnnotationSource.getDefaultInstance()) {
                    source_ = datawave.annotation.protobuf.v1.AnnotationSource.newBuilder(source_).mergeFrom(value).buildPartial();
                } else {
                    source_ = value;
                }
                onChanged();
            } else {
                sourceBuilder_.mergeFrom(value);
            }
            bitField0_ |= 0x00000001;
            return this;
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        public Builder clearSource() {
            if (sourceBuilder_ == null) {
                source_ = null;
                onChanged();
            } else {
                sourceBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        public datawave.annotation.protobuf.v1.AnnotationSource.Builder getSourceBuilder() {
            bitField0_ |= 0x00000001;
            onChanged();
            return getSourceFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        public datawave.annotation.protobuf.v1.AnnotationSourceOrBuilder getSourceOrBuilder() {
            if (sourceBuilder_ != null) {
                return sourceBuilder_.getMessageOrBuilder();
            } else {
                return source_ == null ? datawave.annotation.protobuf.v1.AnnotationSource.getDefaultInstance() : source_;
            }
        }

        /**
         * <pre>
         * the source details for this annotation.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.AnnotationSource source = 8;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.AnnotationSource,datawave.annotation.protobuf.v1.AnnotationSource.Builder,datawave.annotation.protobuf.v1.AnnotationSourceOrBuilder> getSourceFieldBuilder() {
            if (sourceBuilder_ == null) {
                sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.AnnotationSource,datawave.annotation.protobuf.v1.AnnotationSource.Builder,datawave.annotation.protobuf.v1.AnnotationSourceOrBuilder>(
                                getSource(), getParentForChildren(), isClean());
                source_ = null;
            }
            return sourceBuilder_;
        }

        private java.util.List<datawave.annotation.protobuf.v1.Segment> segments_ = java.util.Collections.emptyList();

        private void ensureSegmentsIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                segments_ = new java.util.ArrayList<datawave.annotation.protobuf.v1.Segment>(segments_);
                bitField0_ |= 0x00000002;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<datawave.annotation.protobuf.v1.Segment,datawave.annotation.protobuf.v1.Segment.Builder,datawave.annotation.protobuf.v1.SegmentOrBuilder> segmentsBuilder_;

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public java.util.List<datawave.annotation.protobuf.v1.Segment> getSegmentsList() {
            if (segmentsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(segments_);
            } else {
                return segmentsBuilder_.getMessageList();
            }
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public int getSegmentsCount() {
            if (segmentsBuilder_ == null) {
                return segments_.size();
            } else {
                return segmentsBuilder_.getCount();
            }
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public datawave.annotation.protobuf.v1.Segment getSegments(int index) {
            if (segmentsBuilder_ == null) {
                return segments_.get(index);
            } else {
                return segmentsBuilder_.getMessage(index);
            }
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder setSegments(int index, datawave.annotation.protobuf.v1.Segment value) {
            if (segmentsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSegmentsIsMutable();
                segments_.set(index, value);
                onChanged();
            } else {
                segmentsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder setSegments(int index, datawave.annotation.protobuf.v1.Segment.Builder builderForValue) {
            if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.set(index, builderForValue.build());
                onChanged();
            } else {
                segmentsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder addSegments(datawave.annotation.protobuf.v1.Segment value) {
            if (segmentsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSegmentsIsMutable();
                segments_.add(value);
                onChanged();
            } else {
                segmentsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder addSegments(int index, datawave.annotation.protobuf.v1.Segment value) {
            if (segmentsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureSegmentsIsMutable();
                segments_.add(index, value);
                onChanged();
            } else {
                segmentsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder addSegments(datawave.annotation.protobuf.v1.Segment.Builder builderForValue) {
            if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.add(builderForValue.build());
                onChanged();
            } else {
                segmentsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder addSegments(int index, datawave.annotation.protobuf.v1.Segment.Builder builderForValue) {
            if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.add(index, builderForValue.build());
                onChanged();
            } else {
                segmentsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder addAllSegments(java.lang.Iterable<? extends datawave.annotation.protobuf.v1.Segment> values) {
            if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, segments_);
                onChanged();
            } else {
                segmentsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder clearSegments() {
            if (segmentsBuilder_ == null) {
                segments_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                segmentsBuilder_.clear();
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public Builder removeSegments(int index) {
            if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.remove(index);
                onChanged();
            } else {
                segmentsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public datawave.annotation.protobuf.v1.Segment.Builder getSegmentsBuilder(int index) {
            return getSegmentsFieldBuilder().getBuilder(index);
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentOrBuilder getSegmentsOrBuilder(int index) {
            if (segmentsBuilder_ == null) {
                return segments_.get(index);
            } else {
                return segmentsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public java.util.List<? extends datawave.annotation.protobuf.v1.SegmentOrBuilder> getSegmentsOrBuilderList() {
            if (segmentsBuilder_ != null) {
                return segmentsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(segments_);
            }
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public datawave.annotation.protobuf.v1.Segment.Builder addSegmentsBuilder() {
            return getSegmentsFieldBuilder().addBuilder(datawave.annotation.protobuf.v1.Segment.getDefaultInstance());
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public datawave.annotation.protobuf.v1.Segment.Builder addSegmentsBuilder(int index) {
            return getSegmentsFieldBuilder().addBuilder(index, datawave.annotation.protobuf.v1.Segment.getDefaultInstance());
        }

        /**
         * <pre>
         * segment data
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.Segment segments = 20;</code>
         */
        public java.util.List<datawave.annotation.protobuf.v1.Segment.Builder> getSegmentsBuilderList() {
            return getSegmentsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<datawave.annotation.protobuf.v1.Segment,datawave.annotation.protobuf.v1.Segment.Builder,datawave.annotation.protobuf.v1.SegmentOrBuilder> getSegmentsFieldBuilder() {
            if (segmentsBuilder_ == null) {
                segmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<datawave.annotation.protobuf.v1.Segment,datawave.annotation.protobuf.v1.Segment.Builder,datawave.annotation.protobuf.v1.SegmentOrBuilder>(
                                segments_, ((bitField0_ & 0x00000002) != 0), getParentForChildren(), isClean());
                segments_ = null;
            }
            return segmentsBuilder_;
        }

        private com.google.protobuf.MapField<java.lang.String,java.lang.String> metadata_;

        private com.google.protobuf.MapField<java.lang.String,java.lang.String> internalGetMetadata() {
            if (metadata_ == null) {
                return com.google.protobuf.MapField.emptyMapField(MetadataDefaultEntryHolder.defaultEntry);
            }
            return metadata_;
        }

        private com.google.protobuf.MapField<java.lang.String,java.lang.String> internalGetMutableMetadata() {
            onChanged();
            ;
            if (metadata_ == null) {
                metadata_ = com.google.protobuf.MapField.newMapField(MetadataDefaultEntryHolder.defaultEntry);
            }
            if (!metadata_.isMutable()) {
                metadata_ = metadata_.copy();
            }
            return metadata_;
        }

        public int getMetadataCount() {
            return internalGetMetadata().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */

        @java.lang.Override
        public boolean containsMetadata(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetMetadata().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
            return getMetadataMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String,java.lang.String> getMetadataMap() {
            return internalGetMetadata().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        @java.lang.Override

        public java.lang.String getMetadataOrDefault(java.lang.String key, java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        @java.lang.Override

        public java.lang.String getMetadataOrThrow(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearMetadata() {
            internalGetMutableMetadata().getMutableMap().clear();
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */

        public Builder removeMetadata(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableMetadata().getMutableMap().remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String,java.lang.String> getMutableMetadata() {
            return internalGetMutableMetadata().getMutableMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        public Builder putMetadata(java.lang.String key, java.lang.String value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableMetadata().getMutableMap().put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */

        public Builder putAllMetadata(java.util.Map<java.lang.String,java.lang.String> values) {
            internalGetMutableMetadata().getMutableMap().putAll(values);
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.v1.Annotation)
    }

    // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.v1.Annotation)
    private static final datawave.annotation.protobuf.v1.Annotation DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new datawave.annotation.protobuf.v1.Annotation();
    }

    public static datawave.annotation.protobuf.v1.Annotation getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Annotation> PARSER = new com.google.protobuf.AbstractParser<Annotation>() {
        @java.lang.Override
        public Annotation parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Annotation> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Annotation> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public datawave.annotation.protobuf.v1.Annotation getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
