// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: warehouse/annotation-core/src/main/protobuf/AnnotationV1.proto

// Protobuf Java Version: 3.25.3
package datawave.annotation.protobuf.v1;

public interface CreateSegmentRequestOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.CreateSegmentRequest)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ignore client-sent id/create_time/update_time/etag
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.Segment segment = 2;</code>
     *
     * @return Whether the segment field is set.
     */
    boolean hasSegment();

    /**
     * <pre>
     * ignore client-sent id/create_time/update_time/etag
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.Segment segment = 2;</code>
     *
     * @return The segment.
     */
    datawave.annotation.protobuf.v1.Segment getSegment();

    /**
     * <pre>
     * ignore client-sent id/create_time/update_time/etag
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.Segment segment = 2;</code>
     */
    datawave.annotation.protobuf.v1.SegmentOrBuilder getSegmentOrBuilder();
}
