// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

public interface DeleteAnnotationRequestOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.DeleteAnnotationRequest)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string annotationId = 1;</code>
     *
     * @return The annotationId.
     */
    java.lang.String getAnnotationId();

    /**
     * <code>string annotationId = 1;</code>
     *
     * @return The bytes for annotationId.
     */
    com.google.protobuf.ByteString getAnnotationIdBytes();

    /**
     * <pre>
     * Optional: require matching etag to delete
     * </pre>
     *
     * <code>string eTag = 3;</code>
     *
     * @return The eTag.
     */
    java.lang.String getETag();

    /**
     * <pre>
     * Optional: require matching etag to delete
     * </pre>
     *
     * <code>string eTag = 3;</code>
     *
     * @return The bytes for eTag.
     */
    com.google.protobuf.ByteString getETagBytes();
}
