// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

public interface GetAnnotationRequestOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.GetAnnotationRequest)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string idType = 1;</code>
     *
     * @return The idType.
     */
    java.lang.String getIdType();

    /**
     * <code>string idType = 1;</code>
     *
     * @return The bytes for idType.
     */
    com.google.protobuf.ByteString getIdTypeBytes();

    /**
     * <code>string annotationId = 2;</code>
     *
     * @return The annotationId.
     */
    java.lang.String getAnnotationId();

    /**
     * <code>string annotationId = 2;</code>
     *
     * @return The bytes for annotationId.
     */
    com.google.protobuf.ByteString getAnnotationIdBytes();
}
