// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

public interface SegmentValueOrBuilder extends
                // @@protoc_insertion_point(interface_extends:datawave.annotation.protobuf.v1.SegmentValue)
                com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * e.g., label
     * </pre>
     *
     * <code>string value = 1;</code>
     *
     * @return The value.
     */
    java.lang.String getValue();

    /**
     * <pre>
     * e.g., label
     * </pre>
     *
     * <code>string value = 1;</code>
     *
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString getValueBytes();

    /**
     * <pre>
     * e.g., confidence
     * </pre>
     *
     * <code>double score = 2;</code>
     *
     * @return The score.
     */
    double getScore();

    /**
     * <pre>
     * type-specific data
     * </pre>
     *
     * <code>string extension = 3;</code>
     *
     * @return Whether the extension field is set.
     */
    boolean hasExtension();

    /**
     * <pre>
     * type-specific data
     * </pre>
     *
     * <code>string extension = 3;</code>
     *
     * @return The extension.
     */
    java.lang.String getExtension();

    /**
     * <pre>
     * type-specific data
     * </pre>
     *
     * <code>string extension = 3;</code>
     *
     * @return The bytes for extension.
     */
    com.google.protobuf.ByteString getExtensionBytes();
}
