// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

/**
 * Protobuf type {@code datawave.annotation.protobuf.v1.UpdateSegmentRequest}
 */
public final class UpdateSegmentRequest extends com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.v1.UpdateSegmentRequest)
                UpdateSegmentRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use UpdateSegmentRequest.newBuilder() to construct.
    private UpdateSegmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private UpdateSegmentRequest() {}

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new UpdateSegmentRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_UpdateSegmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_UpdateSegmentRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.UpdateSegmentRequest.class,
                                        datawave.annotation.protobuf.v1.UpdateSegmentRequest.Builder.class);
    }

    public static final int SEGMENT_FIELD_NUMBER = 1;
    private datawave.annotation.protobuf.v1.Segment segment_;

    /**
     * <pre>
     * must include id
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
     *
     * @return Whether the segment field is set.
     */
    @java.lang.Override
    public boolean hasSegment() {
        return segment_ != null;
    }

    /**
     * <pre>
     * must include id
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
     *
     * @return The segment.
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.Segment getSegment() {
        return segment_ == null ? datawave.annotation.protobuf.v1.Segment.getDefaultInstance() : segment_;
    }

    /**
     * <pre>
     * must include id
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.SegmentOrBuilder getSegmentOrBuilder() {
        return getSegment();
    }

    public static final int UPDATEMASK_FIELD_NUMBER = 2;
    private com.google.protobuf.FieldMask updateMask_;

    /**
     * <pre>
     * e.g. "label,confidence,time"
     * </pre>
     *
     * <code>.google.protobuf.FieldMask updateMask = 2;</code>
     *
     * @return Whether the updateMask field is set.
     */
    @java.lang.Override
    public boolean hasUpdateMask() {
        return updateMask_ != null;
    }

    /**
     * <pre>
     * e.g. "label,confidence,time"
     * </pre>
     *
     * <code>.google.protobuf.FieldMask updateMask = 2;</code>
     *
     * @return The updateMask.
     */
    @java.lang.Override
    public com.google.protobuf.FieldMask getUpdateMask() {
        return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
    }

    /**
     * <pre>
     * e.g. "label,confidence,time"
     * </pre>
     *
     * <code>.google.protobuf.FieldMask updateMask = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
        return getUpdateMask();
    }

    public static final int ALLOWMISSING_FIELD_NUMBER = 3;
    private boolean allowMissing_;

    /**
     * <pre>
     * If set, require etag to match for optimistic concurrency.
     * </pre>
     *
     * <code>bool allowMissing = 3;</code>
     *
     * @return The allowMissing.
     */
    @java.lang.Override
    public boolean getAllowMissing() {
        return allowMissing_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (segment_ != null) {
            output.writeMessage(1, getSegment());
        }
        if (updateMask_ != null) {
            output.writeMessage(2, getUpdateMask());
        }
        if (allowMissing_ != false) {
            output.writeBool(3, allowMissing_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (segment_ != null) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getSegment());
        }
        if (updateMask_ != null) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getUpdateMask());
        }
        if (allowMissing_ != false) {
            size += com.google.protobuf.CodedOutputStream.computeBoolSize(3, allowMissing_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof datawave.annotation.protobuf.v1.UpdateSegmentRequest)) {
            return super.equals(obj);
        }
        datawave.annotation.protobuf.v1.UpdateSegmentRequest other = (datawave.annotation.protobuf.v1.UpdateSegmentRequest) obj;

        if (hasSegment() != other.hasSegment())
            return false;
        if (hasSegment()) {
            if (!getSegment().equals(other.getSegment()))
                return false;
        }
        if (hasUpdateMask() != other.hasUpdateMask())
            return false;
        if (hasUpdateMask()) {
            if (!getUpdateMask().equals(other.getUpdateMask()))
                return false;
        }
        if (getAllowMissing() != other.getAllowMissing())
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasSegment()) {
            hash = (37 * hash) + SEGMENT_FIELD_NUMBER;
            hash = (53 * hash) + getSegment().hashCode();
        }
        if (hasUpdateMask()) {
            hash = (37 * hash) + UPDATEMASK_FIELD_NUMBER;
            hash = (53 * hash) + getUpdateMask().hashCode();
        }
        hash = (37 * hash) + ALLOWMISSING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getAllowMissing());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseDelimitedFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest parseFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(datawave.annotation.protobuf.v1.UpdateSegmentRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code datawave.annotation.protobuf.v1.UpdateSegmentRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.v1.UpdateSegmentRequest)
                    datawave.annotation.protobuf.v1.UpdateSegmentRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_UpdateSegmentRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_UpdateSegmentRequest_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.UpdateSegmentRequest.class,
                                            datawave.annotation.protobuf.v1.UpdateSegmentRequest.Builder.class);
        }

        // Construct using datawave.annotation.protobuf.v1.UpdateSegmentRequest.newBuilder()
        private Builder() {

        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (segmentBuilder_ == null) {
                segment_ = null;
            } else {
                segment_ = null;
                segmentBuilder_ = null;
            }
            if (updateMaskBuilder_ == null) {
                updateMask_ = null;
            } else {
                updateMask_ = null;
                updateMaskBuilder_ = null;
            }
            allowMissing_ = false;

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_UpdateSegmentRequest_descriptor;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.UpdateSegmentRequest getDefaultInstanceForType() {
            return datawave.annotation.protobuf.v1.UpdateSegmentRequest.getDefaultInstance();
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.UpdateSegmentRequest build() {
            datawave.annotation.protobuf.v1.UpdateSegmentRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.UpdateSegmentRequest buildPartial() {
            datawave.annotation.protobuf.v1.UpdateSegmentRequest result = new datawave.annotation.protobuf.v1.UpdateSegmentRequest(this);
            if (segmentBuilder_ == null) {
                result.segment_ = segment_;
            } else {
                result.segment_ = segmentBuilder_.build();
            }
            if (updateMaskBuilder_ == null) {
                result.updateMask_ = updateMask_;
            } else {
                result.updateMask_ = updateMaskBuilder_.build();
            }
            result.allowMissing_ = allowMissing_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof datawave.annotation.protobuf.v1.UpdateSegmentRequest) {
                return mergeFrom((datawave.annotation.protobuf.v1.UpdateSegmentRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(datawave.annotation.protobuf.v1.UpdateSegmentRequest other) {
            if (other == datawave.annotation.protobuf.v1.UpdateSegmentRequest.getDefaultInstance())
                return this;
            if (other.hasSegment()) {
                mergeSegment(other.getSegment());
            }
            if (other.hasUpdateMask()) {
                mergeUpdateMask(other.getUpdateMask());
            }
            if (other.getAllowMissing() != false) {
                setAllowMissing(other.getAllowMissing());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            input.readMessage(getSegmentFieldBuilder().getBuilder(), extensionRegistry);

                            break;
                        } // case 10
                        case 18: {
                            input.readMessage(getUpdateMaskFieldBuilder().getBuilder(), extensionRegistry);

                            break;
                        } // case 18
                        case 24: {
                            allowMissing_ = input.readBool();

                            break;
                        } // case 24
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private datawave.annotation.protobuf.v1.Segment segment_;
        private com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.Segment,datawave.annotation.protobuf.v1.Segment.Builder,datawave.annotation.protobuf.v1.SegmentOrBuilder> segmentBuilder_;

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         *
         * @return Whether the segment field is set.
         */
        public boolean hasSegment() {
            return segmentBuilder_ != null || segment_ != null;
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         *
         * @return The segment.
         */
        public datawave.annotation.protobuf.v1.Segment getSegment() {
            if (segmentBuilder_ == null) {
                return segment_ == null ? datawave.annotation.protobuf.v1.Segment.getDefaultInstance() : segment_;
            } else {
                return segmentBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        public Builder setSegment(datawave.annotation.protobuf.v1.Segment value) {
            if (segmentBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                segment_ = value;
                onChanged();
            } else {
                segmentBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        public Builder setSegment(datawave.annotation.protobuf.v1.Segment.Builder builderForValue) {
            if (segmentBuilder_ == null) {
                segment_ = builderForValue.build();
                onChanged();
            } else {
                segmentBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        public Builder mergeSegment(datawave.annotation.protobuf.v1.Segment value) {
            if (segmentBuilder_ == null) {
                if (segment_ != null) {
                    segment_ = datawave.annotation.protobuf.v1.Segment.newBuilder(segment_).mergeFrom(value).buildPartial();
                } else {
                    segment_ = value;
                }
                onChanged();
            } else {
                segmentBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        public Builder clearSegment() {
            if (segmentBuilder_ == null) {
                segment_ = null;
                onChanged();
            } else {
                segment_ = null;
                segmentBuilder_ = null;
            }

            return this;
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        public datawave.annotation.protobuf.v1.Segment.Builder getSegmentBuilder() {

            onChanged();
            return getSegmentFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentOrBuilder getSegmentOrBuilder() {
            if (segmentBuilder_ != null) {
                return segmentBuilder_.getMessageOrBuilder();
            } else {
                return segment_ == null ? datawave.annotation.protobuf.v1.Segment.getDefaultInstance() : segment_;
            }
        }

        /**
         * <pre>
         * must include id
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.Segment segment = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.Segment,datawave.annotation.protobuf.v1.Segment.Builder,datawave.annotation.protobuf.v1.SegmentOrBuilder> getSegmentFieldBuilder() {
            if (segmentBuilder_ == null) {
                segmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.Segment,datawave.annotation.protobuf.v1.Segment.Builder,datawave.annotation.protobuf.v1.SegmentOrBuilder>(
                                getSegment(), getParentForChildren(), isClean());
                segment_ = null;
            }
            return segmentBuilder_;
        }

        private com.google.protobuf.FieldMask updateMask_;
        private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.FieldMask,com.google.protobuf.FieldMask.Builder,com.google.protobuf.FieldMaskOrBuilder> updateMaskBuilder_;

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         *
         * @return Whether the updateMask field is set.
         */
        public boolean hasUpdateMask() {
            return updateMaskBuilder_ != null || updateMask_ != null;
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         *
         * @return The updateMask.
         */
        public com.google.protobuf.FieldMask getUpdateMask() {
            if (updateMaskBuilder_ == null) {
                return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
            } else {
                return updateMaskBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        public Builder setUpdateMask(com.google.protobuf.FieldMask value) {
            if (updateMaskBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                updateMask_ = value;
                onChanged();
            } else {
                updateMaskBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        public Builder setUpdateMask(com.google.protobuf.FieldMask.Builder builderForValue) {
            if (updateMaskBuilder_ == null) {
                updateMask_ = builderForValue.build();
                onChanged();
            } else {
                updateMaskBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        public Builder mergeUpdateMask(com.google.protobuf.FieldMask value) {
            if (updateMaskBuilder_ == null) {
                if (updateMask_ != null) {
                    updateMask_ = com.google.protobuf.FieldMask.newBuilder(updateMask_).mergeFrom(value).buildPartial();
                } else {
                    updateMask_ = value;
                }
                onChanged();
            } else {
                updateMaskBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        public Builder clearUpdateMask() {
            if (updateMaskBuilder_ == null) {
                updateMask_ = null;
                onChanged();
            } else {
                updateMask_ = null;
                updateMaskBuilder_ = null;
            }

            return this;
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        public com.google.protobuf.FieldMask.Builder getUpdateMaskBuilder() {

            onChanged();
            return getUpdateMaskFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        public com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder() {
            if (updateMaskBuilder_ != null) {
                return updateMaskBuilder_.getMessageOrBuilder();
            } else {
                return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
            }
        }

        /**
         * <pre>
         * e.g. "label,confidence,time"
         * </pre>
         *
         * <code>.google.protobuf.FieldMask updateMask = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.FieldMask,com.google.protobuf.FieldMask.Builder,com.google.protobuf.FieldMaskOrBuilder> getUpdateMaskFieldBuilder() {
            if (updateMaskBuilder_ == null) {
                updateMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.google.protobuf.FieldMask,com.google.protobuf.FieldMask.Builder,com.google.protobuf.FieldMaskOrBuilder>(
                                getUpdateMask(), getParentForChildren(), isClean());
                updateMask_ = null;
            }
            return updateMaskBuilder_;
        }

        private boolean allowMissing_;

        /**
         * <pre>
         * If set, require etag to match for optimistic concurrency.
         * </pre>
         *
         * <code>bool allowMissing = 3;</code>
         *
         * @return The allowMissing.
         */
        @java.lang.Override
        public boolean getAllowMissing() {
            return allowMissing_;
        }

        /**
         * <pre>
         * If set, require etag to match for optimistic concurrency.
         * </pre>
         *
         * <code>bool allowMissing = 3;</code>
         *
         * @param value
         *            The allowMissing to set.
         * @return This builder for chaining.
         */
        public Builder setAllowMissing(boolean value) {

            allowMissing_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * If set, require etag to match for optimistic concurrency.
         * </pre>
         *
         * <code>bool allowMissing = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAllowMissing() {

            allowMissing_ = false;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.v1.UpdateSegmentRequest)
    }

    // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.v1.UpdateSegmentRequest)
    private static final datawave.annotation.protobuf.v1.UpdateSegmentRequest DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new datawave.annotation.protobuf.v1.UpdateSegmentRequest();
    }

    public static datawave.annotation.protobuf.v1.UpdateSegmentRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateSegmentRequest> PARSER = new com.google.protobuf.AbstractParser<UpdateSegmentRequest>() {
        @java.lang.Override
        public UpdateSegmentRequest parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<UpdateSegmentRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateSegmentRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public datawave.annotation.protobuf.v1.UpdateSegmentRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
