package datawave.microservice.http.converter.html;

/**
 * A provider for head and footer banner messages to appear on any page with HTML generated by {@link AbstractDatawaveHttpMessageConverter}.
 */
public interface BannerProvider {
    String getHeadBanner();
    
    String getFootBanner();
}
