<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>gov.nsa.datawave.microservice</groupId>
        <artifactId>datawave-microservice-parent</artifactId>
        <version>4.0.14-SNAPSHOT</version>
        <relativePath>../../../microservice-parent/pom.xml</relativePath>
    </parent>
    <artifactId>annotation-api</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <properties>
        <version.datawave>7.40.0</version.datawave>
    </properties>
    <dependencies>
        <dependency>
            <groupId>gov.nsa.datawave.core</groupId>
            <artifactId>datawave-core-annotation</artifactId>
            <version>${version.datawave}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
