// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AnnotationV1.proto

package datawave.annotation.protobuf.v1;

/**
 * Protobuf type {@code datawave.annotation.protobuf.v1.Segment}
 */
public final class Segment extends com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:datawave.annotation.protobuf.v1.Segment)
                SegmentOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Segment.newBuilder() to construct.
    private Segment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Segment() {
        segmentHash_ = "";
        values_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new Segment();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Segment_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
            case 50:
                return internalGetMetadata();
            default:
                throw new RuntimeException("Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Segment_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.Segment.class, datawave.annotation.protobuf.v1.Segment.Builder.class);
    }

    public static final int SEGMENTHASH_FIELD_NUMBER = 1;
    private volatile java.lang.Object segmentHash_;

    /**
     * <pre>
     * the 32-bit hash used for segment identification and grouping.
     * </pre>
     *
     * <code>string segmentHash = 1;</code>
     *
     * @return The segmentHash.
     */
    @java.lang.Override
    public java.lang.String getSegmentHash() {
        java.lang.Object ref = segmentHash_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            segmentHash_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * the 32-bit hash used for segment identification and grouping.
     * </pre>
     *
     * <code>string segmentHash = 1;</code>
     *
     * @return The bytes for segmentHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSegmentHashBytes() {
        java.lang.Object ref = segmentHash_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            segmentHash_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int BOUNDARY_FIELD_NUMBER = 2;
    private datawave.annotation.protobuf.v1.SegmentBoundary boundary_;

    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
     *
     * @return Whether the boundary field is set.
     */
    @java.lang.Override
    public boolean hasBoundary() {
        return boundary_ != null;
    }

    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
     *
     * @return The boundary.
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.SegmentBoundary getBoundary() {
        return boundary_ == null ? datawave.annotation.protobuf.v1.SegmentBoundary.getDefaultInstance() : boundary_;
    }

    /**
     * <pre>
     * the boundary for this segment.
     * </pre>
     *
     * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.SegmentBoundaryOrBuilder getBoundaryOrBuilder() {
        return getBoundary();
    }

    public static final int VALUES_FIELD_NUMBER = 3;
    private java.util.List<datawave.annotation.protobuf.v1.SegmentValue> values_;

    /**
     * <pre>
     * multiple values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
     */
    @java.lang.Override
    public java.util.List<datawave.annotation.protobuf.v1.SegmentValue> getValuesList() {
        return values_;
    }

    /**
     * <pre>
     * multiple values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends datawave.annotation.protobuf.v1.SegmentValueOrBuilder> getValuesOrBuilderList() {
        return values_;
    }

    /**
     * <pre>
     * multiple values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
     */
    @java.lang.Override
    public int getValuesCount() {
        return values_.size();
    }

    /**
     * <pre>
     * multiple values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.SegmentValue getValues(int index) {
        return values_.get(index);
    }

    /**
     * <pre>
     * multiple values associated with this segment.
     * </pre>
     *
     * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
     */
    @java.lang.Override
    public datawave.annotation.protobuf.v1.SegmentValueOrBuilder getValuesOrBuilder(int index) {
        return values_.get(index);
    }

    public static final int METADATA_FIELD_NUMBER = 50;

    private static final class MetadataDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<java.lang.String,java.lang.String> defaultEntry = com.google.protobuf.MapEntry.<java.lang.String,java.lang.String> newDefaultInstance(
                        datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Segment_MetadataEntry_descriptor,
                        com.google.protobuf.WireFormat.FieldType.STRING, "", com.google.protobuf.WireFormat.FieldType.STRING, "");
    }

    private com.google.protobuf.MapField<java.lang.String,java.lang.String> metadata_;

    private com.google.protobuf.MapField<java.lang.String,java.lang.String> internalGetMetadata() {
        if (metadata_ == null) {
            return com.google.protobuf.MapField.emptyMapField(MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
    }

    public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
    }

    /**
     * <pre>
     * optional segment metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */

    @java.lang.Override
    public boolean containsMetadata(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetMetadata().getMap().containsKey(key);
    }

    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
        return getMetadataMap();
    }

    /**
     * <pre>
     * optional segment metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String,java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
    }

    /**
     * <pre>
     * optional segment metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrDefault(java.lang.String key, java.lang.String defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <pre>
     * optional segment metadata
     * </pre>
     *
     * <code>map&lt;string, string&gt; metadata = 50;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrThrow(java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!getSegmentHashBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, segmentHash_);
        }
        if (boundary_ != null) {
            output.writeMessage(2, getBoundary());
        }
        for (int i = 0; i < values_.size(); i++) {
            output.writeMessage(3, values_.get(i));
        }
        com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output, internalGetMetadata(), MetadataDefaultEntryHolder.defaultEntry, 50);
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getSegmentHashBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, segmentHash_);
        }
        if (boundary_ != null) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getBoundary());
        }
        for (int i = 0; i < values_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, values_.get(i));
        }
        for (java.util.Map.Entry<java.lang.String,java.lang.String> entry : internalGetMetadata().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String,java.lang.String> metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
                            .setKey(entry.getKey()).setValue(entry.getValue()).build();
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(50, metadata__);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof datawave.annotation.protobuf.v1.Segment)) {
            return super.equals(obj);
        }
        datawave.annotation.protobuf.v1.Segment other = (datawave.annotation.protobuf.v1.Segment) obj;

        if (!getSegmentHash().equals(other.getSegmentHash()))
            return false;
        if (hasBoundary() != other.hasBoundary())
            return false;
        if (hasBoundary()) {
            if (!getBoundary().equals(other.getBoundary()))
                return false;
        }
        if (!getValuesList().equals(other.getValuesList()))
            return false;
        if (!internalGetMetadata().equals(other.internalGetMetadata()))
            return false;
        if (!getUnknownFields().equals(other.getUnknownFields()))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SEGMENTHASH_FIELD_NUMBER;
        hash = (53 * hash) + getSegmentHash().hashCode();
        if (hasBoundary()) {
            hash = (37 * hash) + BOUNDARY_FIELD_NUMBER;
            hash = (53 * hash) + getBoundary().hashCode();
        }
        if (getValuesCount() > 0) {
            hash = (37 * hash) + VALUES_FIELD_NUMBER;
            hash = (53 * hash) + getValuesList().hashCode();
        }
        if (!internalGetMetadata().getMap().isEmpty()) {
            hash = (37 * hash) + METADATA_FIELD_NUMBER;
            hash = (53 * hash) + internalGetMetadata().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Segment parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.Segment parseDelimitedFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static datawave.annotation.protobuf.v1.Segment parseFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(datawave.annotation.protobuf.v1.Segment prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code datawave.annotation.protobuf.v1.Segment}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:datawave.annotation.protobuf.v1.Segment)
                    datawave.annotation.protobuf.v1.SegmentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Segment_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(int number) {
            switch (number) {
                case 50:
                    return internalGetMetadata();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
            switch (number) {
                case 50:
                    return internalGetMutableMetadata();
                default:
                    throw new RuntimeException("Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Segment_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(datawave.annotation.protobuf.v1.Segment.class,
                                            datawave.annotation.protobuf.v1.Segment.Builder.class);
        }

        // Construct using datawave.annotation.protobuf.v1.Segment.newBuilder()
        private Builder() {

        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            segmentHash_ = "";

            if (boundaryBuilder_ == null) {
                boundary_ = null;
            } else {
                boundary_ = null;
                boundaryBuilder_ = null;
            }
            if (valuesBuilder_ == null) {
                values_ = java.util.Collections.emptyList();
            } else {
                values_ = null;
                valuesBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000001);
            internalGetMutableMetadata().clear();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return datawave.annotation.protobuf.v1.AnnotationV1.internal_static_datawave_annotation_protobuf_v1_Segment_descriptor;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.Segment getDefaultInstanceForType() {
            return datawave.annotation.protobuf.v1.Segment.getDefaultInstance();
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.Segment build() {
            datawave.annotation.protobuf.v1.Segment result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public datawave.annotation.protobuf.v1.Segment buildPartial() {
            datawave.annotation.protobuf.v1.Segment result = new datawave.annotation.protobuf.v1.Segment(this);
            int from_bitField0_ = bitField0_;
            result.segmentHash_ = segmentHash_;
            if (boundaryBuilder_ == null) {
                result.boundary_ = boundary_;
            } else {
                result.boundary_ = boundaryBuilder_.build();
            }
            if (valuesBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    values_ = java.util.Collections.unmodifiableList(values_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.values_ = values_;
            } else {
                result.values_ = valuesBuilder_.build();
            }
            result.metadata_ = internalGetMetadata();
            result.metadata_.makeImmutable();
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof datawave.annotation.protobuf.v1.Segment) {
                return mergeFrom((datawave.annotation.protobuf.v1.Segment) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(datawave.annotation.protobuf.v1.Segment other) {
            if (other == datawave.annotation.protobuf.v1.Segment.getDefaultInstance())
                return this;
            if (!other.getSegmentHash().isEmpty()) {
                segmentHash_ = other.segmentHash_;
                onChanged();
            }
            if (other.hasBoundary()) {
                mergeBoundary(other.getBoundary());
            }
            if (valuesBuilder_ == null) {
                if (!other.values_.isEmpty()) {
                    if (values_.isEmpty()) {
                        values_ = other.values_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureValuesIsMutable();
                        values_.addAll(other.values_);
                    }
                    onChanged();
                }
            } else {
                if (!other.values_.isEmpty()) {
                    if (valuesBuilder_.isEmpty()) {
                        valuesBuilder_.dispose();
                        valuesBuilder_ = null;
                        values_ = other.values_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        valuesBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getValuesFieldBuilder() : null;
                    } else {
                        valuesBuilder_.addAllMessages(other.values_);
                    }
                }
            }
            internalGetMutableMetadata().mergeFrom(other.internalGetMetadata());
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            segmentHash_ = input.readStringRequireUtf8();

                            break;
                        } // case 10
                        case 18: {
                            input.readMessage(getBoundaryFieldBuilder().getBuilder(), extensionRegistry);

                            break;
                        } // case 18
                        case 26: {
                            datawave.annotation.protobuf.v1.SegmentValue m = input.readMessage(datawave.annotation.protobuf.v1.SegmentValue.parser(),
                                            extensionRegistry);
                            if (valuesBuilder_ == null) {
                                ensureValuesIsMutable();
                                values_.add(m);
                            } else {
                                valuesBuilder_.addMessage(m);
                            }
                            break;
                        } // case 26
                        case 402: {
                            com.google.protobuf.MapEntry<java.lang.String,java.lang.String> metadata__ = input
                                            .readMessage(MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            internalGetMutableMetadata().getMutableMap().put(metadata__.getKey(), metadata__.getValue());
                            break;
                        } // case 402
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object segmentHash_ = "";

        /**
         * <pre>
         * the 32-bit hash used for segment identification and grouping.
         * </pre>
         *
         * <code>string segmentHash = 1;</code>
         *
         * @return The segmentHash.
         */
        public java.lang.String getSegmentHash() {
            java.lang.Object ref = segmentHash_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                segmentHash_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * the 32-bit hash used for segment identification and grouping.
         * </pre>
         *
         * <code>string segmentHash = 1;</code>
         *
         * @return The bytes for segmentHash.
         */
        public com.google.protobuf.ByteString getSegmentHashBytes() {
            java.lang.Object ref = segmentHash_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                segmentHash_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * the 32-bit hash used for segment identification and grouping.
         * </pre>
         *
         * <code>string segmentHash = 1;</code>
         *
         * @param value
         *            The segmentHash to set.
         * @return This builder for chaining.
         */
        public Builder setSegmentHash(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            segmentHash_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the 32-bit hash used for segment identification and grouping.
         * </pre>
         *
         * <code>string segmentHash = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSegmentHash() {

            segmentHash_ = getDefaultInstance().getSegmentHash();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * the 32-bit hash used for segment identification and grouping.
         * </pre>
         *
         * <code>string segmentHash = 1;</code>
         *
         * @param value
         *            The bytes for segmentHash to set.
         * @return This builder for chaining.
         */
        public Builder setSegmentHashBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            segmentHash_ = value;
            onChanged();
            return this;
        }

        private datawave.annotation.protobuf.v1.SegmentBoundary boundary_;
        private com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.SegmentBoundary,datawave.annotation.protobuf.v1.SegmentBoundary.Builder,datawave.annotation.protobuf.v1.SegmentBoundaryOrBuilder> boundaryBuilder_;

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         *
         * @return Whether the boundary field is set.
         */
        public boolean hasBoundary() {
            return boundaryBuilder_ != null || boundary_ != null;
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         *
         * @return The boundary.
         */
        public datawave.annotation.protobuf.v1.SegmentBoundary getBoundary() {
            if (boundaryBuilder_ == null) {
                return boundary_ == null ? datawave.annotation.protobuf.v1.SegmentBoundary.getDefaultInstance() : boundary_;
            } else {
                return boundaryBuilder_.getMessage();
            }
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        public Builder setBoundary(datawave.annotation.protobuf.v1.SegmentBoundary value) {
            if (boundaryBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                boundary_ = value;
                onChanged();
            } else {
                boundaryBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        public Builder setBoundary(datawave.annotation.protobuf.v1.SegmentBoundary.Builder builderForValue) {
            if (boundaryBuilder_ == null) {
                boundary_ = builderForValue.build();
                onChanged();
            } else {
                boundaryBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        public Builder mergeBoundary(datawave.annotation.protobuf.v1.SegmentBoundary value) {
            if (boundaryBuilder_ == null) {
                if (boundary_ != null) {
                    boundary_ = datawave.annotation.protobuf.v1.SegmentBoundary.newBuilder(boundary_).mergeFrom(value).buildPartial();
                } else {
                    boundary_ = value;
                }
                onChanged();
            } else {
                boundaryBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        public Builder clearBoundary() {
            if (boundaryBuilder_ == null) {
                boundary_ = null;
                onChanged();
            } else {
                boundary_ = null;
                boundaryBuilder_ = null;
            }

            return this;
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentBoundary.Builder getBoundaryBuilder() {

            onChanged();
            return getBoundaryFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentBoundaryOrBuilder getBoundaryOrBuilder() {
            if (boundaryBuilder_ != null) {
                return boundaryBuilder_.getMessageOrBuilder();
            } else {
                return boundary_ == null ? datawave.annotation.protobuf.v1.SegmentBoundary.getDefaultInstance() : boundary_;
            }
        }

        /**
         * <pre>
         * the boundary for this segment.
         * </pre>
         *
         * <code>.datawave.annotation.protobuf.v1.SegmentBoundary boundary = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.SegmentBoundary,datawave.annotation.protobuf.v1.SegmentBoundary.Builder,datawave.annotation.protobuf.v1.SegmentBoundaryOrBuilder> getBoundaryFieldBuilder() {
            if (boundaryBuilder_ == null) {
                boundaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<datawave.annotation.protobuf.v1.SegmentBoundary,datawave.annotation.protobuf.v1.SegmentBoundary.Builder,datawave.annotation.protobuf.v1.SegmentBoundaryOrBuilder>(
                                getBoundary(), getParentForChildren(), isClean());
                boundary_ = null;
            }
            return boundaryBuilder_;
        }

        private java.util.List<datawave.annotation.protobuf.v1.SegmentValue> values_ = java.util.Collections.emptyList();

        private void ensureValuesIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                values_ = new java.util.ArrayList<datawave.annotation.protobuf.v1.SegmentValue>(values_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<datawave.annotation.protobuf.v1.SegmentValue,datawave.annotation.protobuf.v1.SegmentValue.Builder,datawave.annotation.protobuf.v1.SegmentValueOrBuilder> valuesBuilder_;

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public java.util.List<datawave.annotation.protobuf.v1.SegmentValue> getValuesList() {
            if (valuesBuilder_ == null) {
                return java.util.Collections.unmodifiableList(values_);
            } else {
                return valuesBuilder_.getMessageList();
            }
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public int getValuesCount() {
            if (valuesBuilder_ == null) {
                return values_.size();
            } else {
                return valuesBuilder_.getCount();
            }
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentValue getValues(int index) {
            if (valuesBuilder_ == null) {
                return values_.get(index);
            } else {
                return valuesBuilder_.getMessage(index);
            }
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder setValues(int index, datawave.annotation.protobuf.v1.SegmentValue value) {
            if (valuesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureValuesIsMutable();
                values_.set(index, value);
                onChanged();
            } else {
                valuesBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder setValues(int index, datawave.annotation.protobuf.v1.SegmentValue.Builder builderForValue) {
            if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                values_.set(index, builderForValue.build());
                onChanged();
            } else {
                valuesBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder addValues(datawave.annotation.protobuf.v1.SegmentValue value) {
            if (valuesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureValuesIsMutable();
                values_.add(value);
                onChanged();
            } else {
                valuesBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder addValues(int index, datawave.annotation.protobuf.v1.SegmentValue value) {
            if (valuesBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureValuesIsMutable();
                values_.add(index, value);
                onChanged();
            } else {
                valuesBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder addValues(datawave.annotation.protobuf.v1.SegmentValue.Builder builderForValue) {
            if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                values_.add(builderForValue.build());
                onChanged();
            } else {
                valuesBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder addValues(int index, datawave.annotation.protobuf.v1.SegmentValue.Builder builderForValue) {
            if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                values_.add(index, builderForValue.build());
                onChanged();
            } else {
                valuesBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder addAllValues(java.lang.Iterable<? extends datawave.annotation.protobuf.v1.SegmentValue> values) {
            if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, values_);
                onChanged();
            } else {
                valuesBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder clearValues() {
            if (valuesBuilder_ == null) {
                values_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                valuesBuilder_.clear();
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public Builder removeValues(int index) {
            if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                values_.remove(index);
                onChanged();
            } else {
                valuesBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentValue.Builder getValuesBuilder(int index) {
            return getValuesFieldBuilder().getBuilder(index);
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentValueOrBuilder getValuesOrBuilder(int index) {
            if (valuesBuilder_ == null) {
                return values_.get(index);
            } else {
                return valuesBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public java.util.List<? extends datawave.annotation.protobuf.v1.SegmentValueOrBuilder> getValuesOrBuilderList() {
            if (valuesBuilder_ != null) {
                return valuesBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(values_);
            }
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentValue.Builder addValuesBuilder() {
            return getValuesFieldBuilder().addBuilder(datawave.annotation.protobuf.v1.SegmentValue.getDefaultInstance());
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public datawave.annotation.protobuf.v1.SegmentValue.Builder addValuesBuilder(int index) {
            return getValuesFieldBuilder().addBuilder(index, datawave.annotation.protobuf.v1.SegmentValue.getDefaultInstance());
        }

        /**
         * <pre>
         * multiple values associated with this segment.
         * </pre>
         *
         * <code>repeated .datawave.annotation.protobuf.v1.SegmentValue values = 3;</code>
         */
        public java.util.List<datawave.annotation.protobuf.v1.SegmentValue.Builder> getValuesBuilderList() {
            return getValuesFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<datawave.annotation.protobuf.v1.SegmentValue,datawave.annotation.protobuf.v1.SegmentValue.Builder,datawave.annotation.protobuf.v1.SegmentValueOrBuilder> getValuesFieldBuilder() {
            if (valuesBuilder_ == null) {
                valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<datawave.annotation.protobuf.v1.SegmentValue,datawave.annotation.protobuf.v1.SegmentValue.Builder,datawave.annotation.protobuf.v1.SegmentValueOrBuilder>(
                                values_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
                values_ = null;
            }
            return valuesBuilder_;
        }

        private com.google.protobuf.MapField<java.lang.String,java.lang.String> metadata_;

        private com.google.protobuf.MapField<java.lang.String,java.lang.String> internalGetMetadata() {
            if (metadata_ == null) {
                return com.google.protobuf.MapField.emptyMapField(MetadataDefaultEntryHolder.defaultEntry);
            }
            return metadata_;
        }

        private com.google.protobuf.MapField<java.lang.String,java.lang.String> internalGetMutableMetadata() {
            onChanged();
            ;
            if (metadata_ == null) {
                metadata_ = com.google.protobuf.MapField.newMapField(MetadataDefaultEntryHolder.defaultEntry);
            }
            if (!metadata_.isMutable()) {
                metadata_ = metadata_.copy();
            }
            return metadata_;
        }

        public int getMetadataCount() {
            return internalGetMetadata().getMap().size();
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */

        @java.lang.Override
        public boolean containsMetadata(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetMetadata().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
            return getMetadataMap();
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String,java.lang.String> getMetadataMap() {
            return internalGetMetadata().getMap();
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        @java.lang.Override

        public java.lang.String getMetadataOrDefault(java.lang.String key, java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        @java.lang.Override

        public java.lang.String getMetadataOrThrow(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String,java.lang.String> map = internalGetMetadata().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearMetadata() {
            internalGetMutableMetadata().getMutableMap().clear();
            return this;
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */

        public Builder removeMetadata(java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableMetadata().getMutableMap().remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String,java.lang.String> getMutableMetadata() {
            return internalGetMutableMetadata().getMutableMap();
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */
        public Builder putMetadata(java.lang.String key, java.lang.String value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableMetadata().getMutableMap().put(key, value);
            return this;
        }

        /**
         * <pre>
         * optional segment metadata
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 50;</code>
         */

        public Builder putAllMetadata(java.util.Map<java.lang.String,java.lang.String> values) {
            internalGetMutableMetadata().getMutableMap().putAll(values);
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:datawave.annotation.protobuf.v1.Segment)
    }

    // @@protoc_insertion_point(class_scope:datawave.annotation.protobuf.v1.Segment)
    private static final datawave.annotation.protobuf.v1.Segment DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new datawave.annotation.protobuf.v1.Segment();
    }

    public static datawave.annotation.protobuf.v1.Segment getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Segment> PARSER = new com.google.protobuf.AbstractParser<Segment>() {
        @java.lang.Override
        public Segment parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<Segment> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Segment> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public datawave.annotation.protobuf.v1.Segment getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
