name: Compose Coordinator

on:
  workflow_call:
    outputs:
      compose-check-result:
        description: 'The result of the compose check gate job'
        value: ${{ jobs.compose-check-jobs.outputs.status }}

jobs:
  call-compose-tests:
    uses: ./.github/workflows/compose-tests.yml
    with:
      allow-snapshots: false
    secrets: inherit
  call-compose-tests-with-snapshots:
    continue-on-error: true
    uses: ./.github/workflows/compose-tests.yml
    with:
      allow-snapshots: true
    secrets: inherit
  compose-check-jobs:
    runs-on: ubuntu-latest
    if: always()
    needs: [call-compose-tests, call-compose-tests-with-snapshots]
    outputs:
      status: ${{ steps.check.outputs.status }}
    steps:
      - name: Status message
        run: |
             echo "compose-tests: ${{ needs.call-compose-tests.result }}"
             echo "compose-tests-with-snapshots: ${{ needs.call-compose-tests-with-snapshots.result }}"
      - name: Checks that at least one of the compose jobs ran successfully
        id: check
        run: |
          if [[ "${{ needs.call-compose-tests.result }}" == "success" || "${{ needs.call-compose-tests-with-snapshots.result }}" == "success" ]]; then
            echo "status=success" >> $GITHUB_OUTPUT
          elif [[ "${{ needs.call-compose-tests.result }}" == "cancelled" && "${{ needs.call-compose-tests-with-snapshots.result }}" == "cancelled" ]]; then
            echo "status=cancelled" >> $GITHUB_OUTPUT
            echo "Compose jobs were cancelled"
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "Neither compose jobs passed"
            exit 1
          fi
